/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample;


import nu.studer.sample.tables.WnwbDefinition;
import nu.studer.sample.tables.WnwbExternalref;
import nu.studer.sample.tables.WnwbExternalrelationtype;
import nu.studer.sample.tables.WnwbExternalsystem;
import nu.studer.sample.tables.WnwbLemmatag;
import nu.studer.sample.tables.WnwbLexicalentry;
import nu.studer.sample.tables.WnwbLexicon;
import nu.studer.sample.tables.WnwbRefcode;
import nu.studer.sample.tables.WnwbSense;
import nu.studer.sample.tables.WnwbSenseexample;
import nu.studer.sample.tables.WnwbSenserelation;
import nu.studer.sample.tables.WnwbSenserelationtype;
import nu.studer.sample.tables.WnwbSensetag;
import nu.studer.sample.tables.WnwbStatement;
import nu.studer.sample.tables.WnwbSynset;
import nu.studer.sample.tables.WnwbSynsetrelation;
import nu.studer.sample.tables.WnwbSynsetrelationtype;
import nu.studer.sample.tables.WnwbSynsettag;
import nu.studer.sample.tables.WnwbTag;
import nu.studer.sample.tables.WnwbTaskorder;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index WNWB_DEFINITION_SENSE_ID_07F73760 = Internal.createIndex(DSL.name("wnwb_definition_sense_id_07f73760"), WnwbDefinition.WNWB_DEFINITION, new OrderField[] { WnwbDefinition.WNWB_DEFINITION.SENSE_ID }, false);
    public static final Index WNWB_DEFINITION_SYNSET_ID_CEDA91A3 = Internal.createIndex(DSL.name("wnwb_definition_synset_id_ceda91a3"), WnwbDefinition.WNWB_DEFINITION, new OrderField[] { WnwbDefinition.WNWB_DEFINITION.SYNSET_ID }, false);
    public static final Index WNWB_EXTERNALREF_REFERENCE_484A5820 = Internal.createIndex(DSL.name("wnwb_externalref_reference_484a5820"), WnwbExternalref.WNWB_EXTERNALREF, new OrderField[] { WnwbExternalref.WNWB_EXTERNALREF.REFERENCE }, false);
    public static final Index WNWB_EXTERNALREF_REFERENCE_484A5820_LIKE = Internal.createIndex(DSL.name("wnwb_externalref_reference_484a5820_like"), WnwbExternalref.WNWB_EXTERNALREF, new OrderField[] { WnwbExternalref.WNWB_EXTERNALREF.REFERENCE }, false);
    public static final Index WNWB_EXTERNALREF_REL_TYPE_ID_5832C6D2 = Internal.createIndex(DSL.name("wnwb_externalref_rel_type_id_5832c6d2"), WnwbExternalref.WNWB_EXTERNALREF, new OrderField[] { WnwbExternalref.WNWB_EXTERNALREF.REL_TYPE_ID }, false);
    public static final Index WNWB_EXTERNALREF_SENSE_ID_FE9D5580 = Internal.createIndex(DSL.name("wnwb_externalref_sense_id_fe9d5580"), WnwbExternalref.WNWB_EXTERNALREF, new OrderField[] { WnwbExternalref.WNWB_EXTERNALREF.SENSE_ID }, false);
    public static final Index WNWB_EXTERNALREF_SYNSET_ID_DA65B8D8 = Internal.createIndex(DSL.name("wnwb_externalref_synset_id_da65b8d8"), WnwbExternalref.WNWB_EXTERNALREF, new OrderField[] { WnwbExternalref.WNWB_EXTERNALREF.SYNSET_ID }, false);
    public static final Index WNWB_EXTERNALREF_SYS_ID_ID_F0181889 = Internal.createIndex(DSL.name("wnwb_externalref_sys_id_id_f0181889"), WnwbExternalref.WNWB_EXTERNALREF, new OrderField[] { WnwbExternalref.WNWB_EXTERNALREF.SYS_ID_ID }, false);
    public static final Index WNWB_EXTERNALRELATIONTYPE_LEXICON_ID_B8515F64 = Internal.createIndex(DSL.name("wnwb_externalrelationtype_lexicon_id_b8515f64"), WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE, new OrderField[] { WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE.LEXICON_ID }, false);
    public static final Index WNWB_EXTERNALSYSTEM_LOCAL_LEXICON_ID_EF06FA64 = Internal.createIndex(DSL.name("wnwb_externalsystem_local_lexicon_id_ef06fa64"), WnwbExternalsystem.WNWB_EXTERNALSYSTEM, new OrderField[] { WnwbExternalsystem.WNWB_EXTERNALSYSTEM.LOCAL_LEXICON_ID }, false);
    public static final Index WNWB_LEMMATAG_LEXICAL_ENTRY_ID_3B4AF2B1 = Internal.createIndex(DSL.name("wnwb_lemmatag_lexical_entry_id_3b4af2b1"), WnwbLemmatag.WNWB_LEMMATAG, new OrderField[] { WnwbLemmatag.WNWB_LEMMATAG.LEXICAL_ENTRY_ID }, false);
    public static final Index WNWB_LEMMATAG_TAG_ID_5A072CB3 = Internal.createIndex(DSL.name("wnwb_lemmatag_tag_id_5a072cb3"), WnwbLemmatag.WNWB_LEMMATAG, new OrderField[] { WnwbLemmatag.WNWB_LEMMATAG.TAG_ID }, false);
    public static final Index WNWB_LEXICALENTRY_LEMMA_11B21783 = Internal.createIndex(DSL.name("wnwb_lexicalentry_lemma_11b21783"), WnwbLexicalentry.WNWB_LEXICALENTRY, new OrderField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.LEMMA }, false);
    public static final Index WNWB_LEXICALENTRY_LEMMA_11B21783_LIKE = Internal.createIndex(DSL.name("wnwb_lexicalentry_lemma_11b21783_like"), WnwbLexicalentry.WNWB_LEXICALENTRY, new OrderField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.LEMMA }, false);
    public static final Index WNWB_LEXICALENTRY_LEXICON_ID_FE960594 = Internal.createIndex(DSL.name("wnwb_lexicalentry_lexicon_id_fe960594"), WnwbLexicalentry.WNWB_LEXICALENTRY, new OrderField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.LEXICON_ID }, false);
    public static final Index WNWB_LEXICALENTRY_PART_OF_SPEECH_26F577EC = Internal.createIndex(DSL.name("wnwb_lexicalentry_part_of_speech_26f577ec"), WnwbLexicalentry.WNWB_LEXICALENTRY, new OrderField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.PART_OF_SPEECH }, false);
    public static final Index WNWB_LEXICALENTRY_PART_OF_SPEECH_26F577EC_LIKE = Internal.createIndex(DSL.name("wnwb_lexicalentry_part_of_speech_26f577ec_like"), WnwbLexicalentry.WNWB_LEXICALENTRY, new OrderField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.PART_OF_SPEECH }, false);
    public static final Index WNWB_LEXICON_RESOURCE_ID_B1C767F2 = Internal.createIndex(DSL.name("wnwb_lexicon_resource_id_b1c767f2"), WnwbLexicon.WNWB_LEXICON, new OrderField[] { WnwbLexicon.WNWB_LEXICON.RESOURCE_ID }, false);
    public static final Index WNWB_REFCODE_CODE_6FFF01D2 = Internal.createIndex(DSL.name("wnwb_refcode_code_6fff01d2"), WnwbRefcode.WNWB_REFCODE, new OrderField[] { WnwbRefcode.WNWB_REFCODE.CODE }, false);
    public static final Index WNWB_REFCODE_CODE_6FFF01D2_LIKE = Internal.createIndex(DSL.name("wnwb_refcode_code_6fff01d2_like"), WnwbRefcode.WNWB_REFCODE, new OrderField[] { WnwbRefcode.WNWB_REFCODE.CODE }, false);
    public static final Index WNWB_REFCODE_DOMAIN_13324BED = Internal.createIndex(DSL.name("wnwb_refcode_domain_13324bed"), WnwbRefcode.WNWB_REFCODE, new OrderField[] { WnwbRefcode.WNWB_REFCODE.DOMAIN }, false);
    public static final Index WNWB_REFCODE_DOMAIN_13324BED_LIKE = Internal.createIndex(DSL.name("wnwb_refcode_domain_13324bed_like"), WnwbRefcode.WNWB_REFCODE, new OrderField[] { WnwbRefcode.WNWB_REFCODE.DOMAIN }, false);
    public static final Index WNWB_SENSE_LABEL_F98A94E1 = Internal.createIndex(DSL.name("wnwb_sense_label_f98a94e1"), WnwbSense.WNWB_SENSE, new OrderField[] { WnwbSense.WNWB_SENSE.LABEL }, false);
    public static final Index WNWB_SENSE_LABEL_F98A94E1_LIKE = Internal.createIndex(DSL.name("wnwb_sense_label_f98a94e1_like"), WnwbSense.WNWB_SENSE, new OrderField[] { WnwbSense.WNWB_SENSE.LABEL }, false);
    public static final Index WNWB_SENSE_LEXICAL_ENTRY_ID_818118DC = Internal.createIndex(DSL.name("wnwb_sense_lexical_entry_id_818118dc"), WnwbSense.WNWB_SENSE, new OrderField[] { WnwbSense.WNWB_SENSE.LEXICAL_ENTRY_ID }, false);
    public static final Index WNWB_SENSE_SYNSET_ID_F32F0334 = Internal.createIndex(DSL.name("wnwb_sense_synset_id_f32f0334"), WnwbSense.WNWB_SENSE, new OrderField[] { WnwbSense.WNWB_SENSE.SYNSET_ID }, false);
    public static final Index WNWB_SENSEEXAMPLE_SENSE_ID_5B247889 = Internal.createIndex(DSL.name("wnwb_senseexample_sense_id_5b247889"), WnwbSenseexample.WNWB_SENSEEXAMPLE, new OrderField[] { WnwbSenseexample.WNWB_SENSEEXAMPLE.SENSE_ID }, false);
    public static final Index WNWB_SENSERELATION_A_SENSE_ID_C0C51749 = Internal.createIndex(DSL.name("wnwb_senserelation_a_sense_id_c0c51749"), WnwbSenserelation.WNWB_SENSERELATION, new OrderField[] { WnwbSenserelation.WNWB_SENSERELATION.A_SENSE_ID }, false);
    public static final Index WNWB_SENSERELATION_B_SENSE_ID_FEC3E062 = Internal.createIndex(DSL.name("wnwb_senserelation_b_sense_id_fec3e062"), WnwbSenserelation.WNWB_SENSERELATION, new OrderField[] { WnwbSenserelation.WNWB_SENSERELATION.B_SENSE_ID }, false);
    public static final Index WNWB_SENSERELATION_REL_TYPE_ID_8718A120 = Internal.createIndex(DSL.name("wnwb_senserelation_rel_type_id_8718a120"), WnwbSenserelation.WNWB_SENSERELATION, new OrderField[] { WnwbSenserelation.WNWB_SENSERELATION.REL_TYPE_ID }, false);
    public static final Index WNWB_SENSERELATIONTYPE_LEXICON_ID_82C3453D = Internal.createIndex(DSL.name("wnwb_senserelationtype_lexicon_id_82c3453d"), WnwbSenserelationtype.WNWB_SENSERELATIONTYPE, new OrderField[] { WnwbSenserelationtype.WNWB_SENSERELATIONTYPE.LEXICON_ID }, false);
    public static final Index WNWB_SENSETAG_SENSE_ID_F7FB7B9D = Internal.createIndex(DSL.name("wnwb_sensetag_sense_id_f7fb7b9d"), WnwbSensetag.WNWB_SENSETAG, new OrderField[] { WnwbSensetag.WNWB_SENSETAG.SENSE_ID }, false);
    public static final Index WNWB_SENSETAG_TAG_ID_FCED1B6A = Internal.createIndex(DSL.name("wnwb_sensetag_tag_id_fced1b6a"), WnwbSensetag.WNWB_SENSETAG, new OrderField[] { WnwbSensetag.WNWB_SENSETAG.TAG_ID }, false);
    public static final Index WNWB_STATEMENT_DEFINITION_ID_C6356A08 = Internal.createIndex(DSL.name("wnwb_statement_definition_id_c6356a08"), WnwbStatement.WNWB_STATEMENT, new OrderField[] { WnwbStatement.WNWB_STATEMENT.DEFINITION_ID }, false);
    public static final Index WNWB_SYNSET_LABEL_2EF989CA = Internal.createIndex(DSL.name("wnwb_synset_label_2ef989ca"), WnwbSynset.WNWB_SYNSET, new OrderField[] { WnwbSynset.WNWB_SYNSET.LABEL }, false);
    public static final Index WNWB_SYNSET_LABEL_2EF989CA_LIKE = Internal.createIndex(DSL.name("wnwb_synset_label_2ef989ca_like"), WnwbSynset.WNWB_SYNSET, new OrderField[] { WnwbSynset.WNWB_SYNSET.LABEL }, false);
    public static final Index WNWB_SYNSET_LEXICON_ID_2D4135F8 = Internal.createIndex(DSL.name("wnwb_synset_lexicon_id_2d4135f8"), WnwbSynset.WNWB_SYNSET, new OrderField[] { WnwbSynset.WNWB_SYNSET.LEXICON_ID }, false);
    public static final Index WNWB_SYNSETRELATION_A_SYNSET_ID_99F48C44 = Internal.createIndex(DSL.name("wnwb_synsetrelation_a_synset_id_99f48c44"), WnwbSynsetrelation.WNWB_SYNSETRELATION, new OrderField[] { WnwbSynsetrelation.WNWB_SYNSETRELATION.A_SYNSET_ID }, false);
    public static final Index WNWB_SYNSETRELATION_B_SYNSET_ID_C84D4349 = Internal.createIndex(DSL.name("wnwb_synsetrelation_b_synset_id_c84d4349"), WnwbSynsetrelation.WNWB_SYNSETRELATION, new OrderField[] { WnwbSynsetrelation.WNWB_SYNSETRELATION.B_SYNSET_ID }, false);
    public static final Index WNWB_SYNSETRELATION_REL_TYPE_ID_EB53DCEC = Internal.createIndex(DSL.name("wnwb_synsetrelation_rel_type_id_eb53dcec"), WnwbSynsetrelation.WNWB_SYNSETRELATION, new OrderField[] { WnwbSynsetrelation.WNWB_SYNSETRELATION.REL_TYPE_ID }, false);
    public static final Index WNWB_SYNSETRELATIONTYPE_LEXICON_ID_8F83F300 = Internal.createIndex(DSL.name("wnwb_synsetrelationtype_lexicon_id_8f83f300"), WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE, new OrderField[] { WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE.LEXICON_ID }, false);
    public static final Index WNWB_SYNSETTAG_SYNSET_ID_F74B55FF = Internal.createIndex(DSL.name("wnwb_synsettag_synset_id_f74b55ff"), WnwbSynsettag.WNWB_SYNSETTAG, new OrderField[] { WnwbSynsettag.WNWB_SYNSETTAG.SYNSET_ID }, false);
    public static final Index WNWB_SYNSETTAG_TAG_ID_9A41102F = Internal.createIndex(DSL.name("wnwb_synsettag_tag_id_9a41102f"), WnwbSynsettag.WNWB_SYNSETTAG, new OrderField[] { WnwbSynsettag.WNWB_SYNSETTAG.TAG_ID }, false);
    public static final Index WNWB_TAG_CATEGORY_A43FB0EB = Internal.createIndex(DSL.name("wnwb_tag_category_a43fb0eb"), WnwbTag.WNWB_TAG, new OrderField[] { WnwbTag.WNWB_TAG.CATEGORY }, false);
    public static final Index WNWB_TAG_CATEGORY_A43FB0EB_LIKE = Internal.createIndex(DSL.name("wnwb_tag_category_a43fb0eb_like"), WnwbTag.WNWB_TAG, new OrderField[] { WnwbTag.WNWB_TAG.CATEGORY }, false);
    public static final Index WNWB_TASKORDER_MAIN_LEXICON_ID_89633296 = Internal.createIndex(DSL.name("wnwb_taskorder_main_lexicon_id_89633296"), WnwbTaskorder.WNWB_TASKORDER, new OrderField[] { WnwbTaskorder.WNWB_TASKORDER.MAIN_LEXICON_ID }, false);
    public static final Index WNWB_TASKORDER_OTHER_LEXICON_ID_D5CBEAD2 = Internal.createIndex(DSL.name("wnwb_taskorder_other_lexicon_id_d5cbead2"), WnwbTaskorder.WNWB_TASKORDER, new OrderField[] { WnwbTaskorder.WNWB_TASKORDER.OTHER_LEXICON_ID }, false);
}
