/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample;


import nu.studer.sample.tables.WnwbDefinition;
import nu.studer.sample.tables.WnwbExternalref;
import nu.studer.sample.tables.WnwbExternalrelationtype;
import nu.studer.sample.tables.WnwbExternalsystem;
import nu.studer.sample.tables.WnwbLemmatag;
import nu.studer.sample.tables.WnwbLexicalentry;
import nu.studer.sample.tables.WnwbLexicalresource;
import nu.studer.sample.tables.WnwbLexicon;
import nu.studer.sample.tables.WnwbRefcode;
import nu.studer.sample.tables.WnwbSense;
import nu.studer.sample.tables.WnwbSenseexample;
import nu.studer.sample.tables.WnwbSenserelation;
import nu.studer.sample.tables.WnwbSenserelationtype;
import nu.studer.sample.tables.WnwbSensetag;
import nu.studer.sample.tables.WnwbStatement;
import nu.studer.sample.tables.WnwbSynset;
import nu.studer.sample.tables.WnwbSynsetrelation;
import nu.studer.sample.tables.WnwbSynsetrelationtype;
import nu.studer.sample.tables.WnwbSynsettag;
import nu.studer.sample.tables.WnwbTag;
import nu.studer.sample.tables.WnwbTaskorder;
import nu.studer.sample.tables.records.WnwbDefinitionRecord;
import nu.studer.sample.tables.records.WnwbExternalrefRecord;
import nu.studer.sample.tables.records.WnwbExternalrelationtypeRecord;
import nu.studer.sample.tables.records.WnwbExternalsystemRecord;
import nu.studer.sample.tables.records.WnwbLemmatagRecord;
import nu.studer.sample.tables.records.WnwbLexicalentryRecord;
import nu.studer.sample.tables.records.WnwbLexicalresourceRecord;
import nu.studer.sample.tables.records.WnwbLexiconRecord;
import nu.studer.sample.tables.records.WnwbRefcodeRecord;
import nu.studer.sample.tables.records.WnwbSenseRecord;
import nu.studer.sample.tables.records.WnwbSenseexampleRecord;
import nu.studer.sample.tables.records.WnwbSenserelationRecord;
import nu.studer.sample.tables.records.WnwbSenserelationtypeRecord;
import nu.studer.sample.tables.records.WnwbSensetagRecord;
import nu.studer.sample.tables.records.WnwbStatementRecord;
import nu.studer.sample.tables.records.WnwbSynsetRecord;
import nu.studer.sample.tables.records.WnwbSynsetrelationRecord;
import nu.studer.sample.tables.records.WnwbSynsetrelationtypeRecord;
import nu.studer.sample.tables.records.WnwbSynsettagRecord;
import nu.studer.sample.tables.records.WnwbTagRecord;
import nu.studer.sample.tables.records.WnwbTaskorderRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WnwbDefinitionRecord> WNWB_DEFINITION_PKEY = Internal.createUniqueKey(WnwbDefinition.WNWB_DEFINITION, DSL.name("wnwb_definition_pkey"), new TableField[] { WnwbDefinition.WNWB_DEFINITION.ID }, true);
    public static final UniqueKey<WnwbExternalrefRecord> WNWB_EXTERNALREF_PKEY = Internal.createUniqueKey(WnwbExternalref.WNWB_EXTERNALREF, DSL.name("wnwb_externalref_pkey"), new TableField[] { WnwbExternalref.WNWB_EXTERNALREF.ID }, true);
    public static final UniqueKey<WnwbExternalrelationtypeRecord> WNWB_EXTERNALRELATIONTYPE_PKEY = Internal.createUniqueKey(WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE, DSL.name("wnwb_externalrelationtype_pkey"), new TableField[] { WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE.ID }, true);
    public static final UniqueKey<WnwbExternalsystemRecord> WNWB_EXTERNALSYSTEM_PKEY = Internal.createUniqueKey(WnwbExternalsystem.WNWB_EXTERNALSYSTEM, DSL.name("wnwb_externalsystem_pkey"), new TableField[] { WnwbExternalsystem.WNWB_EXTERNALSYSTEM.ID }, true);
    public static final UniqueKey<WnwbLemmatagRecord> WNWB_LEMMATAG_PKEY = Internal.createUniqueKey(WnwbLemmatag.WNWB_LEMMATAG, DSL.name("wnwb_lemmatag_pkey"), new TableField[] { WnwbLemmatag.WNWB_LEMMATAG.ID }, true);
    public static final UniqueKey<WnwbLexicalentryRecord> WNWB_LEXICALENTRY_PKEY = Internal.createUniqueKey(WnwbLexicalentry.WNWB_LEXICALENTRY, DSL.name("wnwb_lexicalentry_pkey"), new TableField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.ID }, true);
    public static final UniqueKey<WnwbLexicalresourceRecord> WNWB_LEXICALRESOURCE_PKEY = Internal.createUniqueKey(WnwbLexicalresource.WNWB_LEXICALRESOURCE, DSL.name("wnwb_lexicalresource_pkey"), new TableField[] { WnwbLexicalresource.WNWB_LEXICALRESOURCE.ID }, true);
    public static final UniqueKey<WnwbLexiconRecord> WNWB_LEXICON_PKEY = Internal.createUniqueKey(WnwbLexicon.WNWB_LEXICON, DSL.name("wnwb_lexicon_pkey"), new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final UniqueKey<WnwbRefcodeRecord> WNWB_REFCODE_PKEY = Internal.createUniqueKey(WnwbRefcode.WNWB_REFCODE, DSL.name("wnwb_refcode_pkey"), new TableField[] { WnwbRefcode.WNWB_REFCODE.ID }, true);
    public static final UniqueKey<WnwbSenseRecord> WNWB_SENSE_PKEY = Internal.createUniqueKey(WnwbSense.WNWB_SENSE, DSL.name("wnwb_sense_pkey"), new TableField[] { WnwbSense.WNWB_SENSE.ID }, true);
    public static final UniqueKey<WnwbSenseexampleRecord> WNWB_SENSEEXAMPLE_PKEY = Internal.createUniqueKey(WnwbSenseexample.WNWB_SENSEEXAMPLE, DSL.name("wnwb_senseexample_pkey"), new TableField[] { WnwbSenseexample.WNWB_SENSEEXAMPLE.ID }, true);
    public static final UniqueKey<WnwbSenserelationRecord> WNWB_SENSERELATION_PKEY = Internal.createUniqueKey(WnwbSenserelation.WNWB_SENSERELATION, DSL.name("wnwb_senserelation_pkey"), new TableField[] { WnwbSenserelation.WNWB_SENSERELATION.ID }, true);
    public static final UniqueKey<WnwbSenserelationtypeRecord> WNWB_SENSERELATIONTYPE_PKEY = Internal.createUniqueKey(WnwbSenserelationtype.WNWB_SENSERELATIONTYPE, DSL.name("wnwb_senserelationtype_pkey"), new TableField[] { WnwbSenserelationtype.WNWB_SENSERELATIONTYPE.ID }, true);
    public static final UniqueKey<WnwbSensetagRecord> WNWB_SENSETAG_PKEY = Internal.createUniqueKey(WnwbSensetag.WNWB_SENSETAG, DSL.name("wnwb_sensetag_pkey"), new TableField[] { WnwbSensetag.WNWB_SENSETAG.ID }, true);
    public static final UniqueKey<WnwbStatementRecord> WNWB_STATEMENT_PKEY = Internal.createUniqueKey(WnwbStatement.WNWB_STATEMENT, DSL.name("wnwb_statement_pkey"), new TableField[] { WnwbStatement.WNWB_STATEMENT.ID }, true);
    public static final UniqueKey<WnwbSynsetRecord> WNWB_SYNSET_PKEY = Internal.createUniqueKey(WnwbSynset.WNWB_SYNSET, DSL.name("wnwb_synset_pkey"), new TableField[] { WnwbSynset.WNWB_SYNSET.ID }, true);
    public static final UniqueKey<WnwbSynsetrelationRecord> WNWB_SYNSETRELATION_PKEY = Internal.createUniqueKey(WnwbSynsetrelation.WNWB_SYNSETRELATION, DSL.name("wnwb_synsetrelation_pkey"), new TableField[] { WnwbSynsetrelation.WNWB_SYNSETRELATION.ID }, true);
    public static final UniqueKey<WnwbSynsetrelationtypeRecord> WNWB_SYNSETRELATIONTYPE_PKEY = Internal.createUniqueKey(WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE, DSL.name("wnwb_synsetrelationtype_pkey"), new TableField[] { WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE.ID }, true);
    public static final UniqueKey<WnwbSynsettagRecord> WNWB_SYNSETTAG_PKEY = Internal.createUniqueKey(WnwbSynsettag.WNWB_SYNSETTAG, DSL.name("wnwb_synsettag_pkey"), new TableField[] { WnwbSynsettag.WNWB_SYNSETTAG.ID }, true);
    public static final UniqueKey<WnwbTagRecord> WNWB_TAG_PKEY = Internal.createUniqueKey(WnwbTag.WNWB_TAG, DSL.name("wnwb_tag_pkey"), new TableField[] { WnwbTag.WNWB_TAG.ID }, true);
    public static final UniqueKey<WnwbTaskorderRecord> WNWB_TASKORDER_PKEY = Internal.createUniqueKey(WnwbTaskorder.WNWB_TASKORDER, DSL.name("wnwb_taskorder_pkey"), new TableField[] { WnwbTaskorder.WNWB_TASKORDER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WnwbDefinitionRecord, WnwbSenseRecord> WNWB_DEFINITION__WNWB_DEFINITION_SENSE_ID_07F73760_FK_WNWB_SENSE_ID = Internal.createForeignKey(WnwbDefinition.WNWB_DEFINITION, DSL.name("wnwb_definition_sense_id_07f73760_fk_wnwb_sense_id"), new TableField[] { WnwbDefinition.WNWB_DEFINITION.SENSE_ID }, Keys.WNWB_SENSE_PKEY, new TableField[] { WnwbSense.WNWB_SENSE.ID }, true);
    public static final ForeignKey<WnwbDefinitionRecord, WnwbSynsetRecord> WNWB_DEFINITION__WNWB_DEFINITION_SYNSET_ID_CEDA91A3_FK_WNWB_SYNSET_ID = Internal.createForeignKey(WnwbDefinition.WNWB_DEFINITION, DSL.name("wnwb_definition_synset_id_ceda91a3_fk_wnwb_synset_id"), new TableField[] { WnwbDefinition.WNWB_DEFINITION.SYNSET_ID }, Keys.WNWB_SYNSET_PKEY, new TableField[] { WnwbSynset.WNWB_SYNSET.ID }, true);
    public static final ForeignKey<WnwbExternalrefRecord, WnwbExternalrelationtypeRecord> WNWB_EXTERNALREF__WNWB_EXTERNALREF_REL_TYPE_ID_5832C6D2_FK_WNWB_EXTE = Internal.createForeignKey(WnwbExternalref.WNWB_EXTERNALREF, DSL.name("wnwb_externalref_rel_type_id_5832c6d2_fk_wnwb_exte"), new TableField[] { WnwbExternalref.WNWB_EXTERNALREF.REL_TYPE_ID }, Keys.WNWB_EXTERNALRELATIONTYPE_PKEY, new TableField[] { WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE.ID }, true);
    public static final ForeignKey<WnwbExternalrefRecord, WnwbSenseRecord> WNWB_EXTERNALREF__WNWB_EXTERNALREF_SENSE_ID_FE9D5580_FK_WNWB_SENSE_ID = Internal.createForeignKey(WnwbExternalref.WNWB_EXTERNALREF, DSL.name("wnwb_externalref_sense_id_fe9d5580_fk_wnwb_sense_id"), new TableField[] { WnwbExternalref.WNWB_EXTERNALREF.SENSE_ID }, Keys.WNWB_SENSE_PKEY, new TableField[] { WnwbSense.WNWB_SENSE.ID }, true);
    public static final ForeignKey<WnwbExternalrefRecord, WnwbSynsetRecord> WNWB_EXTERNALREF__WNWB_EXTERNALREF_SYNSET_ID_DA65B8D8_FK_WNWB_SYNSET_ID = Internal.createForeignKey(WnwbExternalref.WNWB_EXTERNALREF, DSL.name("wnwb_externalref_synset_id_da65b8d8_fk_wnwb_synset_id"), new TableField[] { WnwbExternalref.WNWB_EXTERNALREF.SYNSET_ID }, Keys.WNWB_SYNSET_PKEY, new TableField[] { WnwbSynset.WNWB_SYNSET.ID }, true);
    public static final ForeignKey<WnwbExternalrefRecord, WnwbExternalsystemRecord> WNWB_EXTERNALREF__WNWB_EXTERNALREF_SYS_ID_ID_F0181889_FK_WNWB_EXTERNALSYSTEM_ID = Internal.createForeignKey(WnwbExternalref.WNWB_EXTERNALREF, DSL.name("wnwb_externalref_sys_id_id_f0181889_fk_wnwb_externalsystem_id"), new TableField[] { WnwbExternalref.WNWB_EXTERNALREF.SYS_ID_ID }, Keys.WNWB_EXTERNALSYSTEM_PKEY, new TableField[] { WnwbExternalsystem.WNWB_EXTERNALSYSTEM.ID }, true);
    public static final ForeignKey<WnwbExternalrelationtypeRecord, WnwbLexiconRecord> WNWB_EXTERNALRELATIONTYPE__WNWB_EXTERNALRELATIO_LEXICON_ID_B8515F64_FK_WNWB_LEXI = Internal.createForeignKey(WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE, DSL.name("wnwb_externalrelatio_lexicon_id_b8515f64_fk_wnwb_lexi"), new TableField[] { WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE.LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final ForeignKey<WnwbExternalsystemRecord, WnwbLexiconRecord> WNWB_EXTERNALSYSTEM__WNWB_EXTERNALSYSTEM_LOCAL_LEXICON_ID_EF06FA64_FK_WNWB_LEXI = Internal.createForeignKey(WnwbExternalsystem.WNWB_EXTERNALSYSTEM, DSL.name("wnwb_externalsystem_local_lexicon_id_ef06fa64_fk_wnwb_lexi"), new TableField[] { WnwbExternalsystem.WNWB_EXTERNALSYSTEM.LOCAL_LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final ForeignKey<WnwbLemmatagRecord, WnwbLexicalentryRecord> WNWB_LEMMATAG__WNWB_LEMMATAG_LEXICAL_ENTRY_ID_3B4AF2B1_FK_WNWB_LEXICALENTRY_ID = Internal.createForeignKey(WnwbLemmatag.WNWB_LEMMATAG, DSL.name("wnwb_lemmatag_lexical_entry_id_3b4af2b1_fk_wnwb_lexicalentry_id"), new TableField[] { WnwbLemmatag.WNWB_LEMMATAG.LEXICAL_ENTRY_ID }, Keys.WNWB_LEXICALENTRY_PKEY, new TableField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.ID }, true);
    public static final ForeignKey<WnwbLemmatagRecord, WnwbTagRecord> WNWB_LEMMATAG__WNWB_LEMMATAG_TAG_ID_5A072CB3_FK_WNWB_TAG_ID = Internal.createForeignKey(WnwbLemmatag.WNWB_LEMMATAG, DSL.name("wnwb_lemmatag_tag_id_5a072cb3_fk_wnwb_tag_id"), new TableField[] { WnwbLemmatag.WNWB_LEMMATAG.TAG_ID }, Keys.WNWB_TAG_PKEY, new TableField[] { WnwbTag.WNWB_TAG.ID }, true);
    public static final ForeignKey<WnwbLexicalentryRecord, WnwbLexiconRecord> WNWB_LEXICALENTRY__WNWB_LEXICALENTRY_LEXICON_ID_FE960594_FK_WNWB_LEXICON_ID = Internal.createForeignKey(WnwbLexicalentry.WNWB_LEXICALENTRY, DSL.name("wnwb_lexicalentry_lexicon_id_fe960594_fk_wnwb_lexicon_id"), new TableField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final ForeignKey<WnwbLexiconRecord, WnwbLexicalresourceRecord> WNWB_LEXICON__WNWB_LEXICON_RESOURCE_ID_B1C767F2_FK_WNWB_LEXICALRESOURCE_ID = Internal.createForeignKey(WnwbLexicon.WNWB_LEXICON, DSL.name("wnwb_lexicon_resource_id_b1c767f2_fk_wnwb_lexicalresource_id"), new TableField[] { WnwbLexicon.WNWB_LEXICON.RESOURCE_ID }, Keys.WNWB_LEXICALRESOURCE_PKEY, new TableField[] { WnwbLexicalresource.WNWB_LEXICALRESOURCE.ID }, true);
    public static final ForeignKey<WnwbSenseRecord, WnwbLexicalentryRecord> WNWB_SENSE__WNWB_SENSE_LEXICAL_ENTRY_ID_818118DC_FK_WNWB_LEXICALENTRY_ID = Internal.createForeignKey(WnwbSense.WNWB_SENSE, DSL.name("wnwb_sense_lexical_entry_id_818118dc_fk_wnwb_lexicalentry_id"), new TableField[] { WnwbSense.WNWB_SENSE.LEXICAL_ENTRY_ID }, Keys.WNWB_LEXICALENTRY_PKEY, new TableField[] { WnwbLexicalentry.WNWB_LEXICALENTRY.ID }, true);
    public static final ForeignKey<WnwbSenseRecord, WnwbSynsetRecord> WNWB_SENSE__WNWB_SENSE_SYNSET_ID_F32F0334_FK_WNWB_SYNSET_ID = Internal.createForeignKey(WnwbSense.WNWB_SENSE, DSL.name("wnwb_sense_synset_id_f32f0334_fk_wnwb_synset_id"), new TableField[] { WnwbSense.WNWB_SENSE.SYNSET_ID }, Keys.WNWB_SYNSET_PKEY, new TableField[] { WnwbSynset.WNWB_SYNSET.ID }, true);
    public static final ForeignKey<WnwbSenseexampleRecord, WnwbSenseRecord> WNWB_SENSEEXAMPLE__WNWB_SENSEEXAMPLE_SENSE_ID_5B247889_FK_WNWB_SENSE_ID = Internal.createForeignKey(WnwbSenseexample.WNWB_SENSEEXAMPLE, DSL.name("wnwb_senseexample_sense_id_5b247889_fk_wnwb_sense_id"), new TableField[] { WnwbSenseexample.WNWB_SENSEEXAMPLE.SENSE_ID }, Keys.WNWB_SENSE_PKEY, new TableField[] { WnwbSense.WNWB_SENSE.ID }, true);
    public static final ForeignKey<WnwbSenserelationRecord, WnwbSenseRecord> WNWB_SENSERELATION__WNWB_SENSERELATION_A_SENSE_ID_C0C51749_FK_WNWB_SENSE_ID = Internal.createForeignKey(WnwbSenserelation.WNWB_SENSERELATION, DSL.name("wnwb_senserelation_a_sense_id_c0c51749_fk_wnwb_sense_id"), new TableField[] { WnwbSenserelation.WNWB_SENSERELATION.A_SENSE_ID }, Keys.WNWB_SENSE_PKEY, new TableField[] { WnwbSense.WNWB_SENSE.ID }, true);
    public static final ForeignKey<WnwbSenserelationRecord, WnwbSenseRecord> WNWB_SENSERELATION__WNWB_SENSERELATION_B_SENSE_ID_FEC3E062_FK_WNWB_SENSE_ID = Internal.createForeignKey(WnwbSenserelation.WNWB_SENSERELATION, DSL.name("wnwb_senserelation_b_sense_id_fec3e062_fk_wnwb_sense_id"), new TableField[] { WnwbSenserelation.WNWB_SENSERELATION.B_SENSE_ID }, Keys.WNWB_SENSE_PKEY, new TableField[] { WnwbSense.WNWB_SENSE.ID }, true);
    public static final ForeignKey<WnwbSenserelationRecord, WnwbSenserelationtypeRecord> WNWB_SENSERELATION__WNWB_SENSERELATION_REL_TYPE_ID_8718A120_FK_WNWB_SENS = Internal.createForeignKey(WnwbSenserelation.WNWB_SENSERELATION, DSL.name("wnwb_senserelation_rel_type_id_8718a120_fk_wnwb_sens"), new TableField[] { WnwbSenserelation.WNWB_SENSERELATION.REL_TYPE_ID }, Keys.WNWB_SENSERELATIONTYPE_PKEY, new TableField[] { WnwbSenserelationtype.WNWB_SENSERELATIONTYPE.ID }, true);
    public static final ForeignKey<WnwbSenserelationtypeRecord, WnwbLexiconRecord> WNWB_SENSERELATIONTYPE__WNWB_SENSERELATIONTYPE_LEXICON_ID_82C3453D_FK_WNWB_LEXICON_ID = Internal.createForeignKey(WnwbSenserelationtype.WNWB_SENSERELATIONTYPE, DSL.name("wnwb_senserelationtype_lexicon_id_82c3453d_fk_wnwb_lexicon_id"), new TableField[] { WnwbSenserelationtype.WNWB_SENSERELATIONTYPE.LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final ForeignKey<WnwbSensetagRecord, WnwbSenseRecord> WNWB_SENSETAG__WNWB_SENSETAG_SENSE_ID_F7FB7B9D_FK_WNWB_SENSE_ID = Internal.createForeignKey(WnwbSensetag.WNWB_SENSETAG, DSL.name("wnwb_sensetag_sense_id_f7fb7b9d_fk_wnwb_sense_id"), new TableField[] { WnwbSensetag.WNWB_SENSETAG.SENSE_ID }, Keys.WNWB_SENSE_PKEY, new TableField[] { WnwbSense.WNWB_SENSE.ID }, true);
    public static final ForeignKey<WnwbSensetagRecord, WnwbTagRecord> WNWB_SENSETAG__WNWB_SENSETAG_TAG_ID_FCED1B6A_FK_WNWB_TAG_ID = Internal.createForeignKey(WnwbSensetag.WNWB_SENSETAG, DSL.name("wnwb_sensetag_tag_id_fced1b6a_fk_wnwb_tag_id"), new TableField[] { WnwbSensetag.WNWB_SENSETAG.TAG_ID }, Keys.WNWB_TAG_PKEY, new TableField[] { WnwbTag.WNWB_TAG.ID }, true);
    public static final ForeignKey<WnwbStatementRecord, WnwbDefinitionRecord> WNWB_STATEMENT__WNWB_STATEMENT_DEFINITION_ID_C6356A08_FK_WNWB_DEFINITION_ID = Internal.createForeignKey(WnwbStatement.WNWB_STATEMENT, DSL.name("wnwb_statement_definition_id_c6356a08_fk_wnwb_definition_id"), new TableField[] { WnwbStatement.WNWB_STATEMENT.DEFINITION_ID }, Keys.WNWB_DEFINITION_PKEY, new TableField[] { WnwbDefinition.WNWB_DEFINITION.ID }, true);
    public static final ForeignKey<WnwbSynsetRecord, WnwbLexiconRecord> WNWB_SYNSET__WNWB_SYNSET_LEXICON_ID_2D4135F8_FK_WNWB_LEXICON_ID = Internal.createForeignKey(WnwbSynset.WNWB_SYNSET, DSL.name("wnwb_synset_lexicon_id_2d4135f8_fk_wnwb_lexicon_id"), new TableField[] { WnwbSynset.WNWB_SYNSET.LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final ForeignKey<WnwbSynsetrelationRecord, WnwbSynsetRecord> WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_A_SYNSET_ID_99F48C44_FK_WNWB_SYNSET_ID = Internal.createForeignKey(WnwbSynsetrelation.WNWB_SYNSETRELATION, DSL.name("wnwb_synsetrelation_a_synset_id_99f48c44_fk_wnwb_synset_id"), new TableField[] { WnwbSynsetrelation.WNWB_SYNSETRELATION.A_SYNSET_ID }, Keys.WNWB_SYNSET_PKEY, new TableField[] { WnwbSynset.WNWB_SYNSET.ID }, true);
    public static final ForeignKey<WnwbSynsetrelationRecord, WnwbSynsetRecord> WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_B_SYNSET_ID_C84D4349_FK_WNWB_SYNSET_ID = Internal.createForeignKey(WnwbSynsetrelation.WNWB_SYNSETRELATION, DSL.name("wnwb_synsetrelation_b_synset_id_c84d4349_fk_wnwb_synset_id"), new TableField[] { WnwbSynsetrelation.WNWB_SYNSETRELATION.B_SYNSET_ID }, Keys.WNWB_SYNSET_PKEY, new TableField[] { WnwbSynset.WNWB_SYNSET.ID }, true);
    public static final ForeignKey<WnwbSynsetrelationRecord, WnwbSynsetrelationtypeRecord> WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_REL_TYPE_ID_EB53DCEC_FK_WNWB_SYNS = Internal.createForeignKey(WnwbSynsetrelation.WNWB_SYNSETRELATION, DSL.name("wnwb_synsetrelation_rel_type_id_eb53dcec_fk_wnwb_syns"), new TableField[] { WnwbSynsetrelation.WNWB_SYNSETRELATION.REL_TYPE_ID }, Keys.WNWB_SYNSETRELATIONTYPE_PKEY, new TableField[] { WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE.ID }, true);
    public static final ForeignKey<WnwbSynsetrelationtypeRecord, WnwbLexiconRecord> WNWB_SYNSETRELATIONTYPE__WNWB_SYNSETRELATIONTYPE_LEXICON_ID_8F83F300_FK_WNWB_LEXICON_ID = Internal.createForeignKey(WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE, DSL.name("wnwb_synsetrelationtype_lexicon_id_8f83f300_fk_wnwb_lexicon_id"), new TableField[] { WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE.LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final ForeignKey<WnwbSynsettagRecord, WnwbSynsetRecord> WNWB_SYNSETTAG__WNWB_SYNSETTAG_SYNSET_ID_F74B55FF_FK_WNWB_SYNSET_ID = Internal.createForeignKey(WnwbSynsettag.WNWB_SYNSETTAG, DSL.name("wnwb_synsettag_synset_id_f74b55ff_fk_wnwb_synset_id"), new TableField[] { WnwbSynsettag.WNWB_SYNSETTAG.SYNSET_ID }, Keys.WNWB_SYNSET_PKEY, new TableField[] { WnwbSynset.WNWB_SYNSET.ID }, true);
    public static final ForeignKey<WnwbSynsettagRecord, WnwbTagRecord> WNWB_SYNSETTAG__WNWB_SYNSETTAG_TAG_ID_9A41102F_FK_WNWB_TAG_ID = Internal.createForeignKey(WnwbSynsettag.WNWB_SYNSETTAG, DSL.name("wnwb_synsettag_tag_id_9a41102f_fk_wnwb_tag_id"), new TableField[] { WnwbSynsettag.WNWB_SYNSETTAG.TAG_ID }, Keys.WNWB_TAG_PKEY, new TableField[] { WnwbTag.WNWB_TAG.ID }, true);
    public static final ForeignKey<WnwbTaskorderRecord, WnwbLexiconRecord> WNWB_TASKORDER__WNWB_TASKORDER_MAIN_LEXICON_ID_89633296_FK_WNWB_LEXICON_ID = Internal.createForeignKey(WnwbTaskorder.WNWB_TASKORDER, DSL.name("wnwb_taskorder_main_lexicon_id_89633296_fk_wnwb_lexicon_id"), new TableField[] { WnwbTaskorder.WNWB_TASKORDER.MAIN_LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
    public static final ForeignKey<WnwbTaskorderRecord, WnwbLexiconRecord> WNWB_TASKORDER__WNWB_TASKORDER_OTHER_LEXICON_ID_D5CBEAD2_FK_WNWB_LEXICON_ID = Internal.createForeignKey(WnwbTaskorder.WNWB_TASKORDER, DSL.name("wnwb_taskorder_other_lexicon_id_d5cbead2_fk_wnwb_lexicon_id"), new TableField[] { WnwbTaskorder.WNWB_TASKORDER.OTHER_LEXICON_ID }, Keys.WNWB_LEXICON_PKEY, new TableField[] { WnwbLexicon.WNWB_LEXICON.ID }, true);
}
