/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample;


import java.util.Arrays;
import java.util.List;

import nu.studer.sample.tables.WnwbDefinition;
import nu.studer.sample.tables.WnwbExternalref;
import nu.studer.sample.tables.WnwbExternalrelationtype;
import nu.studer.sample.tables.WnwbExternalsystem;
import nu.studer.sample.tables.WnwbLemmatag;
import nu.studer.sample.tables.WnwbLexicalentry;
import nu.studer.sample.tables.WnwbLexicalresource;
import nu.studer.sample.tables.WnwbLexicon;
import nu.studer.sample.tables.WnwbRefcode;
import nu.studer.sample.tables.WnwbSense;
import nu.studer.sample.tables.WnwbSenseexample;
import nu.studer.sample.tables.WnwbSenserelation;
import nu.studer.sample.tables.WnwbSenserelationtype;
import nu.studer.sample.tables.WnwbSensetag;
import nu.studer.sample.tables.WnwbStatement;
import nu.studer.sample.tables.WnwbSynset;
import nu.studer.sample.tables.WnwbSynsetrelation;
import nu.studer.sample.tables.WnwbSynsetrelationtype;
import nu.studer.sample.tables.WnwbSynsettag;
import nu.studer.sample.tables.WnwbTag;
import nu.studer.sample.tables.WnwbTaskorder;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.wnwb_definition</code>.
     */
    public final WnwbDefinition WNWB_DEFINITION = WnwbDefinition.WNWB_DEFINITION;

    /**
     * The table <code>public.wnwb_externalref</code>.
     */
    public final WnwbExternalref WNWB_EXTERNALREF = WnwbExternalref.WNWB_EXTERNALREF;

    /**
     * The table <code>public.wnwb_externalrelationtype</code>.
     */
    public final WnwbExternalrelationtype WNWB_EXTERNALRELATIONTYPE = WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE;

    /**
     * The table <code>public.wnwb_externalsystem</code>.
     */
    public final WnwbExternalsystem WNWB_EXTERNALSYSTEM = WnwbExternalsystem.WNWB_EXTERNALSYSTEM;

    /**
     * The table <code>public.wnwb_lemmatag</code>.
     */
    public final WnwbLemmatag WNWB_LEMMATAG = WnwbLemmatag.WNWB_LEMMATAG;

    /**
     * The table <code>public.wnwb_lexicalentry</code>.
     */
    public final WnwbLexicalentry WNWB_LEXICALENTRY = WnwbLexicalentry.WNWB_LEXICALENTRY;

    /**
     * The table <code>public.wnwb_lexicalresource</code>.
     */
    public final WnwbLexicalresource WNWB_LEXICALRESOURCE = WnwbLexicalresource.WNWB_LEXICALRESOURCE;

    /**
     * The table <code>public.wnwb_lexicon</code>.
     */
    public final WnwbLexicon WNWB_LEXICON = WnwbLexicon.WNWB_LEXICON;

    /**
     * The table <code>public.wnwb_refcode</code>.
     */
    public final WnwbRefcode WNWB_REFCODE = WnwbRefcode.WNWB_REFCODE;

    /**
     * The table <code>public.wnwb_sense</code>.
     */
    public final WnwbSense WNWB_SENSE = WnwbSense.WNWB_SENSE;

    /**
     * The table <code>public.wnwb_senseexample</code>.
     */
    public final WnwbSenseexample WNWB_SENSEEXAMPLE = WnwbSenseexample.WNWB_SENSEEXAMPLE;

    /**
     * The table <code>public.wnwb_senserelation</code>.
     */
    public final WnwbSenserelation WNWB_SENSERELATION = WnwbSenserelation.WNWB_SENSERELATION;

    /**
     * The table <code>public.wnwb_senserelationtype</code>.
     */
    public final WnwbSenserelationtype WNWB_SENSERELATIONTYPE = WnwbSenserelationtype.WNWB_SENSERELATIONTYPE;

    /**
     * The table <code>public.wnwb_sensetag</code>.
     */
    public final WnwbSensetag WNWB_SENSETAG = WnwbSensetag.WNWB_SENSETAG;

    /**
     * The table <code>public.wnwb_statement</code>.
     */
    public final WnwbStatement WNWB_STATEMENT = WnwbStatement.WNWB_STATEMENT;

    /**
     * The table <code>public.wnwb_synset</code>.
     */
    public final WnwbSynset WNWB_SYNSET = WnwbSynset.WNWB_SYNSET;

    /**
     * The table <code>public.wnwb_synsetrelation</code>.
     */
    public final WnwbSynsetrelation WNWB_SYNSETRELATION = WnwbSynsetrelation.WNWB_SYNSETRELATION;

    /**
     * The table <code>public.wnwb_synsetrelationtype</code>.
     */
    public final WnwbSynsetrelationtype WNWB_SYNSETRELATIONTYPE = WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE;

    /**
     * The table <code>public.wnwb_synsettag</code>.
     */
    public final WnwbSynsettag WNWB_SYNSETTAG = WnwbSynsettag.WNWB_SYNSETTAG;

    /**
     * The table <code>public.wnwb_tag</code>.
     */
    public final WnwbTag WNWB_TAG = WnwbTag.WNWB_TAG;

    /**
     * The table <code>public.wnwb_taskorder</code>.
     */
    public final WnwbTaskorder WNWB_TASKORDER = WnwbTaskorder.WNWB_TASKORDER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            WnwbDefinition.WNWB_DEFINITION,
            WnwbExternalref.WNWB_EXTERNALREF,
            WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE,
            WnwbExternalsystem.WNWB_EXTERNALSYSTEM,
            WnwbLemmatag.WNWB_LEMMATAG,
            WnwbLexicalentry.WNWB_LEXICALENTRY,
            WnwbLexicalresource.WNWB_LEXICALRESOURCE,
            WnwbLexicon.WNWB_LEXICON,
            WnwbRefcode.WNWB_REFCODE,
            WnwbSense.WNWB_SENSE,
            WnwbSenseexample.WNWB_SENSEEXAMPLE,
            WnwbSenserelation.WNWB_SENSERELATION,
            WnwbSenserelationtype.WNWB_SENSERELATIONTYPE,
            WnwbSensetag.WNWB_SENSETAG,
            WnwbStatement.WNWB_STATEMENT,
            WnwbSynset.WNWB_SYNSET,
            WnwbSynsetrelation.WNWB_SYNSETRELATION,
            WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE,
            WnwbSynsettag.WNWB_SYNSETTAG,
            WnwbTag.WNWB_TAG,
            WnwbTaskorder.WNWB_TASKORDER
        );
    }
}
