/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample;


import nu.studer.sample.tables.WnwbDefinition;
import nu.studer.sample.tables.WnwbExternalref;
import nu.studer.sample.tables.WnwbExternalrelationtype;
import nu.studer.sample.tables.WnwbExternalsystem;
import nu.studer.sample.tables.WnwbLemmatag;
import nu.studer.sample.tables.WnwbLexicalentry;
import nu.studer.sample.tables.WnwbLexicalresource;
import nu.studer.sample.tables.WnwbLexicon;
import nu.studer.sample.tables.WnwbRefcode;
import nu.studer.sample.tables.WnwbSense;
import nu.studer.sample.tables.WnwbSenseexample;
import nu.studer.sample.tables.WnwbSenserelation;
import nu.studer.sample.tables.WnwbSenserelationtype;
import nu.studer.sample.tables.WnwbSensetag;
import nu.studer.sample.tables.WnwbStatement;
import nu.studer.sample.tables.WnwbSynset;
import nu.studer.sample.tables.WnwbSynsetrelation;
import nu.studer.sample.tables.WnwbSynsetrelationtype;
import nu.studer.sample.tables.WnwbSynsettag;
import nu.studer.sample.tables.WnwbTag;
import nu.studer.sample.tables.WnwbTaskorder;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.wnwb_definition</code>.
     */
    public static final WnwbDefinition WNWB_DEFINITION = WnwbDefinition.WNWB_DEFINITION;

    /**
     * The table <code>public.wnwb_externalref</code>.
     */
    public static final WnwbExternalref WNWB_EXTERNALREF = WnwbExternalref.WNWB_EXTERNALREF;

    /**
     * The table <code>public.wnwb_externalrelationtype</code>.
     */
    public static final WnwbExternalrelationtype WNWB_EXTERNALRELATIONTYPE = WnwbExternalrelationtype.WNWB_EXTERNALRELATIONTYPE;

    /**
     * The table <code>public.wnwb_externalsystem</code>.
     */
    public static final WnwbExternalsystem WNWB_EXTERNALSYSTEM = WnwbExternalsystem.WNWB_EXTERNALSYSTEM;

    /**
     * The table <code>public.wnwb_lemmatag</code>.
     */
    public static final WnwbLemmatag WNWB_LEMMATAG = WnwbLemmatag.WNWB_LEMMATAG;

    /**
     * The table <code>public.wnwb_lexicalentry</code>.
     */
    public static final WnwbLexicalentry WNWB_LEXICALENTRY = WnwbLexicalentry.WNWB_LEXICALENTRY;

    /**
     * The table <code>public.wnwb_lexicalresource</code>.
     */
    public static final WnwbLexicalresource WNWB_LEXICALRESOURCE = WnwbLexicalresource.WNWB_LEXICALRESOURCE;

    /**
     * The table <code>public.wnwb_lexicon</code>.
     */
    public static final WnwbLexicon WNWB_LEXICON = WnwbLexicon.WNWB_LEXICON;

    /**
     * The table <code>public.wnwb_refcode</code>.
     */
    public static final WnwbRefcode WNWB_REFCODE = WnwbRefcode.WNWB_REFCODE;

    /**
     * The table <code>public.wnwb_sense</code>.
     */
    public static final WnwbSense WNWB_SENSE = WnwbSense.WNWB_SENSE;

    /**
     * The table <code>public.wnwb_senseexample</code>.
     */
    public static final WnwbSenseexample WNWB_SENSEEXAMPLE = WnwbSenseexample.WNWB_SENSEEXAMPLE;

    /**
     * The table <code>public.wnwb_senserelation</code>.
     */
    public static final WnwbSenserelation WNWB_SENSERELATION = WnwbSenserelation.WNWB_SENSERELATION;

    /**
     * The table <code>public.wnwb_senserelationtype</code>.
     */
    public static final WnwbSenserelationtype WNWB_SENSERELATIONTYPE = WnwbSenserelationtype.WNWB_SENSERELATIONTYPE;

    /**
     * The table <code>public.wnwb_sensetag</code>.
     */
    public static final WnwbSensetag WNWB_SENSETAG = WnwbSensetag.WNWB_SENSETAG;

    /**
     * The table <code>public.wnwb_statement</code>.
     */
    public static final WnwbStatement WNWB_STATEMENT = WnwbStatement.WNWB_STATEMENT;

    /**
     * The table <code>public.wnwb_synset</code>.
     */
    public static final WnwbSynset WNWB_SYNSET = WnwbSynset.WNWB_SYNSET;

    /**
     * The table <code>public.wnwb_synsetrelation</code>.
     */
    public static final WnwbSynsetrelation WNWB_SYNSETRELATION = WnwbSynsetrelation.WNWB_SYNSETRELATION;

    /**
     * The table <code>public.wnwb_synsetrelationtype</code>.
     */
    public static final WnwbSynsetrelationtype WNWB_SYNSETRELATIONTYPE = WnwbSynsetrelationtype.WNWB_SYNSETRELATIONTYPE;

    /**
     * The table <code>public.wnwb_synsettag</code>.
     */
    public static final WnwbSynsettag WNWB_SYNSETTAG = WnwbSynsettag.WNWB_SYNSETTAG;

    /**
     * The table <code>public.wnwb_tag</code>.
     */
    public static final WnwbTag WNWB_TAG = WnwbTag.WNWB_TAG;

    /**
     * The table <code>public.wnwb_taskorder</code>.
     */
    public static final WnwbTaskorder WNWB_TASKORDER = WnwbTaskorder.WNWB_TASKORDER;
}
