/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbExternalref implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String reference;
    private final String status;
    private final Integer senseId;
    private final Integer synsetId;
    private final Integer sysIdId;
    private final Integer relTypeId;
    private final Double rate;
    private final String dcSource;
    private final String dcType;
    private final String note;

    public WnwbExternalref(WnwbExternalref value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.reference = value.reference;
        this.status = value.status;
        this.senseId = value.senseId;
        this.synsetId = value.synsetId;
        this.sysIdId = value.sysIdId;
        this.relTypeId = value.relTypeId;
        this.rate = value.rate;
        this.dcSource = value.dcSource;
        this.dcType = value.dcType;
        this.note = value.note;
    }

    public WnwbExternalref(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String reference,
        String status,
        Integer senseId,
        Integer synsetId,
        Integer sysIdId,
        Integer relTypeId,
        Double rate,
        String dcSource,
        String dcType,
        String note
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.reference = reference;
        this.status = status;
        this.senseId = senseId;
        this.synsetId = synsetId;
        this.sysIdId = sysIdId;
        this.relTypeId = relTypeId;
        this.rate = rate;
        this.dcSource = dcSource;
        this.dcType = dcType;
        this.note = note;
    }

    /**
     * Getter for <code>public.wnwb_externalref.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_externalref.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_externalref.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_externalref.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_externalref.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_externalref.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_externalref.reference</code>.
     */
    public String getReference() {
        return this.reference;
    }

    /**
     * Getter for <code>public.wnwb_externalref.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.wnwb_externalref.sense_id</code>.
     */
    public Integer getSenseId() {
        return this.senseId;
    }

    /**
     * Getter for <code>public.wnwb_externalref.synset_id</code>.
     */
    public Integer getSynsetId() {
        return this.synsetId;
    }

    /**
     * Getter for <code>public.wnwb_externalref.sys_id_id</code>.
     */
    public Integer getSysIdId() {
        return this.sysIdId;
    }

    /**
     * Getter for <code>public.wnwb_externalref.rel_type_id</code>.
     */
    public Integer getRelTypeId() {
        return this.relTypeId;
    }

    /**
     * Getter for <code>public.wnwb_externalref.rate</code>.
     */
    public Double getRate() {
        return this.rate;
    }

    /**
     * Getter for <code>public.wnwb_externalref.dc_source</code>.
     */
    public String getDcSource() {
        return this.dcSource;
    }

    /**
     * Getter for <code>public.wnwb_externalref.dc_type</code>.
     */
    public String getDcType() {
        return this.dcType;
    }

    /**
     * Getter for <code>public.wnwb_externalref.note</code>.
     */
    public String getNote() {
        return this.note;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbExternalref other = (WnwbExternalref) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.reference == null) {
            if (other.reference != null)
                return false;
        }
        else if (!this.reference.equals(other.reference))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.senseId == null) {
            if (other.senseId != null)
                return false;
        }
        else if (!this.senseId.equals(other.senseId))
            return false;
        if (this.synsetId == null) {
            if (other.synsetId != null)
                return false;
        }
        else if (!this.synsetId.equals(other.synsetId))
            return false;
        if (this.sysIdId == null) {
            if (other.sysIdId != null)
                return false;
        }
        else if (!this.sysIdId.equals(other.sysIdId))
            return false;
        if (this.relTypeId == null) {
            if (other.relTypeId != null)
                return false;
        }
        else if (!this.relTypeId.equals(other.relTypeId))
            return false;
        if (this.rate == null) {
            if (other.rate != null)
                return false;
        }
        else if (!this.rate.equals(other.rate))
            return false;
        if (this.dcSource == null) {
            if (other.dcSource != null)
                return false;
        }
        else if (!this.dcSource.equals(other.dcSource))
            return false;
        if (this.dcType == null) {
            if (other.dcType != null)
                return false;
        }
        else if (!this.dcType.equals(other.dcType))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.reference == null) ? 0 : this.reference.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.senseId == null) ? 0 : this.senseId.hashCode());
        result = prime * result + ((this.synsetId == null) ? 0 : this.synsetId.hashCode());
        result = prime * result + ((this.sysIdId == null) ? 0 : this.sysIdId.hashCode());
        result = prime * result + ((this.relTypeId == null) ? 0 : this.relTypeId.hashCode());
        result = prime * result + ((this.rate == null) ? 0 : this.rate.hashCode());
        result = prime * result + ((this.dcSource == null) ? 0 : this.dcSource.hashCode());
        result = prime * result + ((this.dcType == null) ? 0 : this.dcType.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbExternalref (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(reference);
        sb.append(", ").append(status);
        sb.append(", ").append(senseId);
        sb.append(", ").append(synsetId);
        sb.append(", ").append(sysIdId);
        sb.append(", ").append(relTypeId);
        sb.append(", ").append(rate);
        sb.append(", ").append(dcSource);
        sb.append(", ").append(dcType);
        sb.append(", ").append(note);

        sb.append(")");
        return sb.toString();
    }
}
