/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSense implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final Integer nr;
    private final String label;
    private final String style;
    private final String status;
    private final String comment;
    private final String lockedBy;
    private final OffsetDateTime dateLocked;
    private final Integer lexicalEntryId;
    private final Integer synsetId;
    private final String dcSource;

    public WnwbSense(WnwbSense value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.nr = value.nr;
        this.label = value.label;
        this.style = value.style;
        this.status = value.status;
        this.comment = value.comment;
        this.lockedBy = value.lockedBy;
        this.dateLocked = value.dateLocked;
        this.lexicalEntryId = value.lexicalEntryId;
        this.synsetId = value.synsetId;
        this.dcSource = value.dcSource;
    }

    public WnwbSense(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        Integer nr,
        String label,
        String style,
        String status,
        String comment,
        String lockedBy,
        OffsetDateTime dateLocked,
        Integer lexicalEntryId,
        Integer synsetId,
        String dcSource
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.nr = nr;
        this.label = label;
        this.style = style;
        this.status = status;
        this.comment = comment;
        this.lockedBy = lockedBy;
        this.dateLocked = dateLocked;
        this.lexicalEntryId = lexicalEntryId;
        this.synsetId = synsetId;
        this.dcSource = dcSource;
    }

    /**
     * Getter for <code>public.wnwb_sense.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_sense.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_sense.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_sense.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_sense.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_sense.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_sense.nr</code>.
     */
    public Integer getNr() {
        return this.nr;
    }

    /**
     * Getter for <code>public.wnwb_sense.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Getter for <code>public.wnwb_sense.style</code>.
     */
    public String getStyle() {
        return this.style;
    }

    /**
     * Getter for <code>public.wnwb_sense.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.wnwb_sense.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Getter for <code>public.wnwb_sense.locked_by</code>.
     */
    public String getLockedBy() {
        return this.lockedBy;
    }

    /**
     * Getter for <code>public.wnwb_sense.date_locked</code>.
     */
    public OffsetDateTime getDateLocked() {
        return this.dateLocked;
    }

    /**
     * Getter for <code>public.wnwb_sense.lexical_entry_id</code>.
     */
    public Integer getLexicalEntryId() {
        return this.lexicalEntryId;
    }

    /**
     * Getter for <code>public.wnwb_sense.synset_id</code>.
     */
    public Integer getSynsetId() {
        return this.synsetId;
    }

    /**
     * Getter for <code>public.wnwb_sense.dc_source</code>.
     */
    public String getDcSource() {
        return this.dcSource;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbSense other = (WnwbSense) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.nr == null) {
            if (other.nr != null)
                return false;
        }
        else if (!this.nr.equals(other.nr))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        if (this.style == null) {
            if (other.style != null)
                return false;
        }
        else if (!this.style.equals(other.style))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!this.comment.equals(other.comment))
            return false;
        if (this.lockedBy == null) {
            if (other.lockedBy != null)
                return false;
        }
        else if (!this.lockedBy.equals(other.lockedBy))
            return false;
        if (this.dateLocked == null) {
            if (other.dateLocked != null)
                return false;
        }
        else if (!this.dateLocked.equals(other.dateLocked))
            return false;
        if (this.lexicalEntryId == null) {
            if (other.lexicalEntryId != null)
                return false;
        }
        else if (!this.lexicalEntryId.equals(other.lexicalEntryId))
            return false;
        if (this.synsetId == null) {
            if (other.synsetId != null)
                return false;
        }
        else if (!this.synsetId.equals(other.synsetId))
            return false;
        if (this.dcSource == null) {
            if (other.dcSource != null)
                return false;
        }
        else if (!this.dcSource.equals(other.dcSource))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.nr == null) ? 0 : this.nr.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        result = prime * result + ((this.style == null) ? 0 : this.style.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.lockedBy == null) ? 0 : this.lockedBy.hashCode());
        result = prime * result + ((this.dateLocked == null) ? 0 : this.dateLocked.hashCode());
        result = prime * result + ((this.lexicalEntryId == null) ? 0 : this.lexicalEntryId.hashCode());
        result = prime * result + ((this.synsetId == null) ? 0 : this.synsetId.hashCode());
        result = prime * result + ((this.dcSource == null) ? 0 : this.dcSource.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbSense (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(nr);
        sb.append(", ").append(label);
        sb.append(", ").append(style);
        sb.append(", ").append(status);
        sb.append(", ").append(comment);
        sb.append(", ").append(lockedBy);
        sb.append(", ").append(dateLocked);
        sb.append(", ").append(lexicalEntryId);
        sb.append(", ").append(synsetId);
        sb.append(", ").append(dcSource);

        sb.append(")");
        return sb.toString();
    }
}
