/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbTaskorder implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String resources;
    private final String params;
    private final String status;
    private final String progress;
    private final Integer mainLexiconId;
    private final Integer otherLexiconId;

    public WnwbTaskorder(WnwbTaskorder value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.resources = value.resources;
        this.params = value.params;
        this.status = value.status;
        this.progress = value.progress;
        this.mainLexiconId = value.mainLexiconId;
        this.otherLexiconId = value.otherLexiconId;
    }

    public WnwbTaskorder(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String resources,
        String params,
        String status,
        String progress,
        Integer mainLexiconId,
        Integer otherLexiconId
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.resources = resources;
        this.params = params;
        this.status = status;
        this.progress = progress;
        this.mainLexiconId = mainLexiconId;
        this.otherLexiconId = otherLexiconId;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.resources</code>.
     */
    public String getResources() {
        return this.resources;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.params</code>.
     */
    public String getParams() {
        return this.params;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.progress</code>.
     */
    public String getProgress() {
        return this.progress;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.main_lexicon_id</code>.
     */
    public Integer getMainLexiconId() {
        return this.mainLexiconId;
    }

    /**
     * Getter for <code>public.wnwb_taskorder.other_lexicon_id</code>.
     */
    public Integer getOtherLexiconId() {
        return this.otherLexiconId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbTaskorder other = (WnwbTaskorder) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.resources == null) {
            if (other.resources != null)
                return false;
        }
        else if (!this.resources.equals(other.resources))
            return false;
        if (this.params == null) {
            if (other.params != null)
                return false;
        }
        else if (!this.params.equals(other.params))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.progress == null) {
            if (other.progress != null)
                return false;
        }
        else if (!this.progress.equals(other.progress))
            return false;
        if (this.mainLexiconId == null) {
            if (other.mainLexiconId != null)
                return false;
        }
        else if (!this.mainLexiconId.equals(other.mainLexiconId))
            return false;
        if (this.otherLexiconId == null) {
            if (other.otherLexiconId != null)
                return false;
        }
        else if (!this.otherLexiconId.equals(other.otherLexiconId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.resources == null) ? 0 : this.resources.hashCode());
        result = prime * result + ((this.params == null) ? 0 : this.params.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.progress == null) ? 0 : this.progress.hashCode());
        result = prime * result + ((this.mainLexiconId == null) ? 0 : this.mainLexiconId.hashCode());
        result = prime * result + ((this.otherLexiconId == null) ? 0 : this.otherLexiconId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbTaskorder (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(resources);
        sb.append(", ").append(params);
        sb.append(", ").append(status);
        sb.append(", ").append(progress);
        sb.append(", ").append(mainLexiconId);
        sb.append(", ").append(otherLexiconId);

        sb.append(")");
        return sb.toString();
    }
}
