/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLexicalentry implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String partOfSpeech;
    private final String scheme;
    private final String lemma;
    private final String distinctiveCase;
    private final String distinctiveForm;
    private final String grammaticalNumber;
    private final String grammaticalGender;
    private final Integer lexiconId;
    private final String dcSource;
    private final String note;

    public WnwbLexicalentry(WnwbLexicalentry value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.partOfSpeech = value.partOfSpeech;
        this.scheme = value.scheme;
        this.lemma = value.lemma;
        this.distinctiveCase = value.distinctiveCase;
        this.distinctiveForm = value.distinctiveForm;
        this.grammaticalNumber = value.grammaticalNumber;
        this.grammaticalGender = value.grammaticalGender;
        this.lexiconId = value.lexiconId;
        this.dcSource = value.dcSource;
        this.note = value.note;
    }

    public WnwbLexicalentry(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String partOfSpeech,
        String scheme,
        String lemma,
        String distinctiveCase,
        String distinctiveForm,
        String grammaticalNumber,
        String grammaticalGender,
        Integer lexiconId,
        String dcSource,
        String note
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.partOfSpeech = partOfSpeech;
        this.scheme = scheme;
        this.lemma = lemma;
        this.distinctiveCase = distinctiveCase;
        this.distinctiveForm = distinctiveForm;
        this.grammaticalNumber = grammaticalNumber;
        this.grammaticalGender = grammaticalGender;
        this.lexiconId = lexiconId;
        this.dcSource = dcSource;
        this.note = note;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.part_of_speech</code>.
     */
    public String getPartOfSpeech() {
        return this.partOfSpeech;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.scheme</code>.
     */
    public String getScheme() {
        return this.scheme;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.lemma</code>.
     */
    public String getLemma() {
        return this.lemma;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.distinctive_case</code>.
     */
    public String getDistinctiveCase() {
        return this.distinctiveCase;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.distinctive_form</code>.
     */
    public String getDistinctiveForm() {
        return this.distinctiveForm;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.grammatical_number</code>.
     */
    public String getGrammaticalNumber() {
        return this.grammaticalNumber;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.grammatical_gender</code>.
     */
    public String getGrammaticalGender() {
        return this.grammaticalGender;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.lexicon_id</code>.
     */
    public Integer getLexiconId() {
        return this.lexiconId;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.dc_source</code>.
     */
    public String getDcSource() {
        return this.dcSource;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.note</code>.
     */
    public String getNote() {
        return this.note;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbLexicalentry other = (WnwbLexicalentry) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.partOfSpeech == null) {
            if (other.partOfSpeech != null)
                return false;
        }
        else if (!this.partOfSpeech.equals(other.partOfSpeech))
            return false;
        if (this.scheme == null) {
            if (other.scheme != null)
                return false;
        }
        else if (!this.scheme.equals(other.scheme))
            return false;
        if (this.lemma == null) {
            if (other.lemma != null)
                return false;
        }
        else if (!this.lemma.equals(other.lemma))
            return false;
        if (this.distinctiveCase == null) {
            if (other.distinctiveCase != null)
                return false;
        }
        else if (!this.distinctiveCase.equals(other.distinctiveCase))
            return false;
        if (this.distinctiveForm == null) {
            if (other.distinctiveForm != null)
                return false;
        }
        else if (!this.distinctiveForm.equals(other.distinctiveForm))
            return false;
        if (this.grammaticalNumber == null) {
            if (other.grammaticalNumber != null)
                return false;
        }
        else if (!this.grammaticalNumber.equals(other.grammaticalNumber))
            return false;
        if (this.grammaticalGender == null) {
            if (other.grammaticalGender != null)
                return false;
        }
        else if (!this.grammaticalGender.equals(other.grammaticalGender))
            return false;
        if (this.lexiconId == null) {
            if (other.lexiconId != null)
                return false;
        }
        else if (!this.lexiconId.equals(other.lexiconId))
            return false;
        if (this.dcSource == null) {
            if (other.dcSource != null)
                return false;
        }
        else if (!this.dcSource.equals(other.dcSource))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.partOfSpeech == null) ? 0 : this.partOfSpeech.hashCode());
        result = prime * result + ((this.scheme == null) ? 0 : this.scheme.hashCode());
        result = prime * result + ((this.lemma == null) ? 0 : this.lemma.hashCode());
        result = prime * result + ((this.distinctiveCase == null) ? 0 : this.distinctiveCase.hashCode());
        result = prime * result + ((this.distinctiveForm == null) ? 0 : this.distinctiveForm.hashCode());
        result = prime * result + ((this.grammaticalNumber == null) ? 0 : this.grammaticalNumber.hashCode());
        result = prime * result + ((this.grammaticalGender == null) ? 0 : this.grammaticalGender.hashCode());
        result = prime * result + ((this.lexiconId == null) ? 0 : this.lexiconId.hashCode());
        result = prime * result + ((this.dcSource == null) ? 0 : this.dcSource.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbLexicalentry (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(partOfSpeech);
        sb.append(", ").append(scheme);
        sb.append(", ").append(lemma);
        sb.append(", ").append(distinctiveCase);
        sb.append(", ").append(distinctiveForm);
        sb.append(", ").append(grammaticalNumber);
        sb.append(", ").append(grammaticalGender);
        sb.append(", ").append(lexiconId);
        sb.append(", ").append(dcSource);
        sb.append(", ").append(note);

        sb.append(")");
        return sb.toString();
    }
}
