/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbExternalrelationtype implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String name;
    private final String description;
    private final Integer lexiconId;
    private final String dcSource;
    private final String note;
    private final Integer priority;

    public WnwbExternalrelationtype(WnwbExternalrelationtype value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.name = value.name;
        this.description = value.description;
        this.lexiconId = value.lexiconId;
        this.dcSource = value.dcSource;
        this.note = value.note;
        this.priority = value.priority;
    }

    public WnwbExternalrelationtype(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String name,
        String description,
        Integer lexiconId,
        String dcSource,
        String note,
        Integer priority
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.name = name;
        this.description = description;
        this.lexiconId = lexiconId;
        this.dcSource = dcSource;
        this.note = note;
        this.priority = priority;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.lexicon_id</code>.
     */
    public Integer getLexiconId() {
        return this.lexiconId;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.dc_source</code>.
     */
    public String getDcSource() {
        return this.dcSource;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.note</code>.
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Getter for <code>public.wnwb_externalrelationtype.priority</code>.
     */
    public Integer getPriority() {
        return this.priority;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbExternalrelationtype other = (WnwbExternalrelationtype) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.lexiconId == null) {
            if (other.lexiconId != null)
                return false;
        }
        else if (!this.lexiconId.equals(other.lexiconId))
            return false;
        if (this.dcSource == null) {
            if (other.dcSource != null)
                return false;
        }
        else if (!this.dcSource.equals(other.dcSource))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        if (this.priority == null) {
            if (other.priority != null)
                return false;
        }
        else if (!this.priority.equals(other.priority))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.lexiconId == null) ? 0 : this.lexiconId.hashCode());
        result = prime * result + ((this.dcSource == null) ? 0 : this.dcSource.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        result = prime * result + ((this.priority == null) ? 0 : this.priority.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbExternalrelationtype (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(lexiconId);
        sb.append(", ").append(dcSource);
        sb.append(", ").append(note);
        sb.append(", ").append(priority);

        sb.append(")");
        return sb.toString();
    }
}
