/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLexicon implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String language;
    private final String version;
    private final String status;
    private final Integer resourceId;
    private final String citation;
    private final String dcCoverage;
    private final String dcPublisher;
    private final String dcRights;
    private final String dcSource;
    private final String email;
    private final String license;
    private final String note;
    private final String url;
    private final Integer synsetcount;

    public WnwbLexicon(WnwbLexicon value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.language = value.language;
        this.version = value.version;
        this.status = value.status;
        this.resourceId = value.resourceId;
        this.citation = value.citation;
        this.dcCoverage = value.dcCoverage;
        this.dcPublisher = value.dcPublisher;
        this.dcRights = value.dcRights;
        this.dcSource = value.dcSource;
        this.email = value.email;
        this.license = value.license;
        this.note = value.note;
        this.url = value.url;
        this.synsetcount = value.synsetcount;
    }

    public WnwbLexicon(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String language,
        String version,
        String status,
        Integer resourceId,
        String citation,
        String dcCoverage,
        String dcPublisher,
        String dcRights,
        String dcSource,
        String email,
        String license,
        String note,
        String url,
        Integer synsetcount
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.language = language;
        this.version = version;
        this.status = status;
        this.resourceId = resourceId;
        this.citation = citation;
        this.dcCoverage = dcCoverage;
        this.dcPublisher = dcPublisher;
        this.dcRights = dcRights;
        this.dcSource = dcSource;
        this.email = email;
        this.license = license;
        this.note = note;
        this.url = url;
        this.synsetcount = synsetcount;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.language</code>.
     */
    public String getLanguage() {
        return this.language;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.version</code>.
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.resource_id</code>.
     */
    public Integer getResourceId() {
        return this.resourceId;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.citation</code>.
     */
    public String getCitation() {
        return this.citation;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_coverage</code>.
     */
    public String getDcCoverage() {
        return this.dcCoverage;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_publisher</code>.
     */
    public String getDcPublisher() {
        return this.dcPublisher;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_rights</code>.
     */
    public String getDcRights() {
        return this.dcRights;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_source</code>.
     */
    public String getDcSource() {
        return this.dcSource;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.license</code>.
     */
    public String getLicense() {
        return this.license;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.note</code>.
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.url</code>.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.synsetcount</code>.
     */
    public Integer getSynsetcount() {
        return this.synsetcount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbLexicon other = (WnwbLexicon) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.language == null) {
            if (other.language != null)
                return false;
        }
        else if (!this.language.equals(other.language))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.resourceId == null) {
            if (other.resourceId != null)
                return false;
        }
        else if (!this.resourceId.equals(other.resourceId))
            return false;
        if (this.citation == null) {
            if (other.citation != null)
                return false;
        }
        else if (!this.citation.equals(other.citation))
            return false;
        if (this.dcCoverage == null) {
            if (other.dcCoverage != null)
                return false;
        }
        else if (!this.dcCoverage.equals(other.dcCoverage))
            return false;
        if (this.dcPublisher == null) {
            if (other.dcPublisher != null)
                return false;
        }
        else if (!this.dcPublisher.equals(other.dcPublisher))
            return false;
        if (this.dcRights == null) {
            if (other.dcRights != null)
                return false;
        }
        else if (!this.dcRights.equals(other.dcRights))
            return false;
        if (this.dcSource == null) {
            if (other.dcSource != null)
                return false;
        }
        else if (!this.dcSource.equals(other.dcSource))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.license == null) {
            if (other.license != null)
                return false;
        }
        else if (!this.license.equals(other.license))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.synsetcount == null) {
            if (other.synsetcount != null)
                return false;
        }
        else if (!this.synsetcount.equals(other.synsetcount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.resourceId == null) ? 0 : this.resourceId.hashCode());
        result = prime * result + ((this.citation == null) ? 0 : this.citation.hashCode());
        result = prime * result + ((this.dcCoverage == null) ? 0 : this.dcCoverage.hashCode());
        result = prime * result + ((this.dcPublisher == null) ? 0 : this.dcPublisher.hashCode());
        result = prime * result + ((this.dcRights == null) ? 0 : this.dcRights.hashCode());
        result = prime * result + ((this.dcSource == null) ? 0 : this.dcSource.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.license == null) ? 0 : this.license.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.synsetcount == null) ? 0 : this.synsetcount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbLexicon (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(language);
        sb.append(", ").append(version);
        sb.append(", ").append(status);
        sb.append(", ").append(resourceId);
        sb.append(", ").append(citation);
        sb.append(", ").append(dcCoverage);
        sb.append(", ").append(dcPublisher);
        sb.append(", ").append(dcRights);
        sb.append(", ").append(dcSource);
        sb.append(", ").append(email);
        sb.append(", ").append(license);
        sb.append(", ").append(note);
        sb.append(", ").append(url);
        sb.append(", ").append(synsetcount);

        sb.append(")");
        return sb.toString();
    }
}
