/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String category;
    private final String value;

    public WnwbTag(WnwbTag value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.category = value.category;
        this.value = value.value;
    }

    public WnwbTag(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String category,
        String value
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.category = category;
        this.value = value;
    }

    /**
     * Getter for <code>public.wnwb_tag.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_tag.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_tag.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_tag.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_tag.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_tag.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_tag.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Getter for <code>public.wnwb_tag.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbTag other = (WnwbTag) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbTag (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(category);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
