/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLexicalresource implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String name;
    private final String languageCoding;
    private final String scriptCoding;
    private final String charCoding;
    private final String short_;

    public WnwbLexicalresource(WnwbLexicalresource value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.name = value.name;
        this.languageCoding = value.languageCoding;
        this.scriptCoding = value.scriptCoding;
        this.charCoding = value.charCoding;
        this.short_ = value.short_;
    }

    public WnwbLexicalresource(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String name,
        String languageCoding,
        String scriptCoding,
        String charCoding,
        String short_
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.name = name;
        this.languageCoding = languageCoding;
        this.scriptCoding = scriptCoding;
        this.charCoding = charCoding;
        this.short_ = short_;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.language_coding</code>.
     */
    public String getLanguageCoding() {
        return this.languageCoding;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.script_coding</code>.
     */
    public String getScriptCoding() {
        return this.scriptCoding;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.char_coding</code>.
     */
    public String getCharCoding() {
        return this.charCoding;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.short</code>.
     */
    public String getShort() {
        return this.short_;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbLexicalresource other = (WnwbLexicalresource) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.languageCoding == null) {
            if (other.languageCoding != null)
                return false;
        }
        else if (!this.languageCoding.equals(other.languageCoding))
            return false;
        if (this.scriptCoding == null) {
            if (other.scriptCoding != null)
                return false;
        }
        else if (!this.scriptCoding.equals(other.scriptCoding))
            return false;
        if (this.charCoding == null) {
            if (other.charCoding != null)
                return false;
        }
        else if (!this.charCoding.equals(other.charCoding))
            return false;
        if (this.short_ == null) {
            if (other.short_ != null)
                return false;
        }
        else if (!this.short_.equals(other.short_))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.languageCoding == null) ? 0 : this.languageCoding.hashCode());
        result = prime * result + ((this.scriptCoding == null) ? 0 : this.scriptCoding.hashCode());
        result = prime * result + ((this.charCoding == null) ? 0 : this.charCoding.hashCode());
        result = prime * result + ((this.short_ == null) ? 0 : this.short_.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbLexicalresource (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(name);
        sb.append(", ").append(languageCoding);
        sb.append(", ").append(scriptCoding);
        sb.append(", ").append(charCoding);
        sb.append(", ").append(short_);

        sb.append(")");
        return sb.toString();
    }
}
