/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSynset implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String createdBy;
    private final OffsetDateTime dateCreated;
    private final String updatedBy;
    private final OffsetDateTime dateUpdated;
    private final Boolean isDeleted;
    private final String label;
    private final String synsetType;
    private final String status;
    private final String comment;
    private final String lockedBy;
    private final OffsetDateTime dateLocked;
    private final Integer lexiconId;

    public WnwbSynset(WnwbSynset value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.dateCreated = value.dateCreated;
        this.updatedBy = value.updatedBy;
        this.dateUpdated = value.dateUpdated;
        this.isDeleted = value.isDeleted;
        this.label = value.label;
        this.synsetType = value.synsetType;
        this.status = value.status;
        this.comment = value.comment;
        this.lockedBy = value.lockedBy;
        this.dateLocked = value.dateLocked;
        this.lexiconId = value.lexiconId;
    }

    public WnwbSynset(
        Integer id,
        String createdBy,
        OffsetDateTime dateCreated,
        String updatedBy,
        OffsetDateTime dateUpdated,
        Boolean isDeleted,
        String label,
        String synsetType,
        String status,
        String comment,
        String lockedBy,
        OffsetDateTime dateLocked,
        Integer lexiconId
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.isDeleted = isDeleted;
        this.label = label;
        this.synsetType = synsetType;
        this.status = status;
        this.comment = comment;
        this.lockedBy = lockedBy;
        this.dateLocked = dateLocked;
        this.lexiconId = lexiconId;
    }

    /**
     * Getter for <code>public.wnwb_synset.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.wnwb_synset.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.wnwb_synset.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>public.wnwb_synset.updated_by</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Getter for <code>public.wnwb_synset.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return this.dateUpdated;
    }

    /**
     * Getter for <code>public.wnwb_synset.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Getter for <code>public.wnwb_synset.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Getter for <code>public.wnwb_synset.synset_type</code>.
     */
    public String getSynsetType() {
        return this.synsetType;
    }

    /**
     * Getter for <code>public.wnwb_synset.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.wnwb_synset.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Getter for <code>public.wnwb_synset.locked_by</code>.
     */
    public String getLockedBy() {
        return this.lockedBy;
    }

    /**
     * Getter for <code>public.wnwb_synset.date_locked</code>.
     */
    public OffsetDateTime getDateLocked() {
        return this.dateLocked;
    }

    /**
     * Getter for <code>public.wnwb_synset.lexicon_id</code>.
     */
    public Integer getLexiconId() {
        return this.lexiconId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WnwbSynset other = (WnwbSynset) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.dateUpdated == null) {
            if (other.dateUpdated != null)
                return false;
        }
        else if (!this.dateUpdated.equals(other.dateUpdated))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        if (this.synsetType == null) {
            if (other.synsetType != null)
                return false;
        }
        else if (!this.synsetType.equals(other.synsetType))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!this.comment.equals(other.comment))
            return false;
        if (this.lockedBy == null) {
            if (other.lockedBy != null)
                return false;
        }
        else if (!this.lockedBy.equals(other.lockedBy))
            return false;
        if (this.dateLocked == null) {
            if (other.dateLocked != null)
                return false;
        }
        else if (!this.dateLocked.equals(other.dateLocked))
            return false;
        if (this.lexiconId == null) {
            if (other.lexiconId != null)
                return false;
        }
        else if (!this.lexiconId.equals(other.lexiconId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.dateUpdated == null) ? 0 : this.dateUpdated.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        result = prime * result + ((this.synsetType == null) ? 0 : this.synsetType.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.lockedBy == null) ? 0 : this.lockedBy.hashCode());
        result = prime * result + ((this.dateLocked == null) ? 0 : this.dateLocked.hashCode());
        result = prime * result + ((this.lexiconId == null) ? 0 : this.lexiconId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WnwbSynset (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(dateUpdated);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(label);
        sb.append(", ").append(synsetType);
        sb.append(", ").append(status);
        sb.append(", ").append(comment);
        sb.append(", ").append(lockedBy);
        sb.append(", ").append(dateLocked);
        sb.append(", ").append(lexiconId);

        sb.append(")");
        return sb.toString();
    }
}
