/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbLexicon;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLexiconRecord extends UpdatableRecordImpl<WnwbLexiconRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_lexicon.id</code>.
     */
    public WnwbLexiconRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.created_by</code>.
     */
    public WnwbLexiconRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.date_created</code>.
     */
    public WnwbLexiconRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.updated_by</code>.
     */
    public WnwbLexiconRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.date_updated</code>.
     */
    public WnwbLexiconRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.is_deleted</code>.
     */
    public WnwbLexiconRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.language</code>.
     */
    public WnwbLexiconRecord setLanguage(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.language</code>.
     */
    public String getLanguage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.version</code>.
     */
    public WnwbLexiconRecord setVersion(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.version</code>.
     */
    public String getVersion() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.status</code>.
     */
    public WnwbLexiconRecord setStatus(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.resource_id</code>.
     */
    public WnwbLexiconRecord setResourceId(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.resource_id</code>.
     */
    public Integer getResourceId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.citation</code>.
     */
    public WnwbLexiconRecord setCitation(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.citation</code>.
     */
    public String getCitation() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.dc_coverage</code>.
     */
    public WnwbLexiconRecord setDcCoverage(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_coverage</code>.
     */
    public String getDcCoverage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.dc_publisher</code>.
     */
    public WnwbLexiconRecord setDcPublisher(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_publisher</code>.
     */
    public String getDcPublisher() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.dc_rights</code>.
     */
    public WnwbLexiconRecord setDcRights(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_rights</code>.
     */
    public String getDcRights() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.dc_source</code>.
     */
    public WnwbLexiconRecord setDcSource(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.dc_source</code>.
     */
    public String getDcSource() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.email</code>.
     */
    public WnwbLexiconRecord setEmail(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.email</code>.
     */
    public String getEmail() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.license</code>.
     */
    public WnwbLexiconRecord setLicense(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.license</code>.
     */
    public String getLicense() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.note</code>.
     */
    public WnwbLexiconRecord setNote(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.note</code>.
     */
    public String getNote() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.url</code>.
     */
    public WnwbLexiconRecord setUrl(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.url</code>.
     */
    public String getUrl() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.wnwb_lexicon.synsetcount</code>.
     */
    public WnwbLexiconRecord setSynsetcount(Integer value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicon.synsetcount</code>.
     */
    public Integer getSynsetcount() {
        return (Integer) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbLexiconRecord
     */
    public WnwbLexiconRecord() {
        super(WnwbLexicon.WNWB_LEXICON);
    }

    /**
     * Create a detached, initialised WnwbLexiconRecord
     */
    public WnwbLexiconRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String language, String version, String status, Integer resourceId, String citation, String dcCoverage, String dcPublisher, String dcRights, String dcSource, String email, String license, String note, String url, Integer synsetcount) {
        super(WnwbLexicon.WNWB_LEXICON);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setLanguage(language);
        setVersion(version);
        setStatus(status);
        setResourceId(resourceId);
        setCitation(citation);
        setDcCoverage(dcCoverage);
        setDcPublisher(dcPublisher);
        setDcRights(dcRights);
        setDcSource(dcSource);
        setEmail(email);
        setLicense(license);
        setNote(note);
        setUrl(url);
        setSynsetcount(synsetcount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbLexiconRecord
     */
    public WnwbLexiconRecord(nu.studer.sample.tables.pojos.WnwbLexicon value) {
        super(WnwbLexicon.WNWB_LEXICON);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setLanguage(value.getLanguage());
            setVersion(value.getVersion());
            setStatus(value.getStatus());
            setResourceId(value.getResourceId());
            setCitation(value.getCitation());
            setDcCoverage(value.getDcCoverage());
            setDcPublisher(value.getDcPublisher());
            setDcRights(value.getDcRights());
            setDcSource(value.getDcSource());
            setEmail(value.getEmail());
            setLicense(value.getLicense());
            setNote(value.getNote());
            setUrl(value.getUrl());
            setSynsetcount(value.getSynsetcount());
            resetChangedOnNotNull();
        }
    }
}
