/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbExternalsystem;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbExternalsystemRecord extends UpdatableRecordImpl<WnwbExternalsystemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_externalsystem.id</code>.
     */
    public WnwbExternalsystemRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.created_by</code>.
     */
    public WnwbExternalsystemRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.date_created</code>.
     */
    public WnwbExternalsystemRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.updated_by</code>.
     */
    public WnwbExternalsystemRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.date_updated</code>.
     */
    public WnwbExternalsystemRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.is_deleted</code>.
     */
    public WnwbExternalsystemRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.name</code>.
     */
    public WnwbExternalsystemRecord setName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.name</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.description</code>.
     */
    public WnwbExternalsystemRecord setDescription(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.url_pattern</code>.
     */
    public WnwbExternalsystemRecord setUrlPattern(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.url_pattern</code>.
     */
    public String getUrlPattern() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.reference_pattern</code>.
     */
    public WnwbExternalsystemRecord setReferencePattern(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.reference_pattern</code>.
     */
    public String getReferencePattern() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.local_lexicon_id</code>.
     */
    public WnwbExternalsystemRecord setLocalLexiconId(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.local_lexicon_id</code>.
     */
    public Integer getLocalLexiconId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.dc_source</code>.
     */
    public WnwbExternalsystemRecord setDcSource(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.dc_source</code>.
     */
    public String getDcSource() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.wnwb_externalsystem.note</code>.
     */
    public WnwbExternalsystemRecord setNote(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalsystem.note</code>.
     */
    public String getNote() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbExternalsystemRecord
     */
    public WnwbExternalsystemRecord() {
        super(WnwbExternalsystem.WNWB_EXTERNALSYSTEM);
    }

    /**
     * Create a detached, initialised WnwbExternalsystemRecord
     */
    public WnwbExternalsystemRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String name, String description, String urlPattern, String referencePattern, Integer localLexiconId, String dcSource, String note) {
        super(WnwbExternalsystem.WNWB_EXTERNALSYSTEM);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setName(name);
        setDescription(description);
        setUrlPattern(urlPattern);
        setReferencePattern(referencePattern);
        setLocalLexiconId(localLexiconId);
        setDcSource(dcSource);
        setNote(note);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbExternalsystemRecord
     */
    public WnwbExternalsystemRecord(nu.studer.sample.tables.pojos.WnwbExternalsystem value) {
        super(WnwbExternalsystem.WNWB_EXTERNALSYSTEM);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setName(value.getName());
            setDescription(value.getDescription());
            setUrlPattern(value.getUrlPattern());
            setReferencePattern(value.getReferencePattern());
            setLocalLexiconId(value.getLocalLexiconId());
            setDcSource(value.getDcSource());
            setNote(value.getNote());
            resetChangedOnNotNull();
        }
    }
}
