/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbLemmatag;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLemmatagRecord extends UpdatableRecordImpl<WnwbLemmatagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_lemmatag.id</code>.
     */
    public WnwbLemmatagRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_lemmatag.created_by</code>.
     */
    public WnwbLemmatagRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_lemmatag.date_created</code>.
     */
    public WnwbLemmatagRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_lemmatag.updated_by</code>.
     */
    public WnwbLemmatagRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_lemmatag.date_updated</code>.
     */
    public WnwbLemmatagRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_lemmatag.is_deleted</code>.
     */
    public WnwbLemmatagRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_lemmatag.lexical_entry_id</code>.
     */
    public WnwbLemmatagRecord setLexicalEntryId(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.lexical_entry_id</code>.
     */
    public Integer getLexicalEntryId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.wnwb_lemmatag.tag_id</code>.
     */
    public WnwbLemmatagRecord setTagId(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lemmatag.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbLemmatagRecord
     */
    public WnwbLemmatagRecord() {
        super(WnwbLemmatag.WNWB_LEMMATAG);
    }

    /**
     * Create a detached, initialised WnwbLemmatagRecord
     */
    public WnwbLemmatagRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, Integer lexicalEntryId, Integer tagId) {
        super(WnwbLemmatag.WNWB_LEMMATAG);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setLexicalEntryId(lexicalEntryId);
        setTagId(tagId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbLemmatagRecord
     */
    public WnwbLemmatagRecord(nu.studer.sample.tables.pojos.WnwbLemmatag value) {
        super(WnwbLemmatag.WNWB_LEMMATAG);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setLexicalEntryId(value.getLexicalEntryId());
            setTagId(value.getTagId());
            resetChangedOnNotNull();
        }
    }
}
