/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbRefcode;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbRefcodeRecord extends UpdatableRecordImpl<WnwbRefcodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_refcode.id</code>.
     */
    public WnwbRefcodeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_refcode.created_by</code>.
     */
    public WnwbRefcodeRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_refcode.date_created</code>.
     */
    public WnwbRefcodeRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_refcode.updated_by</code>.
     */
    public WnwbRefcodeRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_refcode.date_updated</code>.
     */
    public WnwbRefcodeRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_refcode.is_deleted</code>.
     */
    public WnwbRefcodeRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_refcode.domain</code>.
     */
    public WnwbRefcodeRecord setDomain(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.domain</code>.
     */
    public String getDomain() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_refcode.code</code>.
     */
    public WnwbRefcodeRecord setCode(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.code</code>.
     */
    public String getCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_refcode.value</code>.
     */
    public WnwbRefcodeRecord setValue(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.value</code>.
     */
    public String getValue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_refcode.language</code>.
     */
    public WnwbRefcodeRecord setLanguage(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_refcode.language</code>.
     */
    public String getLanguage() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbRefcodeRecord
     */
    public WnwbRefcodeRecord() {
        super(WnwbRefcode.WNWB_REFCODE);
    }

    /**
     * Create a detached, initialised WnwbRefcodeRecord
     */
    public WnwbRefcodeRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String domain, String code, String value, String language) {
        super(WnwbRefcode.WNWB_REFCODE);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setDomain(domain);
        setCode(code);
        setValue(value);
        setLanguage(language);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbRefcodeRecord
     */
    public WnwbRefcodeRecord(nu.studer.sample.tables.pojos.WnwbRefcode value) {
        super(WnwbRefcode.WNWB_REFCODE);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setDomain(value.getDomain());
            setCode(value.getCode());
            setValue(value.getValue());
            setLanguage(value.getLanguage());
            resetChangedOnNotNull();
        }
    }
}
