/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbSense;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSenseRecord extends UpdatableRecordImpl<WnwbSenseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_sense.id</code>.
     */
    public WnwbSenseRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_sense.created_by</code>.
     */
    public WnwbSenseRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_sense.date_created</code>.
     */
    public WnwbSenseRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_sense.updated_by</code>.
     */
    public WnwbSenseRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_sense.date_updated</code>.
     */
    public WnwbSenseRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_sense.is_deleted</code>.
     */
    public WnwbSenseRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_sense.nr</code>.
     */
    public WnwbSenseRecord setNr(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.nr</code>.
     */
    public Integer getNr() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.wnwb_sense.label</code>.
     */
    public WnwbSenseRecord setLabel(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.label</code>.
     */
    public String getLabel() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_sense.style</code>.
     */
    public WnwbSenseRecord setStyle(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.style</code>.
     */
    public String getStyle() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_sense.status</code>.
     */
    public WnwbSenseRecord setStatus(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.wnwb_sense.comment</code>.
     */
    public WnwbSenseRecord setComment(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.comment</code>.
     */
    public String getComment() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.wnwb_sense.locked_by</code>.
     */
    public WnwbSenseRecord setLockedBy(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.locked_by</code>.
     */
    public String getLockedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.wnwb_sense.date_locked</code>.
     */
    public WnwbSenseRecord setDateLocked(OffsetDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.date_locked</code>.
     */
    public OffsetDateTime getDateLocked() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.wnwb_sense.lexical_entry_id</code>.
     */
    public WnwbSenseRecord setLexicalEntryId(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.lexical_entry_id</code>.
     */
    public Integer getLexicalEntryId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.wnwb_sense.synset_id</code>.
     */
    public WnwbSenseRecord setSynsetId(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.synset_id</code>.
     */
    public Integer getSynsetId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.wnwb_sense.dc_source</code>.
     */
    public WnwbSenseRecord setDcSource(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_sense.dc_source</code>.
     */
    public String getDcSource() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbSenseRecord
     */
    public WnwbSenseRecord() {
        super(WnwbSense.WNWB_SENSE);
    }

    /**
     * Create a detached, initialised WnwbSenseRecord
     */
    public WnwbSenseRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, Integer nr, String label, String style, String status, String comment, String lockedBy, OffsetDateTime dateLocked, Integer lexicalEntryId, Integer synsetId, String dcSource) {
        super(WnwbSense.WNWB_SENSE);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setNr(nr);
        setLabel(label);
        setStyle(style);
        setStatus(status);
        setComment(comment);
        setLockedBy(lockedBy);
        setDateLocked(dateLocked);
        setLexicalEntryId(lexicalEntryId);
        setSynsetId(synsetId);
        setDcSource(dcSource);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbSenseRecord
     */
    public WnwbSenseRecord(nu.studer.sample.tables.pojos.WnwbSense value) {
        super(WnwbSense.WNWB_SENSE);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setNr(value.getNr());
            setLabel(value.getLabel());
            setStyle(value.getStyle());
            setStatus(value.getStatus());
            setComment(value.getComment());
            setLockedBy(value.getLockedBy());
            setDateLocked(value.getDateLocked());
            setLexicalEntryId(value.getLexicalEntryId());
            setSynsetId(value.getSynsetId());
            setDcSource(value.getDcSource());
            resetChangedOnNotNull();
        }
    }
}
