/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbSynset;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSynsetRecord extends UpdatableRecordImpl<WnwbSynsetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_synset.id</code>.
     */
    public WnwbSynsetRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_synset.created_by</code>.
     */
    public WnwbSynsetRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_synset.date_created</code>.
     */
    public WnwbSynsetRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_synset.updated_by</code>.
     */
    public WnwbSynsetRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_synset.date_updated</code>.
     */
    public WnwbSynsetRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_synset.is_deleted</code>.
     */
    public WnwbSynsetRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_synset.label</code>.
     */
    public WnwbSynsetRecord setLabel(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.label</code>.
     */
    public String getLabel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_synset.synset_type</code>.
     */
    public WnwbSynsetRecord setSynsetType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.synset_type</code>.
     */
    public String getSynsetType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_synset.status</code>.
     */
    public WnwbSynsetRecord setStatus(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_synset.comment</code>.
     */
    public WnwbSynsetRecord setComment(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.comment</code>.
     */
    public String getComment() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.wnwb_synset.locked_by</code>.
     */
    public WnwbSynsetRecord setLockedBy(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.locked_by</code>.
     */
    public String getLockedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.wnwb_synset.date_locked</code>.
     */
    public WnwbSynsetRecord setDateLocked(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.date_locked</code>.
     */
    public OffsetDateTime getDateLocked() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.wnwb_synset.lexicon_id</code>.
     */
    public WnwbSynsetRecord setLexiconId(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synset.lexicon_id</code>.
     */
    public Integer getLexiconId() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbSynsetRecord
     */
    public WnwbSynsetRecord() {
        super(WnwbSynset.WNWB_SYNSET);
    }

    /**
     * Create a detached, initialised WnwbSynsetRecord
     */
    public WnwbSynsetRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String label, String synsetType, String status, String comment, String lockedBy, OffsetDateTime dateLocked, Integer lexiconId) {
        super(WnwbSynset.WNWB_SYNSET);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setLabel(label);
        setSynsetType(synsetType);
        setStatus(status);
        setComment(comment);
        setLockedBy(lockedBy);
        setDateLocked(dateLocked);
        setLexiconId(lexiconId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbSynsetRecord
     */
    public WnwbSynsetRecord(nu.studer.sample.tables.pojos.WnwbSynset value) {
        super(WnwbSynset.WNWB_SYNSET);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setLabel(value.getLabel());
            setSynsetType(value.getSynsetType());
            setStatus(value.getStatus());
            setComment(value.getComment());
            setLockedBy(value.getLockedBy());
            setDateLocked(value.getDateLocked());
            setLexiconId(value.getLexiconId());
            resetChangedOnNotNull();
        }
    }
}
