/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbSenseexample;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSenseexampleRecord extends UpdatableRecordImpl<WnwbSenseexampleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_senseexample.id</code>.
     */
    public WnwbSenseexampleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.created_by</code>.
     */
    public WnwbSenseexampleRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.date_created</code>.
     */
    public WnwbSenseexampleRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.updated_by</code>.
     */
    public WnwbSenseexampleRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.date_updated</code>.
     */
    public WnwbSenseexampleRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.is_deleted</code>.
     */
    public WnwbSenseexampleRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.text</code>.
     */
    public WnwbSenseexampleRecord setText(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.text</code>.
     */
    public String getText() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.source</code>.
     */
    public WnwbSenseexampleRecord setSource(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.source</code>.
     */
    public String getSource() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.language</code>.
     */
    public WnwbSenseexampleRecord setLanguage(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.language</code>.
     */
    public String getLanguage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.is_primary</code>.
     */
    public WnwbSenseexampleRecord setIsPrimary(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.wnwb_senseexample.sense_id</code>.
     */
    public WnwbSenseexampleRecord setSenseId(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_senseexample.sense_id</code>.
     */
    public Integer getSenseId() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbSenseexampleRecord
     */
    public WnwbSenseexampleRecord() {
        super(WnwbSenseexample.WNWB_SENSEEXAMPLE);
    }

    /**
     * Create a detached, initialised WnwbSenseexampleRecord
     */
    public WnwbSenseexampleRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String text, String source, String language, Boolean isPrimary, Integer senseId) {
        super(WnwbSenseexample.WNWB_SENSEEXAMPLE);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setText(text);
        setSource(source);
        setLanguage(language);
        setIsPrimary(isPrimary);
        setSenseId(senseId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbSenseexampleRecord
     */
    public WnwbSenseexampleRecord(nu.studer.sample.tables.pojos.WnwbSenseexample value) {
        super(WnwbSenseexample.WNWB_SENSEEXAMPLE);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setText(value.getText());
            setSource(value.getSource());
            setLanguage(value.getLanguage());
            setIsPrimary(value.getIsPrimary());
            setSenseId(value.getSenseId());
            resetChangedOnNotNull();
        }
    }
}
