/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbSynsettag;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSynsettagRecord extends UpdatableRecordImpl<WnwbSynsettagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_synsettag.id</code>.
     */
    public WnwbSynsettagRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_synsettag.created_by</code>.
     */
    public WnwbSynsettagRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_synsettag.date_created</code>.
     */
    public WnwbSynsettagRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_synsettag.updated_by</code>.
     */
    public WnwbSynsettagRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_synsettag.date_updated</code>.
     */
    public WnwbSynsettagRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_synsettag.is_deleted</code>.
     */
    public WnwbSynsettagRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_synsettag.synset_id</code>.
     */
    public WnwbSynsettagRecord setSynsetId(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.synset_id</code>.
     */
    public Integer getSynsetId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.wnwb_synsettag.tag_id</code>.
     */
    public WnwbSynsettagRecord setTagId(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsettag.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbSynsettagRecord
     */
    public WnwbSynsettagRecord() {
        super(WnwbSynsettag.WNWB_SYNSETTAG);
    }

    /**
     * Create a detached, initialised WnwbSynsettagRecord
     */
    public WnwbSynsettagRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, Integer synsetId, Integer tagId) {
        super(WnwbSynsettag.WNWB_SYNSETTAG);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setSynsetId(synsetId);
        setTagId(tagId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbSynsettagRecord
     */
    public WnwbSynsettagRecord(nu.studer.sample.tables.pojos.WnwbSynsettag value) {
        super(WnwbSynsettag.WNWB_SYNSETTAG);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setSynsetId(value.getSynsetId());
            setTagId(value.getTagId());
            resetChangedOnNotNull();
        }
    }
}
