/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbSynsetrelation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSynsetrelationRecord extends UpdatableRecordImpl<WnwbSynsetrelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_synsetrelation.id</code>.
     */
    public WnwbSynsetrelationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.created_by</code>.
     */
    public WnwbSynsetrelationRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.date_created</code>.
     */
    public WnwbSynsetrelationRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.updated_by</code>.
     */
    public WnwbSynsetrelationRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.date_updated</code>.
     */
    public WnwbSynsetrelationRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.is_deleted</code>.
     */
    public WnwbSynsetrelationRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.label</code>.
     */
    public WnwbSynsetrelationRecord setLabel(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.label</code>.
     */
    public String getLabel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.status</code>.
     */
    public WnwbSynsetrelationRecord setStatus(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.a_synset_id</code>.
     */
    public WnwbSynsetrelationRecord setASynsetId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.a_synset_id</code>.
     */
    public Integer getASynsetId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.b_synset_id</code>.
     */
    public WnwbSynsetrelationRecord setBSynsetId(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.b_synset_id</code>.
     */
    public Integer getBSynsetId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.rel_type_id</code>.
     */
    public WnwbSynsetrelationRecord setRelTypeId(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.rel_type_id</code>.
     */
    public Integer getRelTypeId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.dc_source</code>.
     */
    public WnwbSynsetrelationRecord setDcSource(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.dc_source</code>.
     */
    public String getDcSource() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.dc_type</code>.
     */
    public WnwbSynsetrelationRecord setDcType(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.dc_type</code>.
     */
    public String getDcType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.note</code>.
     */
    public WnwbSynsetrelationRecord setNote(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.note</code>.
     */
    public String getNote() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.wnwb_synsetrelation.rate</code>.
     */
    public WnwbSynsetrelationRecord setRate(Double value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_synsetrelation.rate</code>.
     */
    public Double getRate() {
        return (Double) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbSynsetrelationRecord
     */
    public WnwbSynsetrelationRecord() {
        super(WnwbSynsetrelation.WNWB_SYNSETRELATION);
    }

    /**
     * Create a detached, initialised WnwbSynsetrelationRecord
     */
    public WnwbSynsetrelationRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String label, String status, Integer aSynsetId, Integer bSynsetId, Integer relTypeId, String dcSource, String dcType, String note, Double rate) {
        super(WnwbSynsetrelation.WNWB_SYNSETRELATION);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setLabel(label);
        setStatus(status);
        setASynsetId(aSynsetId);
        setBSynsetId(bSynsetId);
        setRelTypeId(relTypeId);
        setDcSource(dcSource);
        setDcType(dcType);
        setNote(note);
        setRate(rate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbSynsetrelationRecord
     */
    public WnwbSynsetrelationRecord(nu.studer.sample.tables.pojos.WnwbSynsetrelation value) {
        super(WnwbSynsetrelation.WNWB_SYNSETRELATION);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setLabel(value.getLabel());
            setStatus(value.getStatus());
            setASynsetId(value.getASynsetId());
            setBSynsetId(value.getBSynsetId());
            setRelTypeId(value.getRelTypeId());
            setDcSource(value.getDcSource());
            setDcType(value.getDcType());
            setNote(value.getNote());
            setRate(value.getRate());
            resetChangedOnNotNull();
        }
    }
}
