/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbStatement;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbStatementRecord extends UpdatableRecordImpl<WnwbStatementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_statement.id</code>.
     */
    public WnwbStatementRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_statement.created_by</code>.
     */
    public WnwbStatementRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_statement.date_created</code>.
     */
    public WnwbStatementRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_statement.updated_by</code>.
     */
    public WnwbStatementRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_statement.date_updated</code>.
     */
    public WnwbStatementRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_statement.is_deleted</code>.
     */
    public WnwbStatementRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_statement.text</code>.
     */
    public WnwbStatementRecord setText(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.text</code>.
     */
    public String getText() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_statement.source</code>.
     */
    public WnwbStatementRecord setSource(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.source</code>.
     */
    public String getSource() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_statement.language</code>.
     */
    public WnwbStatementRecord setLanguage(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.language</code>.
     */
    public String getLanguage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_statement.definition_id</code>.
     */
    public WnwbStatementRecord setDefinitionId(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_statement.definition_id</code>.
     */
    public Integer getDefinitionId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbStatementRecord
     */
    public WnwbStatementRecord() {
        super(WnwbStatement.WNWB_STATEMENT);
    }

    /**
     * Create a detached, initialised WnwbStatementRecord
     */
    public WnwbStatementRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String text, String source, String language, Integer definitionId) {
        super(WnwbStatement.WNWB_STATEMENT);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setText(text);
        setSource(source);
        setLanguage(language);
        setDefinitionId(definitionId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbStatementRecord
     */
    public WnwbStatementRecord(nu.studer.sample.tables.pojos.WnwbStatement value) {
        super(WnwbStatement.WNWB_STATEMENT);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setText(value.getText());
            setSource(value.getSource());
            setLanguage(value.getLanguage());
            setDefinitionId(value.getDefinitionId());
            resetChangedOnNotNull();
        }
    }
}
