/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbLexicalresource;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLexicalresourceRecord extends UpdatableRecordImpl<WnwbLexicalresourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_lexicalresource.id</code>.
     */
    public WnwbLexicalresourceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.created_by</code>.
     */
    public WnwbLexicalresourceRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.date_created</code>.
     */
    public WnwbLexicalresourceRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.updated_by</code>.
     */
    public WnwbLexicalresourceRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.date_updated</code>.
     */
    public WnwbLexicalresourceRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.is_deleted</code>.
     */
    public WnwbLexicalresourceRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.name</code>.
     */
    public WnwbLexicalresourceRecord setName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.name</code>.
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.language_coding</code>.
     */
    public WnwbLexicalresourceRecord setLanguageCoding(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.language_coding</code>.
     */
    public String getLanguageCoding() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.script_coding</code>.
     */
    public WnwbLexicalresourceRecord setScriptCoding(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.script_coding</code>.
     */
    public String getScriptCoding() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.char_coding</code>.
     */
    public WnwbLexicalresourceRecord setCharCoding(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.char_coding</code>.
     */
    public String getCharCoding() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.wnwb_lexicalresource.short</code>.
     */
    public WnwbLexicalresourceRecord setShort(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalresource.short</code>.
     */
    public String getShort() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbLexicalresourceRecord
     */
    public WnwbLexicalresourceRecord() {
        super(WnwbLexicalresource.WNWB_LEXICALRESOURCE);
    }

    /**
     * Create a detached, initialised WnwbLexicalresourceRecord
     */
    public WnwbLexicalresourceRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String name, String languageCoding, String scriptCoding, String charCoding, String short_) {
        super(WnwbLexicalresource.WNWB_LEXICALRESOURCE);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setName(name);
        setLanguageCoding(languageCoding);
        setScriptCoding(scriptCoding);
        setCharCoding(charCoding);
        setShort(short_);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbLexicalresourceRecord
     */
    public WnwbLexicalresourceRecord(nu.studer.sample.tables.pojos.WnwbLexicalresource value) {
        super(WnwbLexicalresource.WNWB_LEXICALRESOURCE);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setName(value.getName());
            setLanguageCoding(value.getLanguageCoding());
            setScriptCoding(value.getScriptCoding());
            setCharCoding(value.getCharCoding());
            setShort(value.getShort());
            resetChangedOnNotNull();
        }
    }
}
