/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbLexicalentry;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLexicalentryRecord extends UpdatableRecordImpl<WnwbLexicalentryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_lexicalentry.id</code>.
     */
    public WnwbLexicalentryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.created_by</code>.
     */
    public WnwbLexicalentryRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.date_created</code>.
     */
    public WnwbLexicalentryRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.updated_by</code>.
     */
    public WnwbLexicalentryRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.date_updated</code>.
     */
    public WnwbLexicalentryRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.is_deleted</code>.
     */
    public WnwbLexicalentryRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.part_of_speech</code>.
     */
    public WnwbLexicalentryRecord setPartOfSpeech(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.part_of_speech</code>.
     */
    public String getPartOfSpeech() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.scheme</code>.
     */
    public WnwbLexicalentryRecord setScheme(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.scheme</code>.
     */
    public String getScheme() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.lemma</code>.
     */
    public WnwbLexicalentryRecord setLemma(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.lemma</code>.
     */
    public String getLemma() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.distinctive_case</code>.
     */
    public WnwbLexicalentryRecord setDistinctiveCase(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.distinctive_case</code>.
     */
    public String getDistinctiveCase() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.distinctive_form</code>.
     */
    public WnwbLexicalentryRecord setDistinctiveForm(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.distinctive_form</code>.
     */
    public String getDistinctiveForm() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.grammatical_number</code>.
     */
    public WnwbLexicalentryRecord setGrammaticalNumber(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.grammatical_number</code>.
     */
    public String getGrammaticalNumber() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.grammatical_gender</code>.
     */
    public WnwbLexicalentryRecord setGrammaticalGender(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.grammatical_gender</code>.
     */
    public String getGrammaticalGender() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.lexicon_id</code>.
     */
    public WnwbLexicalentryRecord setLexiconId(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.lexicon_id</code>.
     */
    public Integer getLexiconId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.dc_source</code>.
     */
    public WnwbLexicalentryRecord setDcSource(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.dc_source</code>.
     */
    public String getDcSource() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.wnwb_lexicalentry.note</code>.
     */
    public WnwbLexicalentryRecord setNote(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_lexicalentry.note</code>.
     */
    public String getNote() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbLexicalentryRecord
     */
    public WnwbLexicalentryRecord() {
        super(WnwbLexicalentry.WNWB_LEXICALENTRY);
    }

    /**
     * Create a detached, initialised WnwbLexicalentryRecord
     */
    public WnwbLexicalentryRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String partOfSpeech, String scheme, String lemma, String distinctiveCase, String distinctiveForm, String grammaticalNumber, String grammaticalGender, Integer lexiconId, String dcSource, String note) {
        super(WnwbLexicalentry.WNWB_LEXICALENTRY);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setPartOfSpeech(partOfSpeech);
        setScheme(scheme);
        setLemma(lemma);
        setDistinctiveCase(distinctiveCase);
        setDistinctiveForm(distinctiveForm);
        setGrammaticalNumber(grammaticalNumber);
        setGrammaticalGender(grammaticalGender);
        setLexiconId(lexiconId);
        setDcSource(dcSource);
        setNote(note);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbLexicalentryRecord
     */
    public WnwbLexicalentryRecord(nu.studer.sample.tables.pojos.WnwbLexicalentry value) {
        super(WnwbLexicalentry.WNWB_LEXICALENTRY);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setPartOfSpeech(value.getPartOfSpeech());
            setScheme(value.getScheme());
            setLemma(value.getLemma());
            setDistinctiveCase(value.getDistinctiveCase());
            setDistinctiveForm(value.getDistinctiveForm());
            setGrammaticalNumber(value.getGrammaticalNumber());
            setGrammaticalGender(value.getGrammaticalGender());
            setLexiconId(value.getLexiconId());
            setDcSource(value.getDcSource());
            setNote(value.getNote());
            resetChangedOnNotNull();
        }
    }
}
