/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbTag;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbTagRecord extends UpdatableRecordImpl<WnwbTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_tag.id</code>.
     */
    public WnwbTagRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_tag.created_by</code>.
     */
    public WnwbTagRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_tag.date_created</code>.
     */
    public WnwbTagRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_tag.updated_by</code>.
     */
    public WnwbTagRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_tag.date_updated</code>.
     */
    public WnwbTagRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_tag.is_deleted</code>.
     */
    public WnwbTagRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_tag.category</code>.
     */
    public WnwbTagRecord setCategory(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.category</code>.
     */
    public String getCategory() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_tag.value</code>.
     */
    public WnwbTagRecord setValue(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_tag.value</code>.
     */
    public String getValue() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbTagRecord
     */
    public WnwbTagRecord() {
        super(WnwbTag.WNWB_TAG);
    }

    /**
     * Create a detached, initialised WnwbTagRecord
     */
    public WnwbTagRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String category, String value) {
        super(WnwbTag.WNWB_TAG);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setCategory(category);
        setValue(value);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbTagRecord
     */
    public WnwbTagRecord(nu.studer.sample.tables.pojos.WnwbTag value) {
        super(WnwbTag.WNWB_TAG);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setCategory(value.getCategory());
            setValue(value.getValue());
            resetChangedOnNotNull();
        }
    }
}
