/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbDefinition;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbDefinitionRecord extends UpdatableRecordImpl<WnwbDefinitionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_definition.id</code>.
     */
    public WnwbDefinitionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_definition.created_by</code>.
     */
    public WnwbDefinitionRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_definition.date_created</code>.
     */
    public WnwbDefinitionRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_definition.updated_by</code>.
     */
    public WnwbDefinitionRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_definition.date_updated</code>.
     */
    public WnwbDefinitionRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_definition.is_deleted</code>.
     */
    public WnwbDefinitionRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_definition.text</code>.
     */
    public WnwbDefinitionRecord setText(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.text</code>.
     */
    public String getText() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_definition.source</code>.
     */
    public WnwbDefinitionRecord setSource(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.source</code>.
     */
    public String getSource() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_definition.language</code>.
     */
    public WnwbDefinitionRecord setLanguage(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.language</code>.
     */
    public String getLanguage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.wnwb_definition.is_primary</code>.
     */
    public WnwbDefinitionRecord setIsPrimary(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.wnwb_definition.sense_id</code>.
     */
    public WnwbDefinitionRecord setSenseId(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.sense_id</code>.
     */
    public Integer getSenseId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.wnwb_definition.synset_id</code>.
     */
    public WnwbDefinitionRecord setSynsetId(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_definition.synset_id</code>.
     */
    public Integer getSynsetId() {
        return (Integer) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbDefinitionRecord
     */
    public WnwbDefinitionRecord() {
        super(WnwbDefinition.WNWB_DEFINITION);
    }

    /**
     * Create a detached, initialised WnwbDefinitionRecord
     */
    public WnwbDefinitionRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String text, String source, String language, Boolean isPrimary, Integer senseId, Integer synsetId) {
        super(WnwbDefinition.WNWB_DEFINITION);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setText(text);
        setSource(source);
        setLanguage(language);
        setIsPrimary(isPrimary);
        setSenseId(senseId);
        setSynsetId(synsetId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbDefinitionRecord
     */
    public WnwbDefinitionRecord(nu.studer.sample.tables.pojos.WnwbDefinition value) {
        super(WnwbDefinition.WNWB_DEFINITION);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setText(value.getText());
            setSource(value.getSource());
            setLanguage(value.getLanguage());
            setIsPrimary(value.getIsPrimary());
            setSenseId(value.getSenseId());
            setSynsetId(value.getSynsetId());
            resetChangedOnNotNull();
        }
    }
}
