/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import java.time.OffsetDateTime;

import nu.studer.sample.tables.WnwbExternalref;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbExternalrefRecord extends UpdatableRecordImpl<WnwbExternalrefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wnwb_externalref.id</code>.
     */
    public WnwbExternalrefRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.wnwb_externalref.created_by</code>.
     */
    public WnwbExternalrefRecord setCreatedBy(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.wnwb_externalref.date_created</code>.
     */
    public WnwbExternalrefRecord setDateCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.date_created</code>.
     */
    public OffsetDateTime getDateCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.wnwb_externalref.updated_by</code>.
     */
    public WnwbExternalrefRecord setUpdatedBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.wnwb_externalref.date_updated</code>.
     */
    public WnwbExternalrefRecord setDateUpdated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.date_updated</code>.
     */
    public OffsetDateTime getDateUpdated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.wnwb_externalref.is_deleted</code>.
     */
    public WnwbExternalrefRecord setIsDeleted(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.wnwb_externalref.reference</code>.
     */
    public WnwbExternalrefRecord setReference(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.reference</code>.
     */
    public String getReference() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.wnwb_externalref.status</code>.
     */
    public WnwbExternalrefRecord setStatus(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.wnwb_externalref.sense_id</code>.
     */
    public WnwbExternalrefRecord setSenseId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.sense_id</code>.
     */
    public Integer getSenseId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.wnwb_externalref.synset_id</code>.
     */
    public WnwbExternalrefRecord setSynsetId(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.synset_id</code>.
     */
    public Integer getSynsetId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.wnwb_externalref.sys_id_id</code>.
     */
    public WnwbExternalrefRecord setSysIdId(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.sys_id_id</code>.
     */
    public Integer getSysIdId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.wnwb_externalref.rel_type_id</code>.
     */
    public WnwbExternalrefRecord setRelTypeId(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.rel_type_id</code>.
     */
    public Integer getRelTypeId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.wnwb_externalref.rate</code>.
     */
    public WnwbExternalrefRecord setRate(Double value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.rate</code>.
     */
    public Double getRate() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.wnwb_externalref.dc_source</code>.
     */
    public WnwbExternalrefRecord setDcSource(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.dc_source</code>.
     */
    public String getDcSource() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.wnwb_externalref.dc_type</code>.
     */
    public WnwbExternalrefRecord setDcType(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.dc_type</code>.
     */
    public String getDcType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.wnwb_externalref.note</code>.
     */
    public WnwbExternalrefRecord setNote(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.wnwb_externalref.note</code>.
     */
    public String getNote() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WnwbExternalrefRecord
     */
    public WnwbExternalrefRecord() {
        super(WnwbExternalref.WNWB_EXTERNALREF);
    }

    /**
     * Create a detached, initialised WnwbExternalrefRecord
     */
    public WnwbExternalrefRecord(Integer id, String createdBy, OffsetDateTime dateCreated, String updatedBy, OffsetDateTime dateUpdated, Boolean isDeleted, String reference, String status, Integer senseId, Integer synsetId, Integer sysIdId, Integer relTypeId, Double rate, String dcSource, String dcType, String note) {
        super(WnwbExternalref.WNWB_EXTERNALREF);

        setId(id);
        setCreatedBy(createdBy);
        setDateCreated(dateCreated);
        setUpdatedBy(updatedBy);
        setDateUpdated(dateUpdated);
        setIsDeleted(isDeleted);
        setReference(reference);
        setStatus(status);
        setSenseId(senseId);
        setSynsetId(synsetId);
        setSysIdId(sysIdId);
        setRelTypeId(relTypeId);
        setRate(rate);
        setDcSource(dcSource);
        setDcType(dcType);
        setNote(note);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WnwbExternalrefRecord
     */
    public WnwbExternalrefRecord(nu.studer.sample.tables.pojos.WnwbExternalref value) {
        super(WnwbExternalref.WNWB_EXTERNALREF);

        if (value != null) {
            setId(value.getId());
            setCreatedBy(value.getCreatedBy());
            setDateCreated(value.getDateCreated());
            setUpdatedBy(value.getUpdatedBy());
            setDateUpdated(value.getDateUpdated());
            setIsDeleted(value.getIsDeleted());
            setReference(value.getReference());
            setStatus(value.getStatus());
            setSenseId(value.getSenseId());
            setSynsetId(value.getSynsetId());
            setSysIdId(value.getSysIdId());
            setRelTypeId(value.getRelTypeId());
            setRate(value.getRate());
            setDcSource(value.getDcSource());
            setDcType(value.getDcType());
            setNote(value.getNote());
            resetChangedOnNotNull();
        }
    }
}
