/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbSense.WnwbSensePath;
import nu.studer.sample.tables.WnwbTag.WnwbTagPath;
import nu.studer.sample.tables.records.WnwbSensetagRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSensetag extends TableImpl<WnwbSensetagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_sensetag</code>
     */
    public static final WnwbSensetag WNWB_SENSETAG = new WnwbSensetag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbSensetagRecord> getRecordType() {
        return WnwbSensetagRecord.class;
    }

    /**
     * The column <code>public.wnwb_sensetag.id</code>.
     */
    public final TableField<WnwbSensetagRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_sensetag.created_by</code>.
     */
    public final TableField<WnwbSensetagRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sensetag.date_created</code>.
     */
    public final TableField<WnwbSensetagRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sensetag.updated_by</code>.
     */
    public final TableField<WnwbSensetagRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_sensetag.date_updated</code>.
     */
    public final TableField<WnwbSensetagRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_sensetag.is_deleted</code>.
     */
    public final TableField<WnwbSensetagRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sensetag.sense_id</code>.
     */
    public final TableField<WnwbSensetagRecord, Integer> SENSE_ID = createField(DSL.name("sense_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sensetag.tag_id</code>.
     */
    public final TableField<WnwbSensetagRecord, Integer> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private WnwbSensetag(Name alias, Table<WnwbSensetagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbSensetag(Name alias, Table<WnwbSensetagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_sensetag</code> table reference
     */
    public WnwbSensetag(String alias) {
        this(DSL.name(alias), WNWB_SENSETAG);
    }

    /**
     * Create an aliased <code>public.wnwb_sensetag</code> table reference
     */
    public WnwbSensetag(Name alias) {
        this(alias, WNWB_SENSETAG);
    }

    /**
     * Create a <code>public.wnwb_sensetag</code> table reference
     */
    public WnwbSensetag() {
        this(DSL.name("wnwb_sensetag"), null);
    }

    public <O extends Record> WnwbSensetag(Table<O> path, ForeignKey<O, WnwbSensetagRecord> childPath, InverseForeignKey<O, WnwbSensetagRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_SENSETAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbSensetagPath extends WnwbSensetag implements Path<WnwbSensetagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbSensetagPath(Table<O> path, ForeignKey<O, WnwbSensetagRecord> childPath, InverseForeignKey<O, WnwbSensetagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbSensetagPath(Name alias, Table<WnwbSensetagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbSensetagPath as(String alias) {
            return new WnwbSensetagPath(DSL.name(alias), this);
        }

        @Override
        public WnwbSensetagPath as(Name alias) {
            return new WnwbSensetagPath(alias, this);
        }

        @Override
        public WnwbSensetagPath as(Table<?> alias) {
            return new WnwbSensetagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_SENSETAG_SENSE_ID_F7FB7B9D, Indexes.WNWB_SENSETAG_TAG_ID_FCED1B6A);
    }

    @Override
    public Identity<WnwbSensetagRecord, Integer> getIdentity() {
        return (Identity<WnwbSensetagRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbSensetagRecord> getPrimaryKey() {
        return Keys.WNWB_SENSETAG_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbSensetagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_SENSETAG__WNWB_SENSETAG_SENSE_ID_F7FB7B9D_FK_WNWB_SENSE_ID, Keys.WNWB_SENSETAG__WNWB_SENSETAG_TAG_ID_FCED1B6A_FK_WNWB_TAG_ID);
    }

    private transient WnwbSensePath _wnwbSense;

    /**
     * Get the implicit join path to the <code>public.wnwb_sense</code> table.
     */
    public WnwbSensePath wnwbSense() {
        if (_wnwbSense == null)
            _wnwbSense = new WnwbSensePath(this, Keys.WNWB_SENSETAG__WNWB_SENSETAG_SENSE_ID_F7FB7B9D_FK_WNWB_SENSE_ID, null);

        return _wnwbSense;
    }

    private transient WnwbTagPath _wnwbTag;

    /**
     * Get the implicit join path to the <code>public.wnwb_tag</code> table.
     */
    public WnwbTagPath wnwbTag() {
        if (_wnwbTag == null)
            _wnwbTag = new WnwbTagPath(this, Keys.WNWB_SENSETAG__WNWB_SENSETAG_TAG_ID_FCED1B6A_FK_WNWB_TAG_ID, null);

        return _wnwbTag;
    }

    @Override
    public WnwbSensetag as(String alias) {
        return new WnwbSensetag(DSL.name(alias), this);
    }

    @Override
    public WnwbSensetag as(Name alias) {
        return new WnwbSensetag(alias, this);
    }

    @Override
    public WnwbSensetag as(Table<?> alias) {
        return new WnwbSensetag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSensetag rename(String name) {
        return new WnwbSensetag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSensetag rename(Name name) {
        return new WnwbSensetag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSensetag rename(Table<?> name) {
        return new WnwbSensetag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSensetag where(Condition condition) {
        return new WnwbSensetag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSensetag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSensetag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSensetag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSensetag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSensetag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSensetag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSensetag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSensetag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSensetag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
