/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbSense.WnwbSensePath;
import nu.studer.sample.tables.records.WnwbSenseexampleRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSenseexample extends TableImpl<WnwbSenseexampleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_senseexample</code>
     */
    public static final WnwbSenseexample WNWB_SENSEEXAMPLE = new WnwbSenseexample();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbSenseexampleRecord> getRecordType() {
        return WnwbSenseexampleRecord.class;
    }

    /**
     * The column <code>public.wnwb_senseexample.id</code>.
     */
    public final TableField<WnwbSenseexampleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_senseexample.created_by</code>.
     */
    public final TableField<WnwbSenseexampleRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senseexample.date_created</code>.
     */
    public final TableField<WnwbSenseexampleRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senseexample.updated_by</code>.
     */
    public final TableField<WnwbSenseexampleRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_senseexample.date_updated</code>.
     */
    public final TableField<WnwbSenseexampleRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_senseexample.is_deleted</code>.
     */
    public final TableField<WnwbSenseexampleRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senseexample.text</code>.
     */
    public final TableField<WnwbSenseexampleRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senseexample.source</code>.
     */
    public final TableField<WnwbSenseexampleRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.wnwb_senseexample.language</code>.
     */
    public final TableField<WnwbSenseexampleRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senseexample.is_primary</code>.
     */
    public final TableField<WnwbSenseexampleRecord, Boolean> IS_PRIMARY = createField(DSL.name("is_primary"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senseexample.sense_id</code>.
     */
    public final TableField<WnwbSenseexampleRecord, Integer> SENSE_ID = createField(DSL.name("sense_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private WnwbSenseexample(Name alias, Table<WnwbSenseexampleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbSenseexample(Name alias, Table<WnwbSenseexampleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_senseexample</code> table reference
     */
    public WnwbSenseexample(String alias) {
        this(DSL.name(alias), WNWB_SENSEEXAMPLE);
    }

    /**
     * Create an aliased <code>public.wnwb_senseexample</code> table reference
     */
    public WnwbSenseexample(Name alias) {
        this(alias, WNWB_SENSEEXAMPLE);
    }

    /**
     * Create a <code>public.wnwb_senseexample</code> table reference
     */
    public WnwbSenseexample() {
        this(DSL.name("wnwb_senseexample"), null);
    }

    public <O extends Record> WnwbSenseexample(Table<O> path, ForeignKey<O, WnwbSenseexampleRecord> childPath, InverseForeignKey<O, WnwbSenseexampleRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_SENSEEXAMPLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbSenseexamplePath extends WnwbSenseexample implements Path<WnwbSenseexampleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbSenseexamplePath(Table<O> path, ForeignKey<O, WnwbSenseexampleRecord> childPath, InverseForeignKey<O, WnwbSenseexampleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbSenseexamplePath(Name alias, Table<WnwbSenseexampleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbSenseexamplePath as(String alias) {
            return new WnwbSenseexamplePath(DSL.name(alias), this);
        }

        @Override
        public WnwbSenseexamplePath as(Name alias) {
            return new WnwbSenseexamplePath(alias, this);
        }

        @Override
        public WnwbSenseexamplePath as(Table<?> alias) {
            return new WnwbSenseexamplePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_SENSEEXAMPLE_SENSE_ID_5B247889);
    }

    @Override
    public Identity<WnwbSenseexampleRecord, Integer> getIdentity() {
        return (Identity<WnwbSenseexampleRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbSenseexampleRecord> getPrimaryKey() {
        return Keys.WNWB_SENSEEXAMPLE_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbSenseexampleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_SENSEEXAMPLE__WNWB_SENSEEXAMPLE_SENSE_ID_5B247889_FK_WNWB_SENSE_ID);
    }

    private transient WnwbSensePath _wnwbSense;

    /**
     * Get the implicit join path to the <code>public.wnwb_sense</code> table.
     */
    public WnwbSensePath wnwbSense() {
        if (_wnwbSense == null)
            _wnwbSense = new WnwbSensePath(this, Keys.WNWB_SENSEEXAMPLE__WNWB_SENSEEXAMPLE_SENSE_ID_5B247889_FK_WNWB_SENSE_ID, null);

        return _wnwbSense;
    }

    @Override
    public WnwbSenseexample as(String alias) {
        return new WnwbSenseexample(DSL.name(alias), this);
    }

    @Override
    public WnwbSenseexample as(Name alias) {
        return new WnwbSenseexample(alias, this);
    }

    @Override
    public WnwbSenseexample as(Table<?> alias) {
        return new WnwbSenseexample(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenseexample rename(String name) {
        return new WnwbSenseexample(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenseexample rename(Name name) {
        return new WnwbSenseexample(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenseexample rename(Table<?> name) {
        return new WnwbSenseexample(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenseexample where(Condition condition) {
        return new WnwbSenseexample(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenseexample where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenseexample where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenseexample where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenseexample where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenseexample where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenseexample where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenseexample where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenseexample whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenseexample whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
