/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbLemmatag.WnwbLemmatagPath;
import nu.studer.sample.tables.WnwbSensetag.WnwbSensetagPath;
import nu.studer.sample.tables.WnwbSynsettag.WnwbSynsettagPath;
import nu.studer.sample.tables.records.WnwbTagRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbTag extends TableImpl<WnwbTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_tag</code>
     */
    public static final WnwbTag WNWB_TAG = new WnwbTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbTagRecord> getRecordType() {
        return WnwbTagRecord.class;
    }

    /**
     * The column <code>public.wnwb_tag.id</code>.
     */
    public final TableField<WnwbTagRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_tag.created_by</code>.
     */
    public final TableField<WnwbTagRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_tag.date_created</code>.
     */
    public final TableField<WnwbTagRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_tag.updated_by</code>.
     */
    public final TableField<WnwbTagRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_tag.date_updated</code>.
     */
    public final TableField<WnwbTagRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_tag.is_deleted</code>.
     */
    public final TableField<WnwbTagRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_tag.category</code>.
     */
    public final TableField<WnwbTagRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_tag.value</code>.
     */
    public final TableField<WnwbTagRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private WnwbTag(Name alias, Table<WnwbTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbTag(Name alias, Table<WnwbTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_tag</code> table reference
     */
    public WnwbTag(String alias) {
        this(DSL.name(alias), WNWB_TAG);
    }

    /**
     * Create an aliased <code>public.wnwb_tag</code> table reference
     */
    public WnwbTag(Name alias) {
        this(alias, WNWB_TAG);
    }

    /**
     * Create a <code>public.wnwb_tag</code> table reference
     */
    public WnwbTag() {
        this(DSL.name("wnwb_tag"), null);
    }

    public <O extends Record> WnwbTag(Table<O> path, ForeignKey<O, WnwbTagRecord> childPath, InverseForeignKey<O, WnwbTagRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_TAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbTagPath extends WnwbTag implements Path<WnwbTagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbTagPath(Table<O> path, ForeignKey<O, WnwbTagRecord> childPath, InverseForeignKey<O, WnwbTagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbTagPath(Name alias, Table<WnwbTagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbTagPath as(String alias) {
            return new WnwbTagPath(DSL.name(alias), this);
        }

        @Override
        public WnwbTagPath as(Name alias) {
            return new WnwbTagPath(alias, this);
        }

        @Override
        public WnwbTagPath as(Table<?> alias) {
            return new WnwbTagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_TAG_CATEGORY_A43FB0EB, Indexes.WNWB_TAG_CATEGORY_A43FB0EB_LIKE);
    }

    @Override
    public Identity<WnwbTagRecord, Integer> getIdentity() {
        return (Identity<WnwbTagRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbTagRecord> getPrimaryKey() {
        return Keys.WNWB_TAG_PKEY;
    }

    private transient WnwbLemmatagPath _wnwbLemmatag;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_lemmatag</code> table
     */
    public WnwbLemmatagPath wnwbLemmatag() {
        if (_wnwbLemmatag == null)
            _wnwbLemmatag = new WnwbLemmatagPath(this, null, Keys.WNWB_LEMMATAG__WNWB_LEMMATAG_TAG_ID_5A072CB3_FK_WNWB_TAG_ID.getInverseKey());

        return _wnwbLemmatag;
    }

    private transient WnwbSensetagPath _wnwbSensetag;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_sensetag</code> table
     */
    public WnwbSensetagPath wnwbSensetag() {
        if (_wnwbSensetag == null)
            _wnwbSensetag = new WnwbSensetagPath(this, null, Keys.WNWB_SENSETAG__WNWB_SENSETAG_TAG_ID_FCED1B6A_FK_WNWB_TAG_ID.getInverseKey());

        return _wnwbSensetag;
    }

    private transient WnwbSynsettagPath _wnwbSynsettag;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_synsettag</code> table
     */
    public WnwbSynsettagPath wnwbSynsettag() {
        if (_wnwbSynsettag == null)
            _wnwbSynsettag = new WnwbSynsettagPath(this, null, Keys.WNWB_SYNSETTAG__WNWB_SYNSETTAG_TAG_ID_9A41102F_FK_WNWB_TAG_ID.getInverseKey());

        return _wnwbSynsettag;
    }

    @Override
    public WnwbTag as(String alias) {
        return new WnwbTag(DSL.name(alias), this);
    }

    @Override
    public WnwbTag as(Name alias) {
        return new WnwbTag(alias, this);
    }

    @Override
    public WnwbTag as(Table<?> alias) {
        return new WnwbTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbTag rename(String name) {
        return new WnwbTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbTag rename(Name name) {
        return new WnwbTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbTag rename(Table<?> name) {
        return new WnwbTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTag where(Condition condition) {
        return new WnwbTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
