/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbExternalref.WnwbExternalrefPath;
import nu.studer.sample.tables.WnwbLexicon.WnwbLexiconPath;
import nu.studer.sample.tables.records.WnwbExternalsystemRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbExternalsystem extends TableImpl<WnwbExternalsystemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_externalsystem</code>
     */
    public static final WnwbExternalsystem WNWB_EXTERNALSYSTEM = new WnwbExternalsystem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbExternalsystemRecord> getRecordType() {
        return WnwbExternalsystemRecord.class;
    }

    /**
     * The column <code>public.wnwb_externalsystem.id</code>.
     */
    public final TableField<WnwbExternalsystemRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.created_by</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.date_created</code>.
     */
    public final TableField<WnwbExternalsystemRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.updated_by</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.date_updated</code>.
     */
    public final TableField<WnwbExternalsystemRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.is_deleted</code>.
     */
    public final TableField<WnwbExternalsystemRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.name</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.description</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_externalsystem.url_pattern</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> URL_PATTERN = createField(DSL.name("url_pattern"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.reference_pattern</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> REFERENCE_PATTERN = createField(DSL.name("reference_pattern"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.wnwb_externalsystem.local_lexicon_id</code>.
     */
    public final TableField<WnwbExternalsystemRecord, Integer> LOCAL_LEXICON_ID = createField(DSL.name("local_lexicon_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_externalsystem.dc_source</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> DC_SOURCE = createField(DSL.name("dc_source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_externalsystem.note</code>.
     */
    public final TableField<WnwbExternalsystemRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB, this, "");

    private WnwbExternalsystem(Name alias, Table<WnwbExternalsystemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbExternalsystem(Name alias, Table<WnwbExternalsystemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_externalsystem</code> table reference
     */
    public WnwbExternalsystem(String alias) {
        this(DSL.name(alias), WNWB_EXTERNALSYSTEM);
    }

    /**
     * Create an aliased <code>public.wnwb_externalsystem</code> table reference
     */
    public WnwbExternalsystem(Name alias) {
        this(alias, WNWB_EXTERNALSYSTEM);
    }

    /**
     * Create a <code>public.wnwb_externalsystem</code> table reference
     */
    public WnwbExternalsystem() {
        this(DSL.name("wnwb_externalsystem"), null);
    }

    public <O extends Record> WnwbExternalsystem(Table<O> path, ForeignKey<O, WnwbExternalsystemRecord> childPath, InverseForeignKey<O, WnwbExternalsystemRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_EXTERNALSYSTEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbExternalsystemPath extends WnwbExternalsystem implements Path<WnwbExternalsystemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbExternalsystemPath(Table<O> path, ForeignKey<O, WnwbExternalsystemRecord> childPath, InverseForeignKey<O, WnwbExternalsystemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbExternalsystemPath(Name alias, Table<WnwbExternalsystemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbExternalsystemPath as(String alias) {
            return new WnwbExternalsystemPath(DSL.name(alias), this);
        }

        @Override
        public WnwbExternalsystemPath as(Name alias) {
            return new WnwbExternalsystemPath(alias, this);
        }

        @Override
        public WnwbExternalsystemPath as(Table<?> alias) {
            return new WnwbExternalsystemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_EXTERNALSYSTEM_LOCAL_LEXICON_ID_EF06FA64);
    }

    @Override
    public Identity<WnwbExternalsystemRecord, Integer> getIdentity() {
        return (Identity<WnwbExternalsystemRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbExternalsystemRecord> getPrimaryKey() {
        return Keys.WNWB_EXTERNALSYSTEM_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbExternalsystemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_EXTERNALSYSTEM__WNWB_EXTERNALSYSTEM_LOCAL_LEXICON_ID_EF06FA64_FK_WNWB_LEXI);
    }

    private transient WnwbLexiconPath _wnwbLexicon;

    /**
     * Get the implicit join path to the <code>public.wnwb_lexicon</code> table.
     */
    public WnwbLexiconPath wnwbLexicon() {
        if (_wnwbLexicon == null)
            _wnwbLexicon = new WnwbLexiconPath(this, Keys.WNWB_EXTERNALSYSTEM__WNWB_EXTERNALSYSTEM_LOCAL_LEXICON_ID_EF06FA64_FK_WNWB_LEXI, null);

        return _wnwbLexicon;
    }

    private transient WnwbExternalrefPath _wnwbExternalref;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_externalref</code> table
     */
    public WnwbExternalrefPath wnwbExternalref() {
        if (_wnwbExternalref == null)
            _wnwbExternalref = new WnwbExternalrefPath(this, null, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SYS_ID_ID_F0181889_FK_WNWB_EXTERNALSYSTEM_ID.getInverseKey());

        return _wnwbExternalref;
    }

    @Override
    public WnwbExternalsystem as(String alias) {
        return new WnwbExternalsystem(DSL.name(alias), this);
    }

    @Override
    public WnwbExternalsystem as(Name alias) {
        return new WnwbExternalsystem(alias, this);
    }

    @Override
    public WnwbExternalsystem as(Table<?> alias) {
        return new WnwbExternalsystem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbExternalsystem rename(String name) {
        return new WnwbExternalsystem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbExternalsystem rename(Name name) {
        return new WnwbExternalsystem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbExternalsystem rename(Table<?> name) {
        return new WnwbExternalsystem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalsystem where(Condition condition) {
        return new WnwbExternalsystem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalsystem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalsystem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalsystem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalsystem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalsystem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalsystem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalsystem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalsystem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalsystem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
