/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbSynset.WnwbSynsetPath;
import nu.studer.sample.tables.WnwbSynsetrelationtype.WnwbSynsetrelationtypePath;
import nu.studer.sample.tables.records.WnwbSynsetrelationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSynsetrelation extends TableImpl<WnwbSynsetrelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_synsetrelation</code>
     */
    public static final WnwbSynsetrelation WNWB_SYNSETRELATION = new WnwbSynsetrelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbSynsetrelationRecord> getRecordType() {
        return WnwbSynsetrelationRecord.class;
    }

    /**
     * The column <code>public.wnwb_synsetrelation.id</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.created_by</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.date_created</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.updated_by</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.date_updated</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.is_deleted</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.label</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.status</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.a_synset_id</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, Integer> A_SYNSET_ID = createField(DSL.name("a_synset_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.b_synset_id</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, Integer> B_SYNSET_ID = createField(DSL.name("b_synset_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.rel_type_id</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, Integer> REL_TYPE_ID = createField(DSL.name("rel_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.dc_source</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, String> DC_SOURCE = createField(DSL.name("dc_source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.dc_type</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, String> DC_TYPE = createField(DSL.name("dc_type"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.note</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_synsetrelation.rate</code>.
     */
    public final TableField<WnwbSynsetrelationRecord, Double> RATE = createField(DSL.name("rate"), SQLDataType.DOUBLE.nullable(false), this, "");

    private WnwbSynsetrelation(Name alias, Table<WnwbSynsetrelationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbSynsetrelation(Name alias, Table<WnwbSynsetrelationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_synsetrelation</code> table reference
     */
    public WnwbSynsetrelation(String alias) {
        this(DSL.name(alias), WNWB_SYNSETRELATION);
    }

    /**
     * Create an aliased <code>public.wnwb_synsetrelation</code> table reference
     */
    public WnwbSynsetrelation(Name alias) {
        this(alias, WNWB_SYNSETRELATION);
    }

    /**
     * Create a <code>public.wnwb_synsetrelation</code> table reference
     */
    public WnwbSynsetrelation() {
        this(DSL.name("wnwb_synsetrelation"), null);
    }

    public <O extends Record> WnwbSynsetrelation(Table<O> path, ForeignKey<O, WnwbSynsetrelationRecord> childPath, InverseForeignKey<O, WnwbSynsetrelationRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_SYNSETRELATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbSynsetrelationPath extends WnwbSynsetrelation implements Path<WnwbSynsetrelationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbSynsetrelationPath(Table<O> path, ForeignKey<O, WnwbSynsetrelationRecord> childPath, InverseForeignKey<O, WnwbSynsetrelationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbSynsetrelationPath(Name alias, Table<WnwbSynsetrelationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbSynsetrelationPath as(String alias) {
            return new WnwbSynsetrelationPath(DSL.name(alias), this);
        }

        @Override
        public WnwbSynsetrelationPath as(Name alias) {
            return new WnwbSynsetrelationPath(alias, this);
        }

        @Override
        public WnwbSynsetrelationPath as(Table<?> alias) {
            return new WnwbSynsetrelationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_SYNSETRELATION_A_SYNSET_ID_99F48C44, Indexes.WNWB_SYNSETRELATION_B_SYNSET_ID_C84D4349, Indexes.WNWB_SYNSETRELATION_REL_TYPE_ID_EB53DCEC);
    }

    @Override
    public Identity<WnwbSynsetrelationRecord, Integer> getIdentity() {
        return (Identity<WnwbSynsetrelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbSynsetrelationRecord> getPrimaryKey() {
        return Keys.WNWB_SYNSETRELATION_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbSynsetrelationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_A_SYNSET_ID_99F48C44_FK_WNWB_SYNSET_ID, Keys.WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_B_SYNSET_ID_C84D4349_FK_WNWB_SYNSET_ID, Keys.WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_REL_TYPE_ID_EB53DCEC_FK_WNWB_SYNS);
    }

    private transient WnwbSynsetPath _wnwbSynsetrelationASynsetId_99f48c44FkWnwbSynsetId;

    /**
     * Get the implicit join path to the <code>public.wnwb_synset</code> table,
     * via the
     * <code>wnwb_synsetrelation_a_synset_id_99f48c44_fk_wnwb_synset_id</code>
     * key.
     */
    public WnwbSynsetPath wnwbSynsetrelationASynsetId_99f48c44FkWnwbSynsetId() {
        if (_wnwbSynsetrelationASynsetId_99f48c44FkWnwbSynsetId == null)
            _wnwbSynsetrelationASynsetId_99f48c44FkWnwbSynsetId = new WnwbSynsetPath(this, Keys.WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_A_SYNSET_ID_99F48C44_FK_WNWB_SYNSET_ID, null);

        return _wnwbSynsetrelationASynsetId_99f48c44FkWnwbSynsetId;
    }

    private transient WnwbSynsetPath _wnwbSynsetrelationBSynsetIdC84d4349FkWnwbSynsetId;

    /**
     * Get the implicit join path to the <code>public.wnwb_synset</code> table,
     * via the
     * <code>wnwb_synsetrelation_b_synset_id_c84d4349_fk_wnwb_synset_id</code>
     * key.
     */
    public WnwbSynsetPath wnwbSynsetrelationBSynsetIdC84d4349FkWnwbSynsetId() {
        if (_wnwbSynsetrelationBSynsetIdC84d4349FkWnwbSynsetId == null)
            _wnwbSynsetrelationBSynsetIdC84d4349FkWnwbSynsetId = new WnwbSynsetPath(this, Keys.WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_B_SYNSET_ID_C84D4349_FK_WNWB_SYNSET_ID, null);

        return _wnwbSynsetrelationBSynsetIdC84d4349FkWnwbSynsetId;
    }

    private transient WnwbSynsetrelationtypePath _wnwbSynsetrelationtype;

    /**
     * Get the implicit join path to the
     * <code>public.wnwb_synsetrelationtype</code> table.
     */
    public WnwbSynsetrelationtypePath wnwbSynsetrelationtype() {
        if (_wnwbSynsetrelationtype == null)
            _wnwbSynsetrelationtype = new WnwbSynsetrelationtypePath(this, Keys.WNWB_SYNSETRELATION__WNWB_SYNSETRELATION_REL_TYPE_ID_EB53DCEC_FK_WNWB_SYNS, null);

        return _wnwbSynsetrelationtype;
    }

    @Override
    public WnwbSynsetrelation as(String alias) {
        return new WnwbSynsetrelation(DSL.name(alias), this);
    }

    @Override
    public WnwbSynsetrelation as(Name alias) {
        return new WnwbSynsetrelation(alias, this);
    }

    @Override
    public WnwbSynsetrelation as(Table<?> alias) {
        return new WnwbSynsetrelation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSynsetrelation rename(String name) {
        return new WnwbSynsetrelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSynsetrelation rename(Name name) {
        return new WnwbSynsetrelation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSynsetrelation rename(Table<?> name) {
        return new WnwbSynsetrelation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSynsetrelation where(Condition condition) {
        return new WnwbSynsetrelation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSynsetrelation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSynsetrelation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSynsetrelation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSynsetrelation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSynsetrelation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSynsetrelation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSynsetrelation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSynsetrelation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSynsetrelation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
