/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbDefinition.WnwbDefinitionPath;
import nu.studer.sample.tables.records.WnwbStatementRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbStatement extends TableImpl<WnwbStatementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_statement</code>
     */
    public static final WnwbStatement WNWB_STATEMENT = new WnwbStatement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbStatementRecord> getRecordType() {
        return WnwbStatementRecord.class;
    }

    /**
     * The column <code>public.wnwb_statement.id</code>.
     */
    public final TableField<WnwbStatementRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_statement.created_by</code>.
     */
    public final TableField<WnwbStatementRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_statement.date_created</code>.
     */
    public final TableField<WnwbStatementRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_statement.updated_by</code>.
     */
    public final TableField<WnwbStatementRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_statement.date_updated</code>.
     */
    public final TableField<WnwbStatementRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_statement.is_deleted</code>.
     */
    public final TableField<WnwbStatementRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_statement.text</code>.
     */
    public final TableField<WnwbStatementRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_statement.source</code>.
     */
    public final TableField<WnwbStatementRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.wnwb_statement.language</code>.
     */
    public final TableField<WnwbStatementRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>public.wnwb_statement.definition_id</code>.
     */
    public final TableField<WnwbStatementRecord, Integer> DEFINITION_ID = createField(DSL.name("definition_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private WnwbStatement(Name alias, Table<WnwbStatementRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbStatement(Name alias, Table<WnwbStatementRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_statement</code> table reference
     */
    public WnwbStatement(String alias) {
        this(DSL.name(alias), WNWB_STATEMENT);
    }

    /**
     * Create an aliased <code>public.wnwb_statement</code> table reference
     */
    public WnwbStatement(Name alias) {
        this(alias, WNWB_STATEMENT);
    }

    /**
     * Create a <code>public.wnwb_statement</code> table reference
     */
    public WnwbStatement() {
        this(DSL.name("wnwb_statement"), null);
    }

    public <O extends Record> WnwbStatement(Table<O> path, ForeignKey<O, WnwbStatementRecord> childPath, InverseForeignKey<O, WnwbStatementRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_STATEMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbStatementPath extends WnwbStatement implements Path<WnwbStatementRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbStatementPath(Table<O> path, ForeignKey<O, WnwbStatementRecord> childPath, InverseForeignKey<O, WnwbStatementRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbStatementPath(Name alias, Table<WnwbStatementRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbStatementPath as(String alias) {
            return new WnwbStatementPath(DSL.name(alias), this);
        }

        @Override
        public WnwbStatementPath as(Name alias) {
            return new WnwbStatementPath(alias, this);
        }

        @Override
        public WnwbStatementPath as(Table<?> alias) {
            return new WnwbStatementPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_STATEMENT_DEFINITION_ID_C6356A08);
    }

    @Override
    public Identity<WnwbStatementRecord, Integer> getIdentity() {
        return (Identity<WnwbStatementRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbStatementRecord> getPrimaryKey() {
        return Keys.WNWB_STATEMENT_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbStatementRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_STATEMENT__WNWB_STATEMENT_DEFINITION_ID_C6356A08_FK_WNWB_DEFINITION_ID);
    }

    private transient WnwbDefinitionPath _wnwbDefinition;

    /**
     * Get the implicit join path to the <code>public.wnwb_definition</code>
     * table.
     */
    public WnwbDefinitionPath wnwbDefinition() {
        if (_wnwbDefinition == null)
            _wnwbDefinition = new WnwbDefinitionPath(this, Keys.WNWB_STATEMENT__WNWB_STATEMENT_DEFINITION_ID_C6356A08_FK_WNWB_DEFINITION_ID, null);

        return _wnwbDefinition;
    }

    @Override
    public WnwbStatement as(String alias) {
        return new WnwbStatement(DSL.name(alias), this);
    }

    @Override
    public WnwbStatement as(Name alias) {
        return new WnwbStatement(alias, this);
    }

    @Override
    public WnwbStatement as(Table<?> alias) {
        return new WnwbStatement(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbStatement rename(String name) {
        return new WnwbStatement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbStatement rename(Name name) {
        return new WnwbStatement(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbStatement rename(Table<?> name) {
        return new WnwbStatement(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbStatement where(Condition condition) {
        return new WnwbStatement(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbStatement where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbStatement where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbStatement where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbStatement where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbStatement where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbStatement where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbStatement where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbStatement whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbStatement whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
