/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbExternalrelationtype.WnwbExternalrelationtypePath;
import nu.studer.sample.tables.WnwbExternalsystem.WnwbExternalsystemPath;
import nu.studer.sample.tables.WnwbSense.WnwbSensePath;
import nu.studer.sample.tables.WnwbSynset.WnwbSynsetPath;
import nu.studer.sample.tables.records.WnwbExternalrefRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbExternalref extends TableImpl<WnwbExternalrefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_externalref</code>
     */
    public static final WnwbExternalref WNWB_EXTERNALREF = new WnwbExternalref();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbExternalrefRecord> getRecordType() {
        return WnwbExternalrefRecord.class;
    }

    /**
     * The column <code>public.wnwb_externalref.id</code>.
     */
    public final TableField<WnwbExternalrefRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_externalref.created_by</code>.
     */
    public final TableField<WnwbExternalrefRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalref.date_created</code>.
     */
    public final TableField<WnwbExternalrefRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalref.updated_by</code>.
     */
    public final TableField<WnwbExternalrefRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_externalref.date_updated</code>.
     */
    public final TableField<WnwbExternalrefRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_externalref.is_deleted</code>.
     */
    public final TableField<WnwbExternalrefRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalref.reference</code>.
     */
    public final TableField<WnwbExternalrefRecord, String> REFERENCE = createField(DSL.name("reference"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalref.status</code>.
     */
    public final TableField<WnwbExternalrefRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalref.sense_id</code>.
     */
    public final TableField<WnwbExternalrefRecord, Integer> SENSE_ID = createField(DSL.name("sense_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_externalref.synset_id</code>.
     */
    public final TableField<WnwbExternalrefRecord, Integer> SYNSET_ID = createField(DSL.name("synset_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_externalref.sys_id_id</code>.
     */
    public final TableField<WnwbExternalrefRecord, Integer> SYS_ID_ID = createField(DSL.name("sys_id_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalref.rel_type_id</code>.
     */
    public final TableField<WnwbExternalrefRecord, Integer> REL_TYPE_ID = createField(DSL.name("rel_type_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_externalref.rate</code>.
     */
    public final TableField<WnwbExternalrefRecord, Double> RATE = createField(DSL.name("rate"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_externalref.dc_source</code>.
     */
    public final TableField<WnwbExternalrefRecord, String> DC_SOURCE = createField(DSL.name("dc_source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_externalref.dc_type</code>.
     */
    public final TableField<WnwbExternalrefRecord, String> DC_TYPE = createField(DSL.name("dc_type"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_externalref.note</code>.
     */
    public final TableField<WnwbExternalrefRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB, this, "");

    private WnwbExternalref(Name alias, Table<WnwbExternalrefRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbExternalref(Name alias, Table<WnwbExternalrefRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_externalref</code> table reference
     */
    public WnwbExternalref(String alias) {
        this(DSL.name(alias), WNWB_EXTERNALREF);
    }

    /**
     * Create an aliased <code>public.wnwb_externalref</code> table reference
     */
    public WnwbExternalref(Name alias) {
        this(alias, WNWB_EXTERNALREF);
    }

    /**
     * Create a <code>public.wnwb_externalref</code> table reference
     */
    public WnwbExternalref() {
        this(DSL.name("wnwb_externalref"), null);
    }

    public <O extends Record> WnwbExternalref(Table<O> path, ForeignKey<O, WnwbExternalrefRecord> childPath, InverseForeignKey<O, WnwbExternalrefRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_EXTERNALREF);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbExternalrefPath extends WnwbExternalref implements Path<WnwbExternalrefRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbExternalrefPath(Table<O> path, ForeignKey<O, WnwbExternalrefRecord> childPath, InverseForeignKey<O, WnwbExternalrefRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbExternalrefPath(Name alias, Table<WnwbExternalrefRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbExternalrefPath as(String alias) {
            return new WnwbExternalrefPath(DSL.name(alias), this);
        }

        @Override
        public WnwbExternalrefPath as(Name alias) {
            return new WnwbExternalrefPath(alias, this);
        }

        @Override
        public WnwbExternalrefPath as(Table<?> alias) {
            return new WnwbExternalrefPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_EXTERNALREF_REFERENCE_484A5820, Indexes.WNWB_EXTERNALREF_REFERENCE_484A5820_LIKE, Indexes.WNWB_EXTERNALREF_REL_TYPE_ID_5832C6D2, Indexes.WNWB_EXTERNALREF_SENSE_ID_FE9D5580, Indexes.WNWB_EXTERNALREF_SYNSET_ID_DA65B8D8, Indexes.WNWB_EXTERNALREF_SYS_ID_ID_F0181889);
    }

    @Override
    public Identity<WnwbExternalrefRecord, Integer> getIdentity() {
        return (Identity<WnwbExternalrefRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbExternalrefRecord> getPrimaryKey() {
        return Keys.WNWB_EXTERNALREF_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbExternalrefRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_REL_TYPE_ID_5832C6D2_FK_WNWB_EXTE, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SENSE_ID_FE9D5580_FK_WNWB_SENSE_ID, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SYNSET_ID_DA65B8D8_FK_WNWB_SYNSET_ID, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SYS_ID_ID_F0181889_FK_WNWB_EXTERNALSYSTEM_ID);
    }

    private transient WnwbExternalrelationtypePath _wnwbExternalrelationtype;

    /**
     * Get the implicit join path to the
     * <code>public.wnwb_externalrelationtype</code> table.
     */
    public WnwbExternalrelationtypePath wnwbExternalrelationtype() {
        if (_wnwbExternalrelationtype == null)
            _wnwbExternalrelationtype = new WnwbExternalrelationtypePath(this, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_REL_TYPE_ID_5832C6D2_FK_WNWB_EXTE, null);

        return _wnwbExternalrelationtype;
    }

    private transient WnwbSensePath _wnwbSense;

    /**
     * Get the implicit join path to the <code>public.wnwb_sense</code> table.
     */
    public WnwbSensePath wnwbSense() {
        if (_wnwbSense == null)
            _wnwbSense = new WnwbSensePath(this, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SENSE_ID_FE9D5580_FK_WNWB_SENSE_ID, null);

        return _wnwbSense;
    }

    private transient WnwbSynsetPath _wnwbSynset;

    /**
     * Get the implicit join path to the <code>public.wnwb_synset</code> table.
     */
    public WnwbSynsetPath wnwbSynset() {
        if (_wnwbSynset == null)
            _wnwbSynset = new WnwbSynsetPath(this, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SYNSET_ID_DA65B8D8_FK_WNWB_SYNSET_ID, null);

        return _wnwbSynset;
    }

    private transient WnwbExternalsystemPath _wnwbExternalsystem;

    /**
     * Get the implicit join path to the <code>public.wnwb_externalsystem</code>
     * table.
     */
    public WnwbExternalsystemPath wnwbExternalsystem() {
        if (_wnwbExternalsystem == null)
            _wnwbExternalsystem = new WnwbExternalsystemPath(this, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SYS_ID_ID_F0181889_FK_WNWB_EXTERNALSYSTEM_ID, null);

        return _wnwbExternalsystem;
    }

    @Override
    public WnwbExternalref as(String alias) {
        return new WnwbExternalref(DSL.name(alias), this);
    }

    @Override
    public WnwbExternalref as(Name alias) {
        return new WnwbExternalref(alias, this);
    }

    @Override
    public WnwbExternalref as(Table<?> alias) {
        return new WnwbExternalref(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbExternalref rename(String name) {
        return new WnwbExternalref(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbExternalref rename(Name name) {
        return new WnwbExternalref(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbExternalref rename(Table<?> name) {
        return new WnwbExternalref(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalref where(Condition condition) {
        return new WnwbExternalref(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalref where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalref where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalref where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalref where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalref where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalref where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbExternalref where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalref whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbExternalref whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
