/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbLexicalentry.WnwbLexicalentryPath;
import nu.studer.sample.tables.WnwbTag.WnwbTagPath;
import nu.studer.sample.tables.records.WnwbLemmatagRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLemmatag extends TableImpl<WnwbLemmatagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_lemmatag</code>
     */
    public static final WnwbLemmatag WNWB_LEMMATAG = new WnwbLemmatag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbLemmatagRecord> getRecordType() {
        return WnwbLemmatagRecord.class;
    }

    /**
     * The column <code>public.wnwb_lemmatag.id</code>.
     */
    public final TableField<WnwbLemmatagRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_lemmatag.created_by</code>.
     */
    public final TableField<WnwbLemmatagRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lemmatag.date_created</code>.
     */
    public final TableField<WnwbLemmatagRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lemmatag.updated_by</code>.
     */
    public final TableField<WnwbLemmatagRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_lemmatag.date_updated</code>.
     */
    public final TableField<WnwbLemmatagRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_lemmatag.is_deleted</code>.
     */
    public final TableField<WnwbLemmatagRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lemmatag.lexical_entry_id</code>.
     */
    public final TableField<WnwbLemmatagRecord, Integer> LEXICAL_ENTRY_ID = createField(DSL.name("lexical_entry_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lemmatag.tag_id</code>.
     */
    public final TableField<WnwbLemmatagRecord, Integer> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private WnwbLemmatag(Name alias, Table<WnwbLemmatagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbLemmatag(Name alias, Table<WnwbLemmatagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_lemmatag</code> table reference
     */
    public WnwbLemmatag(String alias) {
        this(DSL.name(alias), WNWB_LEMMATAG);
    }

    /**
     * Create an aliased <code>public.wnwb_lemmatag</code> table reference
     */
    public WnwbLemmatag(Name alias) {
        this(alias, WNWB_LEMMATAG);
    }

    /**
     * Create a <code>public.wnwb_lemmatag</code> table reference
     */
    public WnwbLemmatag() {
        this(DSL.name("wnwb_lemmatag"), null);
    }

    public <O extends Record> WnwbLemmatag(Table<O> path, ForeignKey<O, WnwbLemmatagRecord> childPath, InverseForeignKey<O, WnwbLemmatagRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_LEMMATAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbLemmatagPath extends WnwbLemmatag implements Path<WnwbLemmatagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbLemmatagPath(Table<O> path, ForeignKey<O, WnwbLemmatagRecord> childPath, InverseForeignKey<O, WnwbLemmatagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbLemmatagPath(Name alias, Table<WnwbLemmatagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbLemmatagPath as(String alias) {
            return new WnwbLemmatagPath(DSL.name(alias), this);
        }

        @Override
        public WnwbLemmatagPath as(Name alias) {
            return new WnwbLemmatagPath(alias, this);
        }

        @Override
        public WnwbLemmatagPath as(Table<?> alias) {
            return new WnwbLemmatagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_LEMMATAG_LEXICAL_ENTRY_ID_3B4AF2B1, Indexes.WNWB_LEMMATAG_TAG_ID_5A072CB3);
    }

    @Override
    public Identity<WnwbLemmatagRecord, Integer> getIdentity() {
        return (Identity<WnwbLemmatagRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbLemmatagRecord> getPrimaryKey() {
        return Keys.WNWB_LEMMATAG_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbLemmatagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_LEMMATAG__WNWB_LEMMATAG_LEXICAL_ENTRY_ID_3B4AF2B1_FK_WNWB_LEXICALENTRY_ID, Keys.WNWB_LEMMATAG__WNWB_LEMMATAG_TAG_ID_5A072CB3_FK_WNWB_TAG_ID);
    }

    private transient WnwbLexicalentryPath _wnwbLexicalentry;

    /**
     * Get the implicit join path to the <code>public.wnwb_lexicalentry</code>
     * table.
     */
    public WnwbLexicalentryPath wnwbLexicalentry() {
        if (_wnwbLexicalentry == null)
            _wnwbLexicalentry = new WnwbLexicalentryPath(this, Keys.WNWB_LEMMATAG__WNWB_LEMMATAG_LEXICAL_ENTRY_ID_3B4AF2B1_FK_WNWB_LEXICALENTRY_ID, null);

        return _wnwbLexicalentry;
    }

    private transient WnwbTagPath _wnwbTag;

    /**
     * Get the implicit join path to the <code>public.wnwb_tag</code> table.
     */
    public WnwbTagPath wnwbTag() {
        if (_wnwbTag == null)
            _wnwbTag = new WnwbTagPath(this, Keys.WNWB_LEMMATAG__WNWB_LEMMATAG_TAG_ID_5A072CB3_FK_WNWB_TAG_ID, null);

        return _wnwbTag;
    }

    @Override
    public WnwbLemmatag as(String alias) {
        return new WnwbLemmatag(DSL.name(alias), this);
    }

    @Override
    public WnwbLemmatag as(Name alias) {
        return new WnwbLemmatag(alias, this);
    }

    @Override
    public WnwbLemmatag as(Table<?> alias) {
        return new WnwbLemmatag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbLemmatag rename(String name) {
        return new WnwbLemmatag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbLemmatag rename(Name name) {
        return new WnwbLemmatag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbLemmatag rename(Table<?> name) {
        return new WnwbLemmatag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLemmatag where(Condition condition) {
        return new WnwbLemmatag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLemmatag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLemmatag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLemmatag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLemmatag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLemmatag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLemmatag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLemmatag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLemmatag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLemmatag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
