/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.records.WnwbRefcodeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbRefcode extends TableImpl<WnwbRefcodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_refcode</code>
     */
    public static final WnwbRefcode WNWB_REFCODE = new WnwbRefcode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbRefcodeRecord> getRecordType() {
        return WnwbRefcodeRecord.class;
    }

    /**
     * The column <code>public.wnwb_refcode.id</code>.
     */
    public final TableField<WnwbRefcodeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_refcode.created_by</code>.
     */
    public final TableField<WnwbRefcodeRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_refcode.date_created</code>.
     */
    public final TableField<WnwbRefcodeRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_refcode.updated_by</code>.
     */
    public final TableField<WnwbRefcodeRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_refcode.date_updated</code>.
     */
    public final TableField<WnwbRefcodeRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_refcode.is_deleted</code>.
     */
    public final TableField<WnwbRefcodeRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_refcode.domain</code>.
     */
    public final TableField<WnwbRefcodeRecord, String> DOMAIN = createField(DSL.name("domain"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_refcode.code</code>.
     */
    public final TableField<WnwbRefcodeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_refcode.value</code>.
     */
    public final TableField<WnwbRefcodeRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_refcode.language</code>.
     */
    public final TableField<WnwbRefcodeRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(3).nullable(false), this, "");

    private WnwbRefcode(Name alias, Table<WnwbRefcodeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbRefcode(Name alias, Table<WnwbRefcodeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_refcode</code> table reference
     */
    public WnwbRefcode(String alias) {
        this(DSL.name(alias), WNWB_REFCODE);
    }

    /**
     * Create an aliased <code>public.wnwb_refcode</code> table reference
     */
    public WnwbRefcode(Name alias) {
        this(alias, WNWB_REFCODE);
    }

    /**
     * Create a <code>public.wnwb_refcode</code> table reference
     */
    public WnwbRefcode() {
        this(DSL.name("wnwb_refcode"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_REFCODE_CODE_6FFF01D2, Indexes.WNWB_REFCODE_CODE_6FFF01D2_LIKE, Indexes.WNWB_REFCODE_DOMAIN_13324BED, Indexes.WNWB_REFCODE_DOMAIN_13324BED_LIKE);
    }

    @Override
    public Identity<WnwbRefcodeRecord, Integer> getIdentity() {
        return (Identity<WnwbRefcodeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbRefcodeRecord> getPrimaryKey() {
        return Keys.WNWB_REFCODE_PKEY;
    }

    @Override
    public WnwbRefcode as(String alias) {
        return new WnwbRefcode(DSL.name(alias), this);
    }

    @Override
    public WnwbRefcode as(Name alias) {
        return new WnwbRefcode(alias, this);
    }

    @Override
    public WnwbRefcode as(Table<?> alias) {
        return new WnwbRefcode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbRefcode rename(String name) {
        return new WnwbRefcode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbRefcode rename(Name name) {
        return new WnwbRefcode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbRefcode rename(Table<?> name) {
        return new WnwbRefcode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbRefcode where(Condition condition) {
        return new WnwbRefcode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbRefcode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbRefcode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbRefcode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbRefcode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbRefcode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbRefcode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbRefcode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbRefcode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbRefcode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
