/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbDefinition.WnwbDefinitionPath;
import nu.studer.sample.tables.WnwbExternalref.WnwbExternalrefPath;
import nu.studer.sample.tables.WnwbLexicalentry.WnwbLexicalentryPath;
import nu.studer.sample.tables.WnwbSenseexample.WnwbSenseexamplePath;
import nu.studer.sample.tables.WnwbSenserelation.WnwbSenserelationPath;
import nu.studer.sample.tables.WnwbSensetag.WnwbSensetagPath;
import nu.studer.sample.tables.WnwbSynset.WnwbSynsetPath;
import nu.studer.sample.tables.records.WnwbSenseRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSense extends TableImpl<WnwbSenseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_sense</code>
     */
    public static final WnwbSense WNWB_SENSE = new WnwbSense();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbSenseRecord> getRecordType() {
        return WnwbSenseRecord.class;
    }

    /**
     * The column <code>public.wnwb_sense.id</code>.
     */
    public final TableField<WnwbSenseRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_sense.created_by</code>.
     */
    public final TableField<WnwbSenseRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sense.date_created</code>.
     */
    public final TableField<WnwbSenseRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sense.updated_by</code>.
     */
    public final TableField<WnwbSenseRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_sense.date_updated</code>.
     */
    public final TableField<WnwbSenseRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_sense.is_deleted</code>.
     */
    public final TableField<WnwbSenseRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sense.nr</code>.
     */
    public final TableField<WnwbSenseRecord, Integer> NR = createField(DSL.name("nr"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sense.label</code>.
     */
    public final TableField<WnwbSenseRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.wnwb_sense.style</code>.
     */
    public final TableField<WnwbSenseRecord, String> STYLE = createField(DSL.name("style"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.wnwb_sense.status</code>.
     */
    public final TableField<WnwbSenseRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sense.comment</code>.
     */
    public final TableField<WnwbSenseRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_sense.locked_by</code>.
     */
    public final TableField<WnwbSenseRecord, String> LOCKED_BY = createField(DSL.name("locked_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_sense.date_locked</code>.
     */
    public final TableField<WnwbSenseRecord, OffsetDateTime> DATE_LOCKED = createField(DSL.name("date_locked"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_sense.lexical_entry_id</code>.
     */
    public final TableField<WnwbSenseRecord, Integer> LEXICAL_ENTRY_ID = createField(DSL.name("lexical_entry_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_sense.synset_id</code>.
     */
    public final TableField<WnwbSenseRecord, Integer> SYNSET_ID = createField(DSL.name("synset_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_sense.dc_source</code>.
     */
    public final TableField<WnwbSenseRecord, String> DC_SOURCE = createField(DSL.name("dc_source"), SQLDataType.CLOB, this, "");

    private WnwbSense(Name alias, Table<WnwbSenseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbSense(Name alias, Table<WnwbSenseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_sense</code> table reference
     */
    public WnwbSense(String alias) {
        this(DSL.name(alias), WNWB_SENSE);
    }

    /**
     * Create an aliased <code>public.wnwb_sense</code> table reference
     */
    public WnwbSense(Name alias) {
        this(alias, WNWB_SENSE);
    }

    /**
     * Create a <code>public.wnwb_sense</code> table reference
     */
    public WnwbSense() {
        this(DSL.name("wnwb_sense"), null);
    }

    public <O extends Record> WnwbSense(Table<O> path, ForeignKey<O, WnwbSenseRecord> childPath, InverseForeignKey<O, WnwbSenseRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_SENSE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbSensePath extends WnwbSense implements Path<WnwbSenseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbSensePath(Table<O> path, ForeignKey<O, WnwbSenseRecord> childPath, InverseForeignKey<O, WnwbSenseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbSensePath(Name alias, Table<WnwbSenseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbSensePath as(String alias) {
            return new WnwbSensePath(DSL.name(alias), this);
        }

        @Override
        public WnwbSensePath as(Name alias) {
            return new WnwbSensePath(alias, this);
        }

        @Override
        public WnwbSensePath as(Table<?> alias) {
            return new WnwbSensePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_SENSE_LABEL_F98A94E1, Indexes.WNWB_SENSE_LABEL_F98A94E1_LIKE, Indexes.WNWB_SENSE_LEXICAL_ENTRY_ID_818118DC, Indexes.WNWB_SENSE_SYNSET_ID_F32F0334);
    }

    @Override
    public Identity<WnwbSenseRecord, Integer> getIdentity() {
        return (Identity<WnwbSenseRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbSenseRecord> getPrimaryKey() {
        return Keys.WNWB_SENSE_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbSenseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_SENSE__WNWB_SENSE_LEXICAL_ENTRY_ID_818118DC_FK_WNWB_LEXICALENTRY_ID, Keys.WNWB_SENSE__WNWB_SENSE_SYNSET_ID_F32F0334_FK_WNWB_SYNSET_ID);
    }

    private transient WnwbLexicalentryPath _wnwbLexicalentry;

    /**
     * Get the implicit join path to the <code>public.wnwb_lexicalentry</code>
     * table.
     */
    public WnwbLexicalentryPath wnwbLexicalentry() {
        if (_wnwbLexicalentry == null)
            _wnwbLexicalentry = new WnwbLexicalentryPath(this, Keys.WNWB_SENSE__WNWB_SENSE_LEXICAL_ENTRY_ID_818118DC_FK_WNWB_LEXICALENTRY_ID, null);

        return _wnwbLexicalentry;
    }

    private transient WnwbSynsetPath _wnwbSynset;

    /**
     * Get the implicit join path to the <code>public.wnwb_synset</code> table.
     */
    public WnwbSynsetPath wnwbSynset() {
        if (_wnwbSynset == null)
            _wnwbSynset = new WnwbSynsetPath(this, Keys.WNWB_SENSE__WNWB_SENSE_SYNSET_ID_F32F0334_FK_WNWB_SYNSET_ID, null);

        return _wnwbSynset;
    }

    private transient WnwbDefinitionPath _wnwbDefinition;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_definition</code> table
     */
    public WnwbDefinitionPath wnwbDefinition() {
        if (_wnwbDefinition == null)
            _wnwbDefinition = new WnwbDefinitionPath(this, null, Keys.WNWB_DEFINITION__WNWB_DEFINITION_SENSE_ID_07F73760_FK_WNWB_SENSE_ID.getInverseKey());

        return _wnwbDefinition;
    }

    private transient WnwbExternalrefPath _wnwbExternalref;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_externalref</code> table
     */
    public WnwbExternalrefPath wnwbExternalref() {
        if (_wnwbExternalref == null)
            _wnwbExternalref = new WnwbExternalrefPath(this, null, Keys.WNWB_EXTERNALREF__WNWB_EXTERNALREF_SENSE_ID_FE9D5580_FK_WNWB_SENSE_ID.getInverseKey());

        return _wnwbExternalref;
    }

    private transient WnwbSenseexamplePath _wnwbSenseexample;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_senseexample</code> table
     */
    public WnwbSenseexamplePath wnwbSenseexample() {
        if (_wnwbSenseexample == null)
            _wnwbSenseexample = new WnwbSenseexamplePath(this, null, Keys.WNWB_SENSEEXAMPLE__WNWB_SENSEEXAMPLE_SENSE_ID_5B247889_FK_WNWB_SENSE_ID.getInverseKey());

        return _wnwbSenseexample;
    }

    private transient WnwbSenserelationPath _wnwbSenserelationASenseIdC0c51749FkWnwbSenseId;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_senserelation</code> table, via the
     * <code>wnwb_senserelation_a_sense_id_c0c51749_fk_wnwb_sense_id</code> key
     */
    public WnwbSenserelationPath wnwbSenserelationASenseIdC0c51749FkWnwbSenseId() {
        if (_wnwbSenserelationASenseIdC0c51749FkWnwbSenseId == null)
            _wnwbSenserelationASenseIdC0c51749FkWnwbSenseId = new WnwbSenserelationPath(this, null, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_A_SENSE_ID_C0C51749_FK_WNWB_SENSE_ID.getInverseKey());

        return _wnwbSenserelationASenseIdC0c51749FkWnwbSenseId;
    }

    private transient WnwbSenserelationPath _wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_senserelation</code> table, via the
     * <code>wnwb_senserelation_b_sense_id_fec3e062_fk_wnwb_sense_id</code> key
     */
    public WnwbSenserelationPath wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId() {
        if (_wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId == null)
            _wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId = new WnwbSenserelationPath(this, null, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_B_SENSE_ID_FEC3E062_FK_WNWB_SENSE_ID.getInverseKey());

        return _wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId;
    }

    private transient WnwbSensetagPath _wnwbSensetag;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_sensetag</code> table
     */
    public WnwbSensetagPath wnwbSensetag() {
        if (_wnwbSensetag == null)
            _wnwbSensetag = new WnwbSensetagPath(this, null, Keys.WNWB_SENSETAG__WNWB_SENSETAG_SENSE_ID_F7FB7B9D_FK_WNWB_SENSE_ID.getInverseKey());

        return _wnwbSensetag;
    }

    @Override
    public WnwbSense as(String alias) {
        return new WnwbSense(DSL.name(alias), this);
    }

    @Override
    public WnwbSense as(Name alias) {
        return new WnwbSense(alias, this);
    }

    @Override
    public WnwbSense as(Table<?> alias) {
        return new WnwbSense(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSense rename(String name) {
        return new WnwbSense(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSense rename(Name name) {
        return new WnwbSense(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSense rename(Table<?> name) {
        return new WnwbSense(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSense where(Condition condition) {
        return new WnwbSense(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSense where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSense where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSense where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSense where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSense where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSense where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSense where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSense whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSense whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
