/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbSense.WnwbSensePath;
import nu.studer.sample.tables.WnwbSenserelationtype.WnwbSenserelationtypePath;
import nu.studer.sample.tables.records.WnwbSenserelationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSenserelation extends TableImpl<WnwbSenserelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_senserelation</code>
     */
    public static final WnwbSenserelation WNWB_SENSERELATION = new WnwbSenserelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbSenserelationRecord> getRecordType() {
        return WnwbSenserelationRecord.class;
    }

    /**
     * The column <code>public.wnwb_senserelation.id</code>.
     */
    public final TableField<WnwbSenserelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_senserelation.created_by</code>.
     */
    public final TableField<WnwbSenserelationRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelation.date_created</code>.
     */
    public final TableField<WnwbSenserelationRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelation.updated_by</code>.
     */
    public final TableField<WnwbSenserelationRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_senserelation.date_updated</code>.
     */
    public final TableField<WnwbSenserelationRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_senserelation.is_deleted</code>.
     */
    public final TableField<WnwbSenserelationRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelation.label</code>.
     */
    public final TableField<WnwbSenserelationRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.wnwb_senserelation.status</code>.
     */
    public final TableField<WnwbSenserelationRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelation.a_sense_id</code>.
     */
    public final TableField<WnwbSenserelationRecord, Integer> A_SENSE_ID = createField(DSL.name("a_sense_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_senserelation.b_sense_id</code>.
     */
    public final TableField<WnwbSenserelationRecord, Integer> B_SENSE_ID = createField(DSL.name("b_sense_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_senserelation.rel_type_id</code>.
     */
    public final TableField<WnwbSenserelationRecord, Integer> REL_TYPE_ID = createField(DSL.name("rel_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelation.dc_source</code>.
     */
    public final TableField<WnwbSenserelationRecord, String> DC_SOURCE = createField(DSL.name("dc_source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_senserelation.dc_type</code>.
     */
    public final TableField<WnwbSenserelationRecord, String> DC_TYPE = createField(DSL.name("dc_type"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_senserelation.note</code>.
     */
    public final TableField<WnwbSenserelationRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_senserelation.rate</code>.
     */
    public final TableField<WnwbSenserelationRecord, Double> RATE = createField(DSL.name("rate"), SQLDataType.DOUBLE.nullable(false), this, "");

    private WnwbSenserelation(Name alias, Table<WnwbSenserelationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbSenserelation(Name alias, Table<WnwbSenserelationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_senserelation</code> table reference
     */
    public WnwbSenserelation(String alias) {
        this(DSL.name(alias), WNWB_SENSERELATION);
    }

    /**
     * Create an aliased <code>public.wnwb_senserelation</code> table reference
     */
    public WnwbSenserelation(Name alias) {
        this(alias, WNWB_SENSERELATION);
    }

    /**
     * Create a <code>public.wnwb_senserelation</code> table reference
     */
    public WnwbSenserelation() {
        this(DSL.name("wnwb_senserelation"), null);
    }

    public <O extends Record> WnwbSenserelation(Table<O> path, ForeignKey<O, WnwbSenserelationRecord> childPath, InverseForeignKey<O, WnwbSenserelationRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_SENSERELATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbSenserelationPath extends WnwbSenserelation implements Path<WnwbSenserelationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbSenserelationPath(Table<O> path, ForeignKey<O, WnwbSenserelationRecord> childPath, InverseForeignKey<O, WnwbSenserelationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbSenserelationPath(Name alias, Table<WnwbSenserelationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbSenserelationPath as(String alias) {
            return new WnwbSenserelationPath(DSL.name(alias), this);
        }

        @Override
        public WnwbSenserelationPath as(Name alias) {
            return new WnwbSenserelationPath(alias, this);
        }

        @Override
        public WnwbSenserelationPath as(Table<?> alias) {
            return new WnwbSenserelationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_SENSERELATION_A_SENSE_ID_C0C51749, Indexes.WNWB_SENSERELATION_B_SENSE_ID_FEC3E062, Indexes.WNWB_SENSERELATION_REL_TYPE_ID_8718A120);
    }

    @Override
    public Identity<WnwbSenserelationRecord, Integer> getIdentity() {
        return (Identity<WnwbSenserelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbSenserelationRecord> getPrimaryKey() {
        return Keys.WNWB_SENSERELATION_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbSenserelationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_A_SENSE_ID_C0C51749_FK_WNWB_SENSE_ID, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_B_SENSE_ID_FEC3E062_FK_WNWB_SENSE_ID, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_REL_TYPE_ID_8718A120_FK_WNWB_SENS);
    }

    private transient WnwbSensePath _wnwbSenserelationASenseIdC0c51749FkWnwbSenseId;

    /**
     * Get the implicit join path to the <code>public.wnwb_sense</code> table,
     * via the
     * <code>wnwb_senserelation_a_sense_id_c0c51749_fk_wnwb_sense_id</code> key.
     */
    public WnwbSensePath wnwbSenserelationASenseIdC0c51749FkWnwbSenseId() {
        if (_wnwbSenserelationASenseIdC0c51749FkWnwbSenseId == null)
            _wnwbSenserelationASenseIdC0c51749FkWnwbSenseId = new WnwbSensePath(this, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_A_SENSE_ID_C0C51749_FK_WNWB_SENSE_ID, null);

        return _wnwbSenserelationASenseIdC0c51749FkWnwbSenseId;
    }

    private transient WnwbSensePath _wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId;

    /**
     * Get the implicit join path to the <code>public.wnwb_sense</code> table,
     * via the
     * <code>wnwb_senserelation_b_sense_id_fec3e062_fk_wnwb_sense_id</code> key.
     */
    public WnwbSensePath wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId() {
        if (_wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId == null)
            _wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId = new WnwbSensePath(this, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_B_SENSE_ID_FEC3E062_FK_WNWB_SENSE_ID, null);

        return _wnwbSenserelationBSenseIdFec3e062FkWnwbSenseId;
    }

    private transient WnwbSenserelationtypePath _wnwbSenserelationtype;

    /**
     * Get the implicit join path to the
     * <code>public.wnwb_senserelationtype</code> table.
     */
    public WnwbSenserelationtypePath wnwbSenserelationtype() {
        if (_wnwbSenserelationtype == null)
            _wnwbSenserelationtype = new WnwbSenserelationtypePath(this, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_REL_TYPE_ID_8718A120_FK_WNWB_SENS, null);

        return _wnwbSenserelationtype;
    }

    @Override
    public WnwbSenserelation as(String alias) {
        return new WnwbSenserelation(DSL.name(alias), this);
    }

    @Override
    public WnwbSenserelation as(Name alias) {
        return new WnwbSenserelation(alias, this);
    }

    @Override
    public WnwbSenserelation as(Table<?> alias) {
        return new WnwbSenserelation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenserelation rename(String name) {
        return new WnwbSenserelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenserelation rename(Name name) {
        return new WnwbSenserelation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenserelation rename(Table<?> name) {
        return new WnwbSenserelation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelation where(Condition condition) {
        return new WnwbSenserelation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
