/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbLexicon.WnwbLexiconPath;
import nu.studer.sample.tables.records.WnwbTaskorderRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbTaskorder extends TableImpl<WnwbTaskorderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_taskorder</code>
     */
    public static final WnwbTaskorder WNWB_TASKORDER = new WnwbTaskorder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbTaskorderRecord> getRecordType() {
        return WnwbTaskorderRecord.class;
    }

    /**
     * The column <code>public.wnwb_taskorder.id</code>.
     */
    public final TableField<WnwbTaskorderRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_taskorder.created_by</code>.
     */
    public final TableField<WnwbTaskorderRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_taskorder.date_created</code>.
     */
    public final TableField<WnwbTaskorderRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_taskorder.updated_by</code>.
     */
    public final TableField<WnwbTaskorderRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_taskorder.date_updated</code>.
     */
    public final TableField<WnwbTaskorderRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_taskorder.is_deleted</code>.
     */
    public final TableField<WnwbTaskorderRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_taskorder.resources</code>.
     */
    public final TableField<WnwbTaskorderRecord, String> RESOURCES = createField(DSL.name("resources"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.wnwb_taskorder.params</code>.
     */
    public final TableField<WnwbTaskorderRecord, String> PARAMS = createField(DSL.name("params"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>public.wnwb_taskorder.status</code>.
     */
    public final TableField<WnwbTaskorderRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_taskorder.progress</code>.
     */
    public final TableField<WnwbTaskorderRecord, String> PROGRESS = createField(DSL.name("progress"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.wnwb_taskorder.main_lexicon_id</code>.
     */
    public final TableField<WnwbTaskorderRecord, Integer> MAIN_LEXICON_ID = createField(DSL.name("main_lexicon_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_taskorder.other_lexicon_id</code>.
     */
    public final TableField<WnwbTaskorderRecord, Integer> OTHER_LEXICON_ID = createField(DSL.name("other_lexicon_id"), SQLDataType.INTEGER, this, "");

    private WnwbTaskorder(Name alias, Table<WnwbTaskorderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbTaskorder(Name alias, Table<WnwbTaskorderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_taskorder</code> table reference
     */
    public WnwbTaskorder(String alias) {
        this(DSL.name(alias), WNWB_TASKORDER);
    }

    /**
     * Create an aliased <code>public.wnwb_taskorder</code> table reference
     */
    public WnwbTaskorder(Name alias) {
        this(alias, WNWB_TASKORDER);
    }

    /**
     * Create a <code>public.wnwb_taskorder</code> table reference
     */
    public WnwbTaskorder() {
        this(DSL.name("wnwb_taskorder"), null);
    }

    public <O extends Record> WnwbTaskorder(Table<O> path, ForeignKey<O, WnwbTaskorderRecord> childPath, InverseForeignKey<O, WnwbTaskorderRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_TASKORDER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbTaskorderPath extends WnwbTaskorder implements Path<WnwbTaskorderRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbTaskorderPath(Table<O> path, ForeignKey<O, WnwbTaskorderRecord> childPath, InverseForeignKey<O, WnwbTaskorderRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbTaskorderPath(Name alias, Table<WnwbTaskorderRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbTaskorderPath as(String alias) {
            return new WnwbTaskorderPath(DSL.name(alias), this);
        }

        @Override
        public WnwbTaskorderPath as(Name alias) {
            return new WnwbTaskorderPath(alias, this);
        }

        @Override
        public WnwbTaskorderPath as(Table<?> alias) {
            return new WnwbTaskorderPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_TASKORDER_MAIN_LEXICON_ID_89633296, Indexes.WNWB_TASKORDER_OTHER_LEXICON_ID_D5CBEAD2);
    }

    @Override
    public Identity<WnwbTaskorderRecord, Integer> getIdentity() {
        return (Identity<WnwbTaskorderRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbTaskorderRecord> getPrimaryKey() {
        return Keys.WNWB_TASKORDER_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbTaskorderRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_TASKORDER__WNWB_TASKORDER_MAIN_LEXICON_ID_89633296_FK_WNWB_LEXICON_ID, Keys.WNWB_TASKORDER__WNWB_TASKORDER_OTHER_LEXICON_ID_D5CBEAD2_FK_WNWB_LEXICON_ID);
    }

    private transient WnwbLexiconPath _wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId;

    /**
     * Get the implicit join path to the <code>public.wnwb_lexicon</code> table,
     * via the
     * <code>wnwb_taskorder_main_lexicon_id_89633296_fk_wnwb_lexicon_id</code>
     * key.
     */
    public WnwbLexiconPath wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId() {
        if (_wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId == null)
            _wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId = new WnwbLexiconPath(this, Keys.WNWB_TASKORDER__WNWB_TASKORDER_MAIN_LEXICON_ID_89633296_FK_WNWB_LEXICON_ID, null);

        return _wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId;
    }

    private transient WnwbLexiconPath _wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId;

    /**
     * Get the implicit join path to the <code>public.wnwb_lexicon</code> table,
     * via the
     * <code>wnwb_taskorder_other_lexicon_id_d5cbead2_fk_wnwb_lexicon_id</code>
     * key.
     */
    public WnwbLexiconPath wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId() {
        if (_wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId == null)
            _wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId = new WnwbLexiconPath(this, Keys.WNWB_TASKORDER__WNWB_TASKORDER_OTHER_LEXICON_ID_D5CBEAD2_FK_WNWB_LEXICON_ID, null);

        return _wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId;
    }

    @Override
    public WnwbTaskorder as(String alias) {
        return new WnwbTaskorder(DSL.name(alias), this);
    }

    @Override
    public WnwbTaskorder as(Name alias) {
        return new WnwbTaskorder(alias, this);
    }

    @Override
    public WnwbTaskorder as(Table<?> alias) {
        return new WnwbTaskorder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbTaskorder rename(String name) {
        return new WnwbTaskorder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbTaskorder rename(Name name) {
        return new WnwbTaskorder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbTaskorder rename(Table<?> name) {
        return new WnwbTaskorder(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTaskorder where(Condition condition) {
        return new WnwbTaskorder(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTaskorder where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTaskorder where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTaskorder where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTaskorder where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTaskorder where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTaskorder where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbTaskorder where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTaskorder whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbTaskorder whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
