/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbExternalrelationtype.WnwbExternalrelationtypePath;
import nu.studer.sample.tables.WnwbExternalsystem.WnwbExternalsystemPath;
import nu.studer.sample.tables.WnwbLexicalentry.WnwbLexicalentryPath;
import nu.studer.sample.tables.WnwbLexicalresource.WnwbLexicalresourcePath;
import nu.studer.sample.tables.WnwbSenserelationtype.WnwbSenserelationtypePath;
import nu.studer.sample.tables.WnwbSynset.WnwbSynsetPath;
import nu.studer.sample.tables.WnwbSynsetrelationtype.WnwbSynsetrelationtypePath;
import nu.studer.sample.tables.WnwbTaskorder.WnwbTaskorderPath;
import nu.studer.sample.tables.records.WnwbLexiconRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbLexicon extends TableImpl<WnwbLexiconRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_lexicon</code>
     */
    public static final WnwbLexicon WNWB_LEXICON = new WnwbLexicon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbLexiconRecord> getRecordType() {
        return WnwbLexiconRecord.class;
    }

    /**
     * The column <code>public.wnwb_lexicon.id</code>.
     */
    public final TableField<WnwbLexiconRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_lexicon.created_by</code>.
     */
    public final TableField<WnwbLexiconRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.date_created</code>.
     */
    public final TableField<WnwbLexiconRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.updated_by</code>.
     */
    public final TableField<WnwbLexiconRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_lexicon.date_updated</code>.
     */
    public final TableField<WnwbLexiconRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_lexicon.is_deleted</code>.
     */
    public final TableField<WnwbLexiconRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.language</code>.
     */
    public final TableField<WnwbLexiconRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.version</code>.
     */
    public final TableField<WnwbLexiconRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.status</code>.
     */
    public final TableField<WnwbLexiconRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.resource_id</code>.
     */
    public final TableField<WnwbLexiconRecord, Integer> RESOURCE_ID = createField(DSL.name("resource_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.citation</code>.
     */
    public final TableField<WnwbLexiconRecord, String> CITATION = createField(DSL.name("citation"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_lexicon.dc_coverage</code>.
     */
    public final TableField<WnwbLexiconRecord, String> DC_COVERAGE = createField(DSL.name("dc_coverage"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_lexicon.dc_publisher</code>.
     */
    public final TableField<WnwbLexiconRecord, String> DC_PUBLISHER = createField(DSL.name("dc_publisher"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_lexicon.dc_rights</code>.
     */
    public final TableField<WnwbLexiconRecord, String> DC_RIGHTS = createField(DSL.name("dc_rights"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_lexicon.dc_source</code>.
     */
    public final TableField<WnwbLexiconRecord, String> DC_SOURCE = createField(DSL.name("dc_source"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_lexicon.email</code>.
     */
    public final TableField<WnwbLexiconRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.license</code>.
     */
    public final TableField<WnwbLexiconRecord, String> LICENSE = createField(DSL.name("license"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_lexicon.note</code>.
     */
    public final TableField<WnwbLexiconRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_lexicon.url</code>.
     */
    public final TableField<WnwbLexiconRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.wnwb_lexicon.synsetcount</code>.
     */
    public final TableField<WnwbLexiconRecord, Integer> SYNSETCOUNT = createField(DSL.name("synsetcount"), SQLDataType.INTEGER, this, "");

    private WnwbLexicon(Name alias, Table<WnwbLexiconRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbLexicon(Name alias, Table<WnwbLexiconRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_lexicon</code> table reference
     */
    public WnwbLexicon(String alias) {
        this(DSL.name(alias), WNWB_LEXICON);
    }

    /**
     * Create an aliased <code>public.wnwb_lexicon</code> table reference
     */
    public WnwbLexicon(Name alias) {
        this(alias, WNWB_LEXICON);
    }

    /**
     * Create a <code>public.wnwb_lexicon</code> table reference
     */
    public WnwbLexicon() {
        this(DSL.name("wnwb_lexicon"), null);
    }

    public <O extends Record> WnwbLexicon(Table<O> path, ForeignKey<O, WnwbLexiconRecord> childPath, InverseForeignKey<O, WnwbLexiconRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_LEXICON);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbLexiconPath extends WnwbLexicon implements Path<WnwbLexiconRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbLexiconPath(Table<O> path, ForeignKey<O, WnwbLexiconRecord> childPath, InverseForeignKey<O, WnwbLexiconRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbLexiconPath(Name alias, Table<WnwbLexiconRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbLexiconPath as(String alias) {
            return new WnwbLexiconPath(DSL.name(alias), this);
        }

        @Override
        public WnwbLexiconPath as(Name alias) {
            return new WnwbLexiconPath(alias, this);
        }

        @Override
        public WnwbLexiconPath as(Table<?> alias) {
            return new WnwbLexiconPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_LEXICON_RESOURCE_ID_B1C767F2);
    }

    @Override
    public Identity<WnwbLexiconRecord, Integer> getIdentity() {
        return (Identity<WnwbLexiconRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbLexiconRecord> getPrimaryKey() {
        return Keys.WNWB_LEXICON_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbLexiconRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_LEXICON__WNWB_LEXICON_RESOURCE_ID_B1C767F2_FK_WNWB_LEXICALRESOURCE_ID);
    }

    private transient WnwbLexicalresourcePath _wnwbLexicalresource;

    /**
     * Get the implicit join path to the
     * <code>public.wnwb_lexicalresource</code> table.
     */
    public WnwbLexicalresourcePath wnwbLexicalresource() {
        if (_wnwbLexicalresource == null)
            _wnwbLexicalresource = new WnwbLexicalresourcePath(this, Keys.WNWB_LEXICON__WNWB_LEXICON_RESOURCE_ID_B1C767F2_FK_WNWB_LEXICALRESOURCE_ID, null);

        return _wnwbLexicalresource;
    }

    private transient WnwbExternalrelationtypePath _wnwbExternalrelationtype;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_externalrelationtype</code> table
     */
    public WnwbExternalrelationtypePath wnwbExternalrelationtype() {
        if (_wnwbExternalrelationtype == null)
            _wnwbExternalrelationtype = new WnwbExternalrelationtypePath(this, null, Keys.WNWB_EXTERNALRELATIONTYPE__WNWB_EXTERNALRELATIO_LEXICON_ID_B8515F64_FK_WNWB_LEXI.getInverseKey());

        return _wnwbExternalrelationtype;
    }

    private transient WnwbExternalsystemPath _wnwbExternalsystem;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_externalsystem</code> table
     */
    public WnwbExternalsystemPath wnwbExternalsystem() {
        if (_wnwbExternalsystem == null)
            _wnwbExternalsystem = new WnwbExternalsystemPath(this, null, Keys.WNWB_EXTERNALSYSTEM__WNWB_EXTERNALSYSTEM_LOCAL_LEXICON_ID_EF06FA64_FK_WNWB_LEXI.getInverseKey());

        return _wnwbExternalsystem;
    }

    private transient WnwbLexicalentryPath _wnwbLexicalentry;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_lexicalentry</code> table
     */
    public WnwbLexicalentryPath wnwbLexicalentry() {
        if (_wnwbLexicalentry == null)
            _wnwbLexicalentry = new WnwbLexicalentryPath(this, null, Keys.WNWB_LEXICALENTRY__WNWB_LEXICALENTRY_LEXICON_ID_FE960594_FK_WNWB_LEXICON_ID.getInverseKey());

        return _wnwbLexicalentry;
    }

    private transient WnwbSenserelationtypePath _wnwbSenserelationtype;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_senserelationtype</code> table
     */
    public WnwbSenserelationtypePath wnwbSenserelationtype() {
        if (_wnwbSenserelationtype == null)
            _wnwbSenserelationtype = new WnwbSenserelationtypePath(this, null, Keys.WNWB_SENSERELATIONTYPE__WNWB_SENSERELATIONTYPE_LEXICON_ID_82C3453D_FK_WNWB_LEXICON_ID.getInverseKey());

        return _wnwbSenserelationtype;
    }

    private transient WnwbSynsetPath _wnwbSynset;

    /**
     * Get the implicit to-many join path to the <code>public.wnwb_synset</code>
     * table
     */
    public WnwbSynsetPath wnwbSynset() {
        if (_wnwbSynset == null)
            _wnwbSynset = new WnwbSynsetPath(this, null, Keys.WNWB_SYNSET__WNWB_SYNSET_LEXICON_ID_2D4135F8_FK_WNWB_LEXICON_ID.getInverseKey());

        return _wnwbSynset;
    }

    private transient WnwbSynsetrelationtypePath _wnwbSynsetrelationtype;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_synsetrelationtype</code> table
     */
    public WnwbSynsetrelationtypePath wnwbSynsetrelationtype() {
        if (_wnwbSynsetrelationtype == null)
            _wnwbSynsetrelationtype = new WnwbSynsetrelationtypePath(this, null, Keys.WNWB_SYNSETRELATIONTYPE__WNWB_SYNSETRELATIONTYPE_LEXICON_ID_8F83F300_FK_WNWB_LEXICON_ID.getInverseKey());

        return _wnwbSynsetrelationtype;
    }

    private transient WnwbTaskorderPath _wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_taskorder</code> table, via the
     * <code>wnwb_taskorder_main_lexicon_id_89633296_fk_wnwb_lexicon_id</code>
     * key
     */
    public WnwbTaskorderPath wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId() {
        if (_wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId == null)
            _wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId = new WnwbTaskorderPath(this, null, Keys.WNWB_TASKORDER__WNWB_TASKORDER_MAIN_LEXICON_ID_89633296_FK_WNWB_LEXICON_ID.getInverseKey());

        return _wnwbTaskorderMainLexiconId_89633296FkWnwbLexiconId;
    }

    private transient WnwbTaskorderPath _wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_taskorder</code> table, via the
     * <code>wnwb_taskorder_other_lexicon_id_d5cbead2_fk_wnwb_lexicon_id</code>
     * key
     */
    public WnwbTaskorderPath wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId() {
        if (_wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId == null)
            _wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId = new WnwbTaskorderPath(this, null, Keys.WNWB_TASKORDER__WNWB_TASKORDER_OTHER_LEXICON_ID_D5CBEAD2_FK_WNWB_LEXICON_ID.getInverseKey());

        return _wnwbTaskorderOtherLexiconIdD5cbead2FkWnwbLexiconId;
    }

    @Override
    public WnwbLexicon as(String alias) {
        return new WnwbLexicon(DSL.name(alias), this);
    }

    @Override
    public WnwbLexicon as(Name alias) {
        return new WnwbLexicon(alias, this);
    }

    @Override
    public WnwbLexicon as(Table<?> alias) {
        return new WnwbLexicon(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbLexicon rename(String name) {
        return new WnwbLexicon(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbLexicon rename(Name name) {
        return new WnwbLexicon(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbLexicon rename(Table<?> name) {
        return new WnwbLexicon(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLexicon where(Condition condition) {
        return new WnwbLexicon(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLexicon where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLexicon where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLexicon where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLexicon where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLexicon where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLexicon where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbLexicon where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLexicon whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbLexicon whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
