/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nu.studer.sample.Indexes;
import nu.studer.sample.Keys;
import nu.studer.sample.Public;
import nu.studer.sample.tables.WnwbLexicon.WnwbLexiconPath;
import nu.studer.sample.tables.WnwbSenserelation.WnwbSenserelationPath;
import nu.studer.sample.tables.records.WnwbSenserelationtypeRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WnwbSenserelationtype extends TableImpl<WnwbSenserelationtypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.wnwb_senserelationtype</code>
     */
    public static final WnwbSenserelationtype WNWB_SENSERELATIONTYPE = new WnwbSenserelationtype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WnwbSenserelationtypeRecord> getRecordType() {
        return WnwbSenserelationtypeRecord.class;
    }

    /**
     * The column <code>public.wnwb_senserelationtype.id</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.created_by</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.date_created</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, OffsetDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.updated_by</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.date_updated</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, OffsetDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.is_deleted</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, Boolean> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.name</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.direction</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, String> DIRECTION = createField(DSL.name("direction"), SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.description</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.other</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, Integer> OTHER = createField(DSL.name("other"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.lexicon_id</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, Integer> LEXICON_ID = createField(DSL.name("lexicon_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.omw_name</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, String> OMW_NAME = createField(DSL.name("omw_name"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.wnwb_senserelationtype.priority</code>.
     */
    public final TableField<WnwbSenserelationtypeRecord, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER, this, "");

    private WnwbSenserelationtype(Name alias, Table<WnwbSenserelationtypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WnwbSenserelationtype(Name alias, Table<WnwbSenserelationtypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.wnwb_senserelationtype</code> table
     * reference
     */
    public WnwbSenserelationtype(String alias) {
        this(DSL.name(alias), WNWB_SENSERELATIONTYPE);
    }

    /**
     * Create an aliased <code>public.wnwb_senserelationtype</code> table
     * reference
     */
    public WnwbSenserelationtype(Name alias) {
        this(alias, WNWB_SENSERELATIONTYPE);
    }

    /**
     * Create a <code>public.wnwb_senserelationtype</code> table reference
     */
    public WnwbSenserelationtype() {
        this(DSL.name("wnwb_senserelationtype"), null);
    }

    public <O extends Record> WnwbSenserelationtype(Table<O> path, ForeignKey<O, WnwbSenserelationtypeRecord> childPath, InverseForeignKey<O, WnwbSenserelationtypeRecord> parentPath) {
        super(path, childPath, parentPath, WNWB_SENSERELATIONTYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WnwbSenserelationtypePath extends WnwbSenserelationtype implements Path<WnwbSenserelationtypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WnwbSenserelationtypePath(Table<O> path, ForeignKey<O, WnwbSenserelationtypeRecord> childPath, InverseForeignKey<O, WnwbSenserelationtypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WnwbSenserelationtypePath(Name alias, Table<WnwbSenserelationtypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WnwbSenserelationtypePath as(String alias) {
            return new WnwbSenserelationtypePath(DSL.name(alias), this);
        }

        @Override
        public WnwbSenserelationtypePath as(Name alias) {
            return new WnwbSenserelationtypePath(alias, this);
        }

        @Override
        public WnwbSenserelationtypePath as(Table<?> alias) {
            return new WnwbSenserelationtypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WNWB_SENSERELATIONTYPE_LEXICON_ID_82C3453D);
    }

    @Override
    public Identity<WnwbSenserelationtypeRecord, Integer> getIdentity() {
        return (Identity<WnwbSenserelationtypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WnwbSenserelationtypeRecord> getPrimaryKey() {
        return Keys.WNWB_SENSERELATIONTYPE_PKEY;
    }

    @Override
    public List<ForeignKey<WnwbSenserelationtypeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WNWB_SENSERELATIONTYPE__WNWB_SENSERELATIONTYPE_LEXICON_ID_82C3453D_FK_WNWB_LEXICON_ID);
    }

    private transient WnwbLexiconPath _wnwbLexicon;

    /**
     * Get the implicit join path to the <code>public.wnwb_lexicon</code> table.
     */
    public WnwbLexiconPath wnwbLexicon() {
        if (_wnwbLexicon == null)
            _wnwbLexicon = new WnwbLexiconPath(this, Keys.WNWB_SENSERELATIONTYPE__WNWB_SENSERELATIONTYPE_LEXICON_ID_82C3453D_FK_WNWB_LEXICON_ID, null);

        return _wnwbLexicon;
    }

    private transient WnwbSenserelationPath _wnwbSenserelation;

    /**
     * Get the implicit to-many join path to the
     * <code>public.wnwb_senserelation</code> table
     */
    public WnwbSenserelationPath wnwbSenserelation() {
        if (_wnwbSenserelation == null)
            _wnwbSenserelation = new WnwbSenserelationPath(this, null, Keys.WNWB_SENSERELATION__WNWB_SENSERELATION_REL_TYPE_ID_8718A120_FK_WNWB_SENS.getInverseKey());

        return _wnwbSenserelation;
    }

    @Override
    public List<Check<WnwbSenserelationtypeRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("wnwb_senserelationtype_other_check"), "((other >= 0))", true),
            Internal.createCheck(this, DSL.name("wnwb_senserelationtype_priority_check"), "((priority >= 0))", true)
        );
    }

    @Override
    public WnwbSenserelationtype as(String alias) {
        return new WnwbSenserelationtype(DSL.name(alias), this);
    }

    @Override
    public WnwbSenserelationtype as(Name alias) {
        return new WnwbSenserelationtype(alias, this);
    }

    @Override
    public WnwbSenserelationtype as(Table<?> alias) {
        return new WnwbSenserelationtype(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenserelationtype rename(String name) {
        return new WnwbSenserelationtype(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenserelationtype rename(Name name) {
        return new WnwbSenserelationtype(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WnwbSenserelationtype rename(Table<?> name) {
        return new WnwbSenserelationtype(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelationtype where(Condition condition) {
        return new WnwbSenserelationtype(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelationtype where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelationtype where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelationtype where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelationtype where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelationtype where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelationtype where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WnwbSenserelationtype where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelationtype whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WnwbSenserelationtype whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
